### ISSUE TITLE
Bug: "Lance" lesson in shogi basics displays wrong completion message

### ISSUE THREAD

**Issue by Marken-Foo** [WandererXII/lishogi#100]
When finishing "The lance" lesson in the shogi basics course (https://lishogi.org/learn/), the message for "The knight" lesson is displayed instead ("Congratulations! You have mastered the knight.")

![learn lance-knight bug](https://user-images.githubusercontent.com/41288521/100878162-c2c7e480-34e4-11eb-90c3-9cf1c0c07fdc.png)

**Comment by WandererXII** [comment]
Hey, thanks a lot for submitting this, fixed here https://github.com/WandererXII/lishogi/commit/f5d054220ec7bc093d3997179cf1d6058074f8b6
