### ISSUE TITLE
Refund rating loss from cheater

### ISSUE THREAD

**Issue by Little-Mage** [WandererXII/lishogi#101]
I know I had already informed you about this https://lishogi.org/FgTum53as9uU. This is just so you don't forget since there are a lot of issues.

**Comment by kleffa** [comment]
how you know was a cheater?

**Comment by Little-Magician** [comment]
We already knew he was a cheater but I gave him another chance then he played like engine, son I put the moves one by one in shogiGUI and analyzed with Gikou and his accuracy was 80% when normally it should be around <50%
Here's the game in KIF format if you wanna check it out yourself.
[Rogue_is_gote.zip](https://github.com/WandererXII/lishogi/files/5632975/Rogue_is_gote.zip)
