### ISSUE TITLE
White/Black flipped in SFEN and a few places

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#103]
In lishogi's current SFEN interpretation, the 'w' is being interpreted as sente's turn, and for 'b' it's gote's.
In the finished game's page the piece symbols beside the names are also flipped https://lishogi.org/JdafFcIowKXV
![Screenshot_20201203-093649](https://user-images.githubusercontent.com/14817065/100952241-2127ae00-354b-11eb-8f3b-a534dc4be83b.png)
Also in analysis board https://lishogi.org/JdafFcIo/white#62 
![Screenshot_20201203-094246](https://user-images.githubusercontent.com/14817065/100952739-099cf500-354c-11eb-974b-9749b5a5b594.png)

The url is flipped too. https://lishogi.org/JdafFcIo/white shows sente's perspective, not gote's.

**Comment by justremember** [comment]
I realized the problem is with how the mobile browser shows ☗ and ☖. The characters themselves gets flipped in dark mode. Which is fine for regular browsers but not in mobile. Maybe replace the unicode characters altogether with images?

**Comment by WandererXII** [comment]
I guess the best solution is to create new characters in [fonts/lishogi.sfd](https://github.com/WandererXII/lishogi/tree/master/public/font) and use those symbols.
The black/white thing is a real mess, after we get the more pressing issues resolved, I will prob rewrite everything to sente/gote.

**Comment by justremember** [comment]
Ok it seems this is fixed except for the ☗ and ☖. 
And I just noticed some few bugs, if from the board editor you click Continue from here > Play with the computer https://lishogi.org/editor/lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/9/LNSGKGSNL_w_-_1 the preview is flipped. But when starting a from position game in the homepage the preview looks fine.
Also the hover text here always says "white". Should be sente & gote
![image](https://user-images.githubusercontent.com/14817065/101909680-bebb5700-3bb5-11eb-9415-9d655c29a778.png)
Lastly this is more of a request, it would be less confusing if sente/black was to the left.

**Comment by WandererXII** [comment]
Ok, I will swap those and fix the hover ups, I also tried this with the unicode chars - https://stackoverflow.com/questions/32915485/how-to-prevent-unicode-characters-from-rendering-as-emoji-in-html-from-javascrip, so maybe they won't be flipped on android phones? Didn't test it tho.

**Comment by WandererXII** [comment]
Swapped black and white and fixed the hover text here https://github.com/WandererXII/lishogi/commit/78143b6fd69880c9ddc71ead43f1c9dcc97b61a9 - this will be visible after I update the server, and also tried putting monospace next to the ☗/☖ https://github.com/WandererXII/lishogi/commit/f05e3040321931923b8e31643da6f8b259aac3e8 - this is live.
I don't have a phone around that does this, so I can't test it, two random virtual phones I tried also didn't work. How does this display for you https://jsfiddle.net/m1tkc54e @justremember? If this doesn't work I will just create the fonts, I think I will have to do that anyways since Kitao-Kawasaki notation also displays these little things...

**Comment by justremember** [comment]
Just opened https://jsfiddle.net/m1tkc54e on my phone, doesn't work, still shows the characters as emojis...

**Comment by WandererXII** [comment]
I added the font containing ☗/☖, samsung (I think?) phones now shouldn't force their emojis on these characters. I still need to add them to the notation tho, so Kitao-Kawasaki notation and Japanese notation(after I add ☗/☖) will still be flipped, I will update that later today or tomorrow.

**Comment by justremember** [comment]
Wdyt about changing the routes here to sente/gote? https://lishogi.org/JdafFcIo/white

**Comment by ddugovic** [comment]
In https://en.wikipedia.org/wiki/Handicap_(shogi) the players are named uwate (white; handicap-giver moves first) and shitate (black).

**Comment by WandererXII** [comment]
> In https://en.wikipedia.org/wiki/Handicap_(shogi) the players are named uwate (white; handicap-giver moves first) and shitate (black) instead of sente and gote.

I created a separate issue for this https://github.com/WandererXII/lishogi/issues/286
Other than that I consider this issue closed, since color was refactored.
