### ISSUE TITLE
Naming tournaments after chess players, not shogi players

### ISSUE THREAD

**Issue by YoGazeFish** [WandererXII/lishogi#104]
If you leave a tournament name empty, a text below says it will name the tournament after a proficient shogi player, however it names the tournament after a proficient chess player, not a proficient shogi player. Not really super important but something to bring to your attention.

**Comment by justremember** [comment]
The list of talented chess players is in https://github.com/WandererXII/lishogi/blob/master/modules/common/src/main/GreatPlayer.scala. Anyone can submit a pull request changing these names w/ pro shogi players. I can do it if I have time.

**Comment by justremember** [comment]
Ok I think it's just a matter of scraping this wikipedia page https://en.wikipedia.org/wiki/Category:Professional_shogi_players

**Comment by timezombi** [comment]
I'm not 100% sure about this, but it may be a bit of a taboo to name a tournament after an active or living player. Perhaps a safer bet would be to only include deceased and/or retired players in the list of names to draw from.

**Comment by YosefZaghi** [comment]
Low key, if I became a god at shogi, I would be down to have a tournament named after me xD. But on the real, why not? @timezombi

**Comment by justremember** [comment]
If not shogi players we can name tournaments after shogi terms like "Tataki no fu" or "Yoseai" http://www.shogi.net/shogivocab/vocabhtml.html. Not shogi openings though because that would confuse players.

**Comment by Marken-Foo** [comment]
It would be even more of a taboo to name a tournament after deceased players it seems, after discussion in the Japanese channel in the Discord server. It would be best to avoid naming tournaments after players at all for legal, and most importantly cultural reasons - personal names are special, and not to be lightly used.

Best to find more neutral alternatives for naming tournaments.

**Comment by jonager** [comment]
I'll try to fix this

**Comment by jonager** [comment]
@justremember @Marken-Foo maybe we can name them after Japanese cities?

**Comment by Marken-Foo** [comment]
@jonager playok is a Polish site, and popular in South-East Asia for certain games (makruk, xiangqi), so make of that what you will with regard to their naming choices (where are those cities in?). I think lishogi should be a neutral ground, so avoiding using names specifically from any one place, culture, language, timezone or country would be good: perhaps shogi proverbs or tesuji, perhaps names of gemstones, perhaps names of trees or some creatively-named pantone colours even.

Place names can also be sensitive (cf. any number of place name disputes between China/Japan/Korea/Russia/South-East Asian countries), and moreover I feel confusing (e.g. is the tournament restricted to only people from that city? Timezone? Does it have regional significance? etc.)

Maybe I'm overthinking this, but I feel something more neutral would be better.

**Comment by jonager** [comment]
@Marken-Foo most players from western countries don't know anything about shogi proverbs or terms(including myself), so having a tournament named "Tataki no fu" wouldn't be too useful. I feel city names should be fine, but I can see how it could be a sensitive subject for some people or be confusing. 

I'll use gemstones names for now that's a good idea, maybe trees or animal names too.
