### ISSUE TITLE
During analysis, the analysed variants show up in some internal computer notation

### ISSUE THREAD

**Issue by KarolS** [WandererXII/lishogi#106]
During analysis, the analysed variants show up in some internal computer notation. See picture below:
![obraz](https://user-images.githubusercontent.com/1790750/101105656-66d98a80-35ce-11eb-9600-62428862a84c.png)

**Comment by WandererXII** [comment]
That's usi with the coordinates changed to number-number system, usi should be number-letter originally. Not sure if that would make it better or even more confusing. We plan to replace this with proper san soon hopefully.

**Comment by WandererXII** [comment]
This was solved with shogiops https://github.com/WandererXII/shogiops
