### ISSUE TITLE
Captchas

### ISSUE THREAD

**Issue by YoGazeFish** [WandererXII/lishogi#107]
For some CAPTCHAs, the solution is to drop a piece but on the CAPTCHA, one isn't given the option to drop a piece so it would be impossible to post in the forums if you received that particular captcha. Here is the link to the game with the captcha. The CAPTCHA is the last move. https://lishogi.org/QD6cqNTo

**Comment by justremember** [comment]
P-72 was already checkmate. No need to drop a piece.

**Comment by WandererXII** [comment]
It's as justremember said, this [funciton](https://github.com/WandererXII/lishogi/blob/master/modules/game/src/main/GameRepo.scala#L338) should should return only a game where last move is not a drop, so it should never happen that  the checkmate would have to be with a dropped piece, in the game you provided the last move is "+P-72" which is correct.
