### ISSUE TITLE
Suggestion: More variants 

### ISSUE THREAD

**Issue by YoGazeFish** [WandererXII/lishogi#108]
Hello! The site is going gr8 so far! Just a suggestion, why don't u add some variants to make the site more fun to play on. 
Here are some variants to choose from: https://en.wikipedia.org/wiki/Category:Shogi_variants

**Comment by justremember** [comment]
Shogi variants are a planned long-term feature. You can discuss possible shogi variants in the Lishogi discord https://discord.gg/YFtpMGg3rR

**Comment by WandererXII** [comment]
Added minishogi - https://lishogi.org/blog/YbjRcRIAACMAFpGD/minishogi-and-much-more.
If you want to request a specific variant, please start a new issue.
