### ISSUE TITLE
Twitch API (feature streamers playing shogi)

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#110]
> Streaming rules
> Include the keyword "lishogi.org" in your stream title and use the category "Chess" when you stream on Lishogi.

https://lishogi.org/streamer/edit

Here is the code which needs to be changed; and someone needs to act as a moderator to approve streamer applications:
https://github.com/WandererXII/lishogi/blob/28010b44377213059a298c62226d8f7bf97c5e8d/modules/streamer/src/main/Streaming.scala#L100

Here is Twitch's API to get the game ID for shogi:
https://dev.twitch.tv/docs/api/reference#get-games

**Comment by justremember** [comment]
Will workon this when I have time.
