### ISSUE TITLE
Sound - Speech - Unpromotion

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#111]
Currently if I play `S-33=` (no promotion) the speech synthesis says "underpromote".  However shogi does not allow pieces to [underpromote](https://www.merriam-webster.com/dictionary/underpromotion): pieces either promote or they do not promote.

**Comment by justremember** [comment]
Fix was pushed already https://github.com/WandererXII/lishogi/commit/55bd9d2bd6d08f7c0318fb138055c5b8667e989a
Though Wanderer hasn't deployed the most recent changes yet.
