### ISSUE TITLE
AI freezes when starting a game from position

### ISSUE THREAD

**Issue by jbs-768** [WandererXII/lishogi#112]
How to reproduce:

0) Start a game as black against Stockfish 8 f.ex. from position `S3/P1PPPH3/1P1G4P/1K4R2/LN3G1NL w PPPPPNLBp 43`

0) Make any move

0) AI freezes until time out

It seems to me that sente/gote/white/black might be flipped when exporting sfen from a previous game or when importing it to a new game.

**Comment by WandererXII** [comment]
Thanks for submitting this. You are correct that white/black is flipped, I'm currently fixing that. But the position _S3/P1PPPH3/1P1G4P/1K4R2/LN3G1NL w PPPPPNLBp 43_ isn't valid there is only one king, and all the pieces are one color except the one pawn in hand, may I ask how did you obtain this sfen?

**Comment by WandererXII** [comment]
I did some fixes, the engine didn't really recognized the pieces in hand in games from position, maybe the fix also solved the problem you were having. The colors are still flipped now tho, working on that.

**Comment by jbs-768** [comment]
Great, that seems to have fixed it. I obtained the sfen from analysis -> continue from position, but sadly don't have the exact game any more (there definitely should have been two kings though). I'll let you know if I encounter it again.

Thanks for the great work on Lishogi!
