### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by Namelecc** [WandererXII/lishogi#113]
404 error Page not found has the "Chess Pursuit" game on it, which isn't exactly shogi ;)

**Comment by justremember** [comment]
This puzzle instead https://www.youtube.com/watch?v=kDZKM0iVxZs or even just a random tsumeshogi from http://playshogi.com/ would be nice.

**Comment by WandererXII** [comment]
I really like the _Hako iri musume_ idea. I suppose there isn't js version of it around. If not, I will look into creating that when I have time.

**Comment by WandererXII** [comment]
https://lishogi.org/blog/YbjRcRIAACMAFpGD/minishogi-and-much-more
