### ISSUE TITLE
Suggestion: Board Editor should have option for putting "All the rest of the pieces" into opponent's hand.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#114]
When making Lishogi Study chapters with an initial position through the board editor, it is really tedious to create a tsumeshogi type position from a cleared board. In tsumeshogi and other puzzles with partial position diagrams, usually only a few pieces will be placed on the board, with all the rest of the pieces being in the opponent's hand.

However, from the board editor, in order to put all the rest of the pieces in your opponent's hand, you need to drag each piece to your opponent's hand! I've resorted to creating a chapter with the board diagram without pieces in hand, then I create a new chapter from that initial position. In the new chapter, I modify the SFEN string for the initial position. It works but it's still really inefficient!

**Comment by justremember** [comment]
Working on this now.
