### ISSUE TITLE
when Im watching someelse plays, I dont see the pieces in hand of those players

### ISSUE THREAD

**Issue by kleffa** [WandererXII/lishogi#115]
this is a little confusing, they should be shown always.
I think this happend in previews of game, but not sure

**Comment by WandererXII** [comment]
Where exactly this occurs, I can see pieces in hand on lishogiTV, the preview on the main page is board only, it probably makes sense to add the pieces on top and bottom of that, although the layout is going to suffer. Is that what you meant?

**Comment by kleffa** [comment]
I noted in tournament halls and the main previews, but I think maybe change
from square to should work
