### ISSUE TITLE
Bug: Malformed SFEN in Analysis Mode for pieces in hand.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#118]
The pieces in hand are malformed in the SFENs of positions in game analysis mode.

As an example, the SFEN generated from this game (https://lishogi.org/mebcMPNr/black#36) has random pieces interposed inside the string to represent pawns in hand. If you have a mixed up order for pieces in hand, many external SFEN parsers will break. Either all pieces should be placed in a specific order to work with the grammar for parsers or better yet the notation should use the factorized shorthand.

For instance, "ln1g4l/1ks1g2+R1/1pppp1n1p/p5p2/9/P1P2r3/1PNPP1P1P/2K2S3/L1SG2GNL b PSPpbpb 19". Notice how the pieces in hand "PSPpbpb" have the bishop and pawns mixed up in order! The pieces in hand should instead say "SPPbbpp" or "S2p2b2p" to parse correctly in a program like ShogiGUI.

The problem is most apparent with pawns since it is more common to have more than 2 of them in your hand.

This is related to #29, but the malformed pieces in hand portion of the SFEN string is the part which is breaking more consistently now.

![image](https://user-images.githubusercontent.com/600562/101439203-e619d780-38c8-11eb-9600-03936c62947d.png)

**Comment by timezombi** [comment]
For reference, there is an example of the grammar used for a SFEN parser here:
https://code.google.com/archive/p/shogitools/wikis/sfen_start.wiki

**Comment by WandererXII** [comment]
Hey, thanks, fixed here 3dfb67d907d9dda793708f3c3b8ddc2c69aab318, it should now be like this in case it's still wrong somewhere feel free to reopen this issue.

> The pieces are always listed in the order rook, bishop, gold, silver, knight, lance, pawn; and with all black pieces before all white pieces.
