### ISSUE TITLE
""typo"" in the meta tag for the description (<meta name="description">)

### ISSUE THREAD

**Issue by PhirosWolf** [WandererXII/lishogi#120]
In the metadata for description, `<meta name="description" content="....">`, when playing a game says "ABC (1500) **plays** XYZ (1500) in a [type of game] ([game time]) game of **chess**. Game is still played after 4 moves. Click to replay, analyse, and discuss the game!".

I think this should be corrected to "ABC (1500) **is playing against** XYZ (1500) in [...] game of **shogi**. [...]". (Not sure about "is playing against". I'm not a native english speaker).

**Comment by WandererXII** [comment]
Hey, thanks for submitting the issue! I fixed it here 6011cd6f02535ebb2d2ae70446fb62bfef9fddf1, the change will be visible after I update the server again, prob in like a week.
