### ISSUE TITLE
Bug: Very short sound plays after making a move in correspondence

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#121]
Maybe 1/10 of a second. But it's noticeable and could be annoying.

**Comment by WandererXII** [comment]
Yeah, it gets pretty annoying, I noticed it only when anon player plays correspondence tho?

**Comment by justremember** [comment]
I hear it when playing on my account.

**Comment by WandererXII** [comment]
I just removed the sound for now, after we merge the sound rework from lichess, I guess we will add it back again. 269785535bfb3ba3f6e9123f5b3738804cee89d7
