### ISSUE TITLE
Bug: chesslike notation shows in conditional premoves in correspondence

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#123]
![image](https://user-images.githubusercontent.com/14817065/101922770-6d679380-3bc6-11eb-805a-4804847207fe.png)

**Comment by WandererXII** [comment]
Noted, I'll try to apply the same notation system there too

**Comment by justremember** [comment]
Oh there is a worse bug, conditional premoves just don't work.

**Comment by WandererXII** [comment]
I think it only doesn't work when you are playing a correspondence game as an anon player... And playing correspondence game without an account makes no sense, I will look into disabling it.
I might be wrong tho, but when two registered players play it worked for me, or maybe there is something else that triggers it?

**Comment by WandererXII** [comment]
Fixed here b934d01efb82ce9e8e0caea3a0dd2722cafd261e
