### ISSUE TITLE
Bug?: Stockfish 2 does not make a move when it is getting mated and has one move available?

### ISSUE THREAD

**Issue by zig1000** [WandererXII/lishogi#124]
While pettily bullying Stockfish 2 and about to finish it off, it hung for minutes on end ignoring its one legal move:
![image](https://user-images.githubusercontent.com/10562960/101984550-1e664080-3c50-11eb-841b-8c274cbbfdb3.png)

**Comment by WandererXII** [comment]
Hmm weird, seems stockfish doesn't like getting bullied. I will fix this asap. Thanks for reporting this!

**Comment by justremember** [comment]
Is this already fixed? @WandererXII

**Comment by WandererXII** [comment]
> Is this already fixed? @WandererXII

I haven't been able to replicate this, and I also haven't seen any other reports like this, so I don't what could be the cause behind this. A lot of stuff about fishnet/shoginet was also changed since then. If anyone had similar experience mention it here please.
