### ISSUE TITLE
Posting on forums (I know it's not a bug)

### ISSUE THREAD

**Issue by nexxogen** [WandererXII/lishogi#127]
Hello.

First of all, a big fat **THANK YOU** for making lishogi a reality. Shogi desperately needed a server with features which chess servers have had forever.

I'm opening this issue here just to give a suggestion that you unlock the forums (at least feedbacks) even for people who haven't played a lot of games, while the server is still in development. I have a lot of feedback to give, but I can't because I haven't played enough games, and I can't play enough games because there's hardly anyone there to play against. I think it's crucial that you receive as much feedback as possible in the early stages in order to avoid the situation where some people might give up on lishogi and never come back because it lacks some features that it will most likely get in the future which could have been addressed much earlier. As there's not enough players to play many games, I think it is crucial that the forums be unlocked in these initial stages.

I sincerely believe that lishogi can become THE shogi server to play on.

I could write the feedback here, but I don't want to pollute the Issues page because it's meant for issue reporting and not feedback.

**Comment by timezombi** [comment]
If you want to give additional feedback, you can also try joining the discord server: https://discord.gg/YFtpMGg3rR

**Comment by nexxogen** [comment]
> If you want to give additional feedback, you can also try joining the discord server: https://discord.gg/YFtpMGg3rR

I did. But I don't see a channel for giving feedback.

**Comment by justremember** [comment]
What do you mean by forums being "unlocked"? Not sure I understand what you are asking.

**Comment by nexxogen** [comment]
> What do you mean by forums being "unlocked"? Not sure I understand what you are asking.

When I open forums, there is no option to create a new topic or post a reply to an existing one. Instead, I get the message saying something like "You can't post yet. Play more games."

I checked it now and it seems that it became possible for me to create new topics and reply to existing ones. So I guess that it was enabled in the meantime?

**Comment by justremember** [comment]
IMO it's a fair feature. You gotta use the site for a while to give feedback. And it seems like playing with a bot unlocks the forums too.

**Comment by nexxogen** [comment]
> IMO it's a fair feature. You gotta use the site for a while to give feedback. And it seems like playing with a bot unlocks the forums too.

I never said it wasn't a fair feature. My point is that **in the beginning stages** the feedback is much more valuable than in later stages of development, so the forum should be unlocked until a bit further in development when the issues get fixed and features get added. Then you can lock it and require players to play more games in order to use it. I think it's fair to treat the current state of lishogi as an open beta. Having that in mind, it doesn't make much sense to set limits on giving feedback. It is actually very counterproductive.

**Comment by WandererXII** [comment]
Currently the condition for posting in forums is "u.count.game > 0 && u.createdSinceDays(2)", so the message "Play more games" is a bit misleading, playing one and waiting for two days is enough. I could remove the two days waiting period or reduce it to one day at least. These waiting periods are a great way to prevent spam, but with the current traffic it is probably not necessary. Maybe increasing game count and removing the waiting period?
But if you have something specific in mind (bugs, features) feel free to post them here.

**Comment by nexxogen** [comment]
> Currently the condition for posting is "u.count.game > 0 && u.createdSinceDays(2)", so the message "Play more games" is a bit misleading, playing one and waiting for two days is enough. I could remove the two days waiting period or reduce it to one day at least. These waiting periods are a great way to prevent spam tho, but with the current traffic it is probably not necessary. Maybe increasing game count to 5 and removing the waiting period?
> But if you have something specific in mind (bugs, features) feel free to post them here.

If playing against the computer counts, then you can have maybe 3 games, but I would definitely not have any waiting period.

I already posted a pretty lengthy post in the Feedback forum, so please check it out when you have time.

**Comment by WandererXII** [comment]
The only requirement to post on forums now is to play at least three games
