### ISSUE TITLE
Bug: no promotion pop-up in captcha

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#128]
Seems that it assumes the rook will promote here.
![image](https://user-images.githubusercontent.com/14817065/102295218-d6daff80-3f42-11eb-97ca-435f0b67ffe6.png)

**Comment by WandererXII** [comment]
Hmm, server checks only the origin and destination square, so it doesn't notice the lack of promotion. We could either add the promotion option and check for it or filter out checkmates requiring promotion. Adding the promotion overlay is going to be a bit of a pain, maybe we could just automatically promote or not promote to the correct answer... I will try that.

**Comment by justremember** [comment]
Also there's 2 possible mates here, maybe it was expecting the other one or sth

**Comment by WandererXII** [comment]
https://github.com/WandererXII/lishogi/commit/d07fad6242d014078fba4c2e68c6f0a1efe30e2f
