### ISSUE TITLE
Feature request: show name beside time in analysis board

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#131]
Figuring out who's who in analysis board can be confusing, user has to look at coordinates or go to first move to see which perspective he's looking at. Lichess doesn't have this problem because pieces are colored.

![image](https://user-images.githubusercontent.com/14817065/102685784-eb392980-41da-11eb-8a96-c2828eaaecc8.png)

**Comment by WandererXII** [comment]
Added names next to the clock, looks good and makes it easier to tell the sides apart. Slight problem might be that coords outside are getting blocked more than before.

**Comment by WandererXII** [comment]
09ffe82519fb79f585ddc489bc8268e3e371c2ce, 4ca9aa7813a5274a26323421457f31d11e7007b9
