### ISSUE TITLE
not a big deal I suppose

### ISSUE THREAD

**Issue by kyngeSac** [WandererXII/lishogi#138]
...just that the promoted Bishop and promoted Knight look very similar to me in the "western" piece set.  I don't know what's standard or whatever, just thought I'd mention it.  But grateful for the site!

**Comment by CouchTomato87** [comment]
You mean the internationalized set?

![image](https://user-images.githubusercontent.com/52322435/103152915-8b063280-475a-11eb-86cf-81e1fd4461d0.png)

Keep in mind that the promoted bishop is called a (dragon) horse. As such, that piece has dragon-like horns and scales. In that sense, it's not so different than distinguishing the tall king and queen in chess. One has spikes (the queen), while the other has a cross.

**Comment by kyngeSac** [comment]
That's the one --- I'll get used to it for sure --- great site!

**Comment by justremember** [comment]
Not sure how it will look, but maybe the dragon could be looking upward instead with its mouth wide open.

**Comment by CouchTomato87** [comment]
I believe I tried a wider mouth, but it looked awkward. Looking upward would be very hard in terms of being efficient with space, especially since shogi pieces are narrower at the top.

**Comment by CouchTomato87** [comment]
Oh, and when you said dragon, did you mean dragon king, not dragon horse? I think kyngeSac said he was confused between the horse and promoted knight though. If anything, I may sometimes confuse the dragon and horse though.

**Comment by justremember** [comment]
Yep I meant dragon king. Just noticed that you mistook the dragon for horse in that previous message, so maybe dragon is the one that needs fixing. Irdk how the horse could be changed.
