### ISSUE TITLE
Byo-Yomi

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#14]
In chess, players can accurately predict how many moves remain in a game and budget their time accordingly.  In shogi, byo-yomi is a superior time control so players do not attempt to use the clock as a means to defeat their opponent.

**Comment by WandererXII** [comment]
Thanks, that's something I definitely should implement. It might take me a while, since it seems like I will need to rewrite a lot of code, but this seems like a must.

**Comment by Little-Magician** [comment]
This site supports byoyomi https://www.pychess.org/
Here's its github https://github.com/gbtami/pychess-variants
Hopefully this helps.

**Comment by ddugovic** [comment]
Thanks, as a Lichess developer myself who talked with the dev who implemented clock times for Lichess, I'm willing to take a shot at implementing this.

**Comment by WandererXII** [comment]
That sounds great guys. It would be perfect, if you could get this to work @ddugovic.
I have to warn you thought, the code I wrote is a mess right now. I was gonna refactor it, or at least clean unnecessary parts from lichess, but I couldn't manage to find any time - writing final thesis in uni this year.
That being said, I believe I didn't touch the code with clock times at all or at least not significantly, so it should be okay. The process of making this thing run locally should be the same as with lichess, but I think that there will be some issues, since some parts got changed, I will try to test it tonight.

**Comment by ddugovic** [comment]
Many thanks for this amazing project and best of luck with your final thesis!

(I've also guided some devs through setting up lila before, so no worries if you can't get to it right away.)

**Comment by WandererXII** [comment]
Thank you very much:)
If you run into any issues let me know. I noticed git complaining about some submodules, hopefully tomorrow I will update everything to make it work properly.

**Comment by ddugovic** [comment]
Fair enough.  As you predicted, my "magic build" command failed (even if I `mkdir node_modules && mkdir ui/node_modules` obviously I need to gulp/yarn install the correct modules/versions which at the moment I'm forgetting how to do):

```
$ git pull && git submodule update --init --recursive && ./ui/build && ./bin/dev compile

Already up to date.
building ui modules with target=dev and mode=build
node: v10.19.0
yarn: 1.22.5
ls: cannot access 'node_modules/@*': No such file or directory
ls: cannot access 'ui/*/node_modules': No such file or directory
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
error Package "shogiground" refers to a non-existing file '"/home/liskadan/lila/ui/shogiground"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by WandererXII** [comment]
Yeah, sorry about that. I think sbt would also complain about some stuff. And also lila-ws... Sorry it's late here, I will make it work tomorrow, hope you don't mind.

**Comment by ddugovic** [comment]
Yeah, no worries whatsoever, it's all in good fun and I'll likely be playing Woogles.io in the interim.  Sorry if I got overeager in sharing the site with friends too early!

**Comment by WandererXII** [comment]
Definitely not a problem, share it as much as you can:) The site certainly has many issues right now, but it wouldn't be possible for me to find them alone.
./ui/build should work now. sbt also works on my machine. I will also update lila-ws. In case I missed something or if you run into any issues, let me know.

**Comment by ddugovic** [comment]
Thanks.  I suppose my next question is: which Java version should I use to `sbt compile`?  Possibly I've done something tremendously dumb by having OpenJDK 11 installed:

```
➜  lishogi git:(master) ✗ java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

...
[error] ## Exception when compiling 309 sources to /home/lila/lishogi/target/scala-2.13/classes
[error] java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$PositionImpl$
[error] xsbt.DelegatingReporter$.convert(DelegatingReporter.scala:149)
[error] xsbt.DelegatingReporter.info0(DelegatingReporter.scala:181)
[error] scala.tools.nsc.reporters.MakeFilteringForwardingReporter.doReport(ForwardingReporter.scala:59)
[error] scala.tools.nsc.reporters.FilteringReporter.info0(Reporter.scala:93)
[error] scala.reflect.internal.Reporter.filteredInfo(Reporting.scala:116)
[error] scala.reflect.internal.Reporter.error(Reporting.scala:111)
...
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] java.base/java.lang.Thread.run(Thread.java:834)
[error]
[error] java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$PositionImpl$
[error]         at xsbt.DelegatingReporter$.convert(DelegatingReporter.scala:149)
[error]         at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:181)
[error]         at scala.tools.nsc.reporters.MakeFilteringForwardingReporter.doReport(ForwardingReporter.scala:59)
...
[error] Caused by: java.lang.ClassNotFoundException: xsbt.DelegatingReporter$PositionImpl$
[error]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[error]         at xsbt.DelegatingReporter$.convert(DelegatingReporter.scala:149)
[error]         at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:181)
```

**Comment by WandererXII** [comment]
I'm using OpenJDK-14 and it seems to be working.
But if lichess works with jdk 11 I think this should too. Try running ./lila instead of sbt I also seem to get some error running just sbt.

**Comment by ddugovic** [comment]
OK, yes you are correct.  So now I have a running dev instance and would like to build the UI assets.

```
$ ./ui/build

building ui modules with target=dev and mode=build
node: v10.19.0
yarn: 1.22.5
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.86s.
/usr/bin/parallel
+ parallel --gnu -j+4 --halt 2 --bar build ::: shogiground shogiutil common
0% 0:3=0s common
### ui/shogiutil ###
yarn run v1.22.5
$ yarn run compile
$ ../../node_modules/typescript/bin/tsc --outDir . --sourceMap --declaration
Done in 9.62s.
33% 1:2=0s common
### ui/common ###
yarn run v1.22.5
$ yarn run compile
$ ../../node_modules/typescript/bin/tsc --incremental
src/resize.ts(1,21): error TS2307: Cannot find module 'shogiground/types' or its corresponding type declarations.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
error Command failed with exit code 1.
parallel: This job failed:
build common
```

**Comment by WandererXII** [comment]
Sorry I'm late, somehow I missed your reply. Try compiling shogiground first `yarn workspace shogiground run dev`, I had the same issue compiling with parallel and this solved it for me. If it doesn't work, I will investigate deeper.

**Comment by ddugovic** [comment]
Thanks for the ample assistance getting my environment set up.

Unfortunately #67 is a bit alarming so at this time I'm afraid to change any code, let alone implement this.

**Comment by jonager** [comment]
@ddugovic @WandererXII  Hi, I'm still a very junior developer but I'd like to contribute to the project, I know javascript/typescript but not much scala, but willing to learn. Could you guys guide me on how to get everything set up? thank you

**Comment by CouchTomato87** [comment]
On the subject of byo-yomi, not only would you have to adjust what's rapid and casual for byo-yomi timers, but I think we also need to adjust what's rapid, casual, blitz, bullet, and ultrabullet for increment timers. A "rapid" game of shogi is not the same as a rapid one for chess, and the cutoffs should be increased. I'm thinking something around a 2x factor?

**Comment by ddugovic** [comment]
Yeah... separately I started changing the time controls at https://github.com/ddugovic/lishogi/tree/calm-clock since in chess the estimated game time is:
base + increment * 40

whereas for shogi I think the estimated game time is more like:
base + increment * 60

**Comment by CouchTomato87** [comment]
Ah cool. So for Shogi, we don't have much data on it being played with increment. But at least with direct comparison to chess, maybe something like base + increment * 80 if we're still keeping increment as an option? And based on feedback from Japanese players, having the option is nice.

Also wondering if you were planning on adding go/janggi style multiple byo-yomi periods. This is also available at Pychess, so you can refer to that as well to see how it was implemented.

**Comment by ddugovic** [comment]
Well, I guess... I've been very firmly in the byo-yomi only stance, but players keep suggesting "why not both" although I think increment encourages players to make bad moves.

As far as how to estimate game time for shogi with increment... it cannot be estimated, because exchanges and drops tend to increase the move count.  (With byo-yomi in theory drops are also problematic, however players attempt to avoid spending hundreds of moves in time pressure, so game durations are at least somewhat predictable.)

**Comment by ddugovic** [comment]
Sure, support for go/janggi-style time controls with multiple byo-yomi periods could be interesting, although I think the code would get complicated and players might find the UI confusing at first.

**Comment by timezombi** [comment]
I said this before in discord, but this is important enough to reiterate! My vote is firmly in the column of both increment and byoyomi support. Large Simuls are much easier to get through on low time if you are using increment. Also, the premove feature (a great feature to have in time trouble) largely becomes useless with non-zero byoyomi enabled.

Were it not for increment, I think I would have lost all the simuls I created!

I also think the popularity of Fischer style increment on Shogi Club 24 and the special televised blitz matches on Abema have contributed to greater awareness of the increment time control.

For completely new players, though, I agree it might be confusing. Additional tutorial popups or documentation may have to be created to make the difference between byoyomi and increment more clear. 

Whilst spectating a new player not accustomed to byoyomi, they almost always start panicking when their initial time allotment gets close to zero. This is a legitimate fear with increment but completely against their best interest in byoyomi (which does not activate until the initial time allotment runs out).

**Comment by timezombi** [comment]
> Sure, support for go/janggi-style time controls with multiple byo-yomi periods could be interesting, although I think the code would get complicated and players might find the UI confusing at first.

It's my understanding that multiple byoyomi periods in Shogi is rarely seen in amateur play, however there is a popular time control in professional play which uses an interesting twist on the concept of multiple periods. Essentially, you are always given the ceiling of your allotted time. If you start with 60 minutes and only use up 59 seconds, then you still have 60 minutes left! However, if you use up 60 seconds to make your move, then you only have 59 minutes left.

The equivalent of this _round-up-to-nearest-minute_ time control would be 1 minutes of initial allotted time and N periods. You can replicate this same experience I mentioned above by having 60 separate 1 minute periods. 

I think this could be a really interesting time control for long games which can be implemented with either rounding up (like in professional play) or with support for very large number of periods (e.g. 1 to 60 would work). I tried once to play this time control at the local Shogi meetup but I couldn't find a clock that supported arbitrarily large numbers of periods. Unfortunately, most of them would only go up to 5 periods if they supported byoyomi.

**Comment by ddugovic** [comment]
I do understand that playing with an increment is becoming increasingly popular; also, commentary of top-10 players' games is pitiful, when players are speeding to stay ahead of each other on the clock (GM Howell: "I don't know if [Black] did this on purpose... he allowed a bishop to take a rook"):
https://clips.twitch.tv/BloodyGeniusWerewolfFloof

Perhaps for simuls, the host deserves a larger byo-yomi than the players, at least while multiple players remain.  I'm not sure.

Perhaps there is a better way to display the clock; adding byo-yomi to the initial clock time has an advantage of being easier to understand and a disadvantage that players already familiar with how byo-yomi works may unexpectedly lose on time.

**Comment by CouchTomato87** [comment]
Hmmm, I see your points. Maybe the best solution would be to allow for the extra options (increment, byoyomi periods), but only allow rated games on byo-yomi timers? I think rated can still apply to byo-yomi periods because in the long run, they don't really add much time at all to the game.

When you pull down the dropdown menu to choose your game speed, which right now just has "Real time" and "Correspondence," we can have "Real time (byo-yomi)," "Real time (increment)," and "Correspondence. For Increment, only casual would be allowed to be selected.

**Comment by CIO61** [comment]
I think a hybrid format of time control, having both byo-yomi and increment is the best of both worlds. 

In byo-yomi styled games, the player that enters byo-yomi first will always have more time to think in their turn in total compared to the other player.
In increment games, in low time periods you can lose the game by not having enough time to move a piece(and no, i don't think premoves are a good solution to that as it almost feels like gambling). 

When having both, the game flow goes the same up until a player reaches byoyomi. The byoyomi player would lose the increments and only play with byoyomi time, while the other player can still spend time or accumulate time(if he plays faster than increment time, that is). It balances off the negative aspects of both time controls without entirely flipping them around.

**Comment by CouchTomato87** [comment]
I don't think we should be inventing new forms of time controls at this point.

**Comment by WandererXII** [comment]
For issues with current implementation of byoymi, please submit a new issue
