### ISSUE TITLE
Inviting others to Correspondence games.

### ISSUE THREAD

**Issue by CricketForJapan** [WandererXII/lishogi#140]
I have invited other players to correspondence games, but unless we are both logged in, then they will not see my invite. In lichess an invite for correspondence game remains, even if the player sending the invite logs out. This also applied to rematches in correspondence chess.

**Comment by WandererXII** [comment]
Thanks for letting me know, I will get on it.

**Comment by CricketForJapan** [comment]
I suppose you would not want the game challenges to hang unaccepted indefinitely.  Is it possible to add a time limit of a few weeks, and then the invite disappears. Cheers

**Comment by WandererXII** [comment]
e6da42343ec3f0e0e93ed2fc56bf536f36134a02
