### ISSUE TITLE
Bug: cannot move any piece on the board after clicking held piece once

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#141]
The board is "locked" it seems, when I click on a held piece. Only after clicking the held piece again will the board be released, and I can move other pieces again.

**Comment by WandererXII** [comment]
That's how click to drop is right now. I will change it so that the board 'unlocks' after clicking on a piece that is on the board.

**Comment by justremember** [comment]
Or dragging any piece, I hope.

**Comment by WandererXII** [comment]
Dragging has nothing to do with this?

**Comment by justremember** [comment]
Sometimes I do a mix of clicking and dragging, so it will be convenient if I can still drag a piece on the board even after clicking a piece in hand.

**Comment by IanOsgood** [comment]
The behavior I would expect is to click on the held piece again to unselect it.

**Comment by nexxogen** [comment]
> The behavior I would expect is to click on the held piece again to unselect it.

That is certainly not desirable. With pieces on the board, when you click on a piece, clicking on another will automatically deselect the previously selected piece. This should be the same with pieces in hand.

**Comment by WandererXII** [comment]
07d72c24e8400940c6084e93031d4312dddbb52c b4c3f5ceb99a936a2c8c389572f981cf525081f1
