### ISSUE TITLE
Increase simul visibility

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#145]
https://lishogi.org/simul does not show all created simuls, for example https://lishogi.org/simul/pZM49yMF .

Lichess has rate limiting to prevent abuse, but currently Lishogi does not have tons of simul givers, so maybe increase this configured limit?  Alternatively I forget if streamers, titled players, etc. have higher "credits" so maybe Shogi_Harbour could register that sometime...

https://github.com/WandererXII/lishogi/blob/2feea9ae815e373b6fc70e5cc82af6bcf0c3d5e4/modules/simul/src/main/Env.scala#L61

**Comment by justremember** [comment]
Fixed already @WandererXII unless you'd like to increase visibility more, somehow...
