### ISSUE TITLE
Suggestion: Info about correspondence etiquette

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#146]
Would be nice to have a blog post/FAQ item about correspondence etiquette, and link it somewhere within the correspondence game .

**Comment by justremember** [comment]
My bad. https://lishogi.org/faq#correspondence But, still great to have a link to that FAQ item ingame.

**Comment by TheYoBots** [comment]
Relevant lila commit (PR): https://github.com/ornicar/lila/pull/9131
