### ISSUE TITLE
Bug: SFEN notation when creating study chapter is wrong

### ISSUE THREAD

**Issue by Marken-Foo** [WandererXII/lishogi#148]
When using the board editor within the lishogi study editor, then going to the SFEN tab, the resulting SFEN is wrong (promoted pieces represented with single letter, presumably the current backend representation).

![image](https://user-images.githubusercontent.com/41288521/103473267-bb407780-4dd1-11eb-9402-c80dc20fcbba.png)

(picture shows board position that was input in background "+r+b+s+n+l+p3/9/9/9/9/9/9/9/+R+B+S+N+L+P3 b - 1", and bugged SFEN in foreground "dhamut3/9/9/9/9/9/9/9/DHAMUT3 b - 1")

**Comment by WandererXII** [comment]
Thanks for reporting this, should be fixed now. ade53d32725340e2710df7d4abeaa4a3a50d207c
