### ISSUE TITLE
Bug: chesslike notation in correspondence unconditional move confirmation & browser notifs

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#149]
Haven't been able to screenshot the browser notif one but just trust me on this xD
![image](https://user-images.githubusercontent.com/14817065/103502308-cb1c9200-4e8b-11eb-83a5-4827b3b0f813.png)

**Comment by WandererXII** [comment]
47ffa5918bc4a4050a8102b072f90305287f6a53 and 4bc7a67ce2b8af5293e4b4e582d276e765b18519
