### ISSUE TITLE
Studies use wrong notation for variation moves

### ISSUE THREAD

**Issue by catask** [WandererXII/lishogi#15]
When creating a study, the main line uses correct shogi notation in the form of number-letter and file-rank. However, when one creates a variation, it switches to chess notation where the letter denotes the file and number denotes the rank. Example: 

https://lishogi.org/study/mDKASaJX

![image](https://user-images.githubusercontent.com/58996479/99281165-d2aeab80-27f7-11eb-9214-93d428a0ce01.png)

**Comment by WandererXII** [comment]
Thanks for letting me know! This should be easy to fix. Expect a fix soon:)

**Comment by WandererXII** [comment]
Should be fixed - force refresh to see changes. If I missed something (quite possible), let me know, I will leave this issue open for a while. Thanks for reporting it.

**Comment by WandererXII** [comment]
Seems to be fixed.
