### ISSUE TITLE
Handicaps in editor

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#154]
In https://lishogi.org/editor "Popular openings" should be renamed to "Popular handicaps". I guess popular openings can have their own section. Also gote (always handicap giver) moves first in all handicaps.
Here is an example of a handicap kifu. Note who moves first as well as the coordinates orientation. https://shogidb2.com/games/0988b1552d1ffb651948ee96c7eeaa794dc6557b

**Comment by WandererXII** [comment]
d90583d55cd5d170e82d71b32728f76e7b087291 and bb3d3966f48ef3856e09d68de9c0e87293b29ce8
