### ISSUE TITLE
Bug in board editor: cannot click to add to held pieces

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#157]
https://lishogi.org/editor

**Comment by justremember** [comment]
Ohh, clicking the empty slot on the hand adds 1 piece. Should've looked more into it before making this issue, sorry.

**Comment by WandererXII** [comment]
I fixed it after I read this, should've mentioned it, sorry:D I will try to do better with issue tracking.
https://github.com/WandererXII/lishogi/commit/bb37171a07599a4b243a88df9b0df718d516ca44
