### ISSUE TITLE
Error when trying to reload server analyzed game

### ISSUE THREAD

**Issue by killerducky** [WandererXII/lishogi#159]
https://lishogi.org/3yGV7R9MgYkW
This game has been analyzed already, but clicking either microscope icon or "analysis board" both 404:

https://lishogi.org/3yGV7R9M/white#97
404 - Resource not found

**Comment by WandererXII** [comment]
Fixed, this little fella was to blame - https://github.com/WandererXII/lishogi/blob/master/modules/analyse/src/main/Info.scala#L62
