### ISSUE TITLE
Bug: correspondence analysis window stuck in infinite refresh loop

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#164]
Cannot give any more context other than what's in the video.

https://user-images.githubusercontent.com/14817065/104115208-bf2b4700-5347-11eb-8fb3-0f3db3d99b56.mp4

**Comment by WandererXII** [comment]
Console shows anything?

**Comment by justremember** [comment]
Forgot to check. But the problem seems to have disappeared now, after 1 turn. Seems like the bug only happens after a very specific set of conditions.

**Comment by justremember** [comment]
Never happened anymore so I closed it.
