### ISSUE TITLE
Make YaneuraOu engine analysis in lishogi studies too

### ISSUE THREAD

**Issue by abunickabhi** [WandererXII/lishogi#165]
The YaneuraOu works for analysing shogi games. Since I have made a few lishogi studies. Can it work for analysing chapters in lishogi studies too?

**Comment by ddugovic** [comment]
Lishogi studies handle handicap imbalances (with unusual material) whereas I believe currently [YaneuraOh does not](https://github.com/yaneurao/YaneuraOu/issues/158).

**Comment by justremember** [comment]
This is implemented already no? @WandererXII  Or are there still bugs that need fixing?

**Comment by abunickabhi** [comment]
Yes I think this is implemented now. Even for handicap games right?

**Comment by WandererXII** [comment]
> Yes I think this is implemented now. Even for handicap games right?

Yep
