### ISSUE TITLE
Typo: Game display preferences shows chess coordinates instead of Shogi Coordinates

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#17]
In the game display preferences (https://lishogi.org/account/preferences/game-display), the option for "Board coordinates" says the following... 

> Board coordinates (A-H, 1-8)

Whereas I would expect it to say... "Board Coordinates (A-I, 1-9)" instead. 

Although I would consider changing this string in the future in consideration of alternative notation/coordinate systems used in Shogi. Most players I know use either two numbers (Arabic numerals) for the coordinates or the Japanese style coordinates of an Arabic numeral to denote file and a Japanese numeral to designate rank.

**Comment by WandererXII** [comment]
Thanks, fixed, will push to the server with other fixes.

I intent to add different coordinates in the future, so everyone can choose, which they like. I thought (A-I, 1-9) might be most neutral, but you are probably correct that two numerals are more common.
