### ISSUE TITLE
All Black 2-Kanji Piece Set

### ISSUE THREAD

**Issue by samtcifihi** [WandererXII/lishogi#177]
Currently the only two kanji piece sets available have red promotion sides. Would it be possible to add at least one two kanji set with Black promotion side? Of the current piece sets, orangain is the one I like best, except for having a red promotion side.

**Comment by samtcifihi** [comment]
Upon further research, CouchTomato's 2-Kanji Ryoko are by far my favorite, if those would be possible to add.

**Comment by Little-Mage** [comment]
The ryoko pieces were made xenmious which are 1-kanji so I'm confused to which set you're referring to.

**Comment by samtcifihi** [comment]
https://github.com/Little-Mage/ShogiGUI-piece-sets/blob/master/PNG/2-Kanji%20Ryoko.png

I'm sorry if I misattributed something.

**Comment by Little-Mage** [comment]
Oh those pieces... They need to be turned to vectors 1st. Also those aren't made by Couch or Xenmious. I don't know who made those, but I do plan to make those pieces; though, right now I have a lot in my list so it'll be a while till I get to making those pieces svg.
I do have a new trick I wanna try I might be able to turn those pieces to vectors really fast.

**Comment by justremember** [comment]
Someone had a similar request in forums recently https://lishogi.org/forum/lishogi-feedback/proper-2-kanji-piece-set
The new 2-kanji piece set is already uploaded to the discord, correct me if I'm wrong though. Hopefully it can be added to the site sooner or later.

**Comment by justremember** [comment]
https://discord.com/channels/778633701541806081/784456895951929364/827645318975586345

This one just needs to be added.
