### ISSUE TITLE
Orientation is reversed from expected value in Study Editor.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#18]
When creating a new chapter in a Study, setting the orientation to "White" actually sets the orientation to Black/Sente's orientation. Conversely, setting the orientation to "Black" sets the orientation to White/Gote's perspective.

Example: Selecting white...
![image](https://user-images.githubusercontent.com/600562/99308839-676fd400-280d-11eb-9a98-840db559c7a1.png)

Clearly this is from Black's perspective!
![image](https://user-images.githubusercontent.com/600562/99308921-84a4a280-280d-11eb-9899-712a55415ffd.png)

**Comment by WandererXII** [comment]
Thanks for finding this. Will be fixed in the next "update".

**Comment by WandererXII** [comment]
aaaf774fe76677ff578ff9f1fc78e474fda13c2d
