### ISSUE TITLE
Bug: forum search does not work at all

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#184]
Forum search does not return anything no matter what query.
https://lishogi.org/forum/search?text=shogi

Will try to work on this tomorrow. Haven't looked at the code yet, but both forum search & game search might need an elasticsearch engine server (as seen in https://lichess.org/costs)

**Comment by justremember** [comment]
Will put this on hold. I should be prioritizing features/bug fixes that users actually requested...

**Comment by justremember** [comment]
Will put this on hold. I should be prioritizing features/bug fixes that users actually requested...

**Comment by WandererXII** [comment]
Done - https://github.com/WandererXII/lishogi-search and https://github.com/WandererXII/lishogi-search-import.
