### ISSUE TITLE
Shogi studies cannot be saved with more than 399 moves

### ISSUE THREAD

**Issue by WateredBread** [WandererXII/lishogi#185]
I've encountered that in studies, it wouldn't let you save moves that are beyond 399 moves. You can still make them go past 399, but once you've gotten out of the study or refreshed the tab, it would always cap out at 399 moves.

That would prove problematic for games which have gone for way more than 399 moves, more specifically artistic tsumes that are meant to be long, such as with Kouji Hashimoto's "Micro-cosmos", which is 1,525 moves long.

**Comment by Marken-Foo** [comment]
On lichess there is similar behaviour (see https://github.com/ornicar/lila/issues/4759), I believe for reasons of limiting how much storage space a study can use. A workaround is to create multiple chapters, each picking up where the previous one left off. The upper limit of moves should be chosen such that it is a little larger than every reasonable game - one shouldn't need to go past the limit very often, if at all.

**Comment by WandererXII** [comment]
The limit won't be raised for technical reason. For games above the limit, it should now automatically create several chapter - cutting the game into parts (only when creating new study).
