### ISSUE TITLE
Suggestion: do not switch sides when rematching in handicap

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#190]
Neither player wants to switch sides after a game of HC. Yes, they can abort the game before it starts but I think it contributes to the player's game completion rate shown in their profile.

**Comment by llighterr** [comment]
Interesting but for myself the switching sides when rematching is more a feature than a bug.😅
Let me explain.
We often use the `From position` type of the game to solve **tsume shogi** problems in pairs. If one player doesn't solve it, we change turns and try again.
<img width="355" alt="Screenshot 2021-01-22 at 22 41 36" src="https://user-images.githubusercontent.com/4364891/105544500-bc473380-5d03-11eb-850c-2e84f019efaa.png">
Eventually, we can come up with more such training exercises.
But I assume that switching sides in handicap games make less sense.
Probably, the best option here is to keep both options, 
and create a checkbox in the new game menu, smth like: `Switch sides after rematch yes/no`.

**Comment by justremember** [comment]
I already solved this issue by not switching sides if the players chose a handicap game, and switching otherwise. (see commit) If we can avoid it I'd rather not add more knobs and buttons, especially to the game menu which already looks a bit cluttered to me.

**Comment by llighterr** [comment]
Sounds good to me👍🏻
