### ISSUE TITLE
Bug: Promoted piece facing wrong way

### ISSUE THREAD

**Issue by zig1000** [WandererXII/lishogi#193]
On move 43 of the following study, a promoted silver is displayed facing the wrong way: https://lishogi.org/study/3M5fs7qd

**Comment by justremember** [comment]
Appears just fine on my end.
![image](https://user-images.githubusercontent.com/14817065/105947771-aee3cd80-60a4-11eb-94d0-2b2d5ab72dd5.png)

**Comment by paj84** [comment]
It depends on what piece set you're using. I was about to issue this bug as well.
![image](https://user-images.githubusercontent.com/13649971/105978464-de89da00-6092-11eb-84d4-f2f5d9369c17.png)

**Comment by zig1000** [comment]
Yes, I should have mentioned I was using the piece set indicated by paj84

**Comment by justremember** [comment]
Okay, so it's a problem with the image files.

**Comment by WandererXII** [comment]
https://github.com/WandererXII/lishogi/commit/7f10d34de1d830b26b72cd077a14ff9ac9406c75
