### ISSUE TITLE
Suggestion: enable sending message to multiple games in succession

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#195]
Users cant copy paste greetings like "onegaishimasu" or click the premade greeting to multiple games that have started at the same time (like in simuls or correspondence). Would be nice if they could, but I think the anti-spam feature stops them. 
https://discord.com/channels/778633701541806081/787582117927714828/797802629479792661
https://discord.com/channels/778633701541806081/778633953992376350/803814939860795453
https://discord.com/channels/778633701541806081/778633953992376350/804321070253473792

**Comment by WandererXII** [comment]
https://github.com/WandererXII/lishogi/commit/036adf902e856aae56a52c2ac578dff7a0cb5eac

We should probably add more like "yoroshiku", "onegaishimasu", etc. also in hiragana and kanji probably, but at the same time we don't want to make the spam filter too loose, although I don't think people would abuse it.

**Comment by justremember** [comment]
The problem with adding yoroshiku onegaishimasu is people will eventually think those are required like in 81dojo, and they might think *not* saying greetings is rude. Players could be silent for many valid reasons including zen mode & kid mode.

**Comment by WandererXII** [comment]
I believe with that it's solved now.
