### ISSUE TITLE
Generating GIFs from Study is broken.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#20]
In the "Share & Export" section of lishogi study page (below the board editor), attempting to generate a GIF results in being redirected to a page with a generic error.

**Comment by WandererXII** [comment]
Currently lishogi doesn't support gif export, or any exports to be more precise. Right now I will just hide the section. Thank you for taking your time to report these bugs, I really appreciate it.

**Comment by WandererXII** [comment]
6074ebdabc5a32c1653b313dddbe45782fbae21d
