### ISSUE TITLE
Piece in hand that was clicked on opponent's turn gets un-highlighted when turn changes from opponent's to player's

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#208]
https://discord.com/channels/778633701541806081/778633953992376350/806180601136676894

Inconsistent behavior from clicking a piece on the board on opponent's turn.

**Comment by WandererXII** [comment]
Fixed while rewriting ui/round with shogiops https://github.com/WandererXII/lishogi/commit/66062663e62b3af2223c7da7a527a27960cfcadf
