### ISSUE TITLE
Lishogi Twitter link on blog goes to a suspended account.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#21]
Example: 

Check out this blog entry: https://lishogi.org/blog/X61fyRMAACEAC33r/updates---november

Click on the "Twitter" link at the bottom of the post.... and it goes here: https://twitter.com/lishogi

That is a suspended account!

**Comment by WandererXII** [comment]
Oops, seems that twitter managed to suspend my account before I managed to confirm my phone number. I will see what I can do about it.

**Comment by WandererXII** [comment]
Submitted an appeal, will see...

**Comment by ch-suginami** [comment]
Welcome back the lishogi [Twitter](https://twitter.com/lishogi) official account!
Maybe no problem (waiting for Tweeting)!
