### ISSUE TITLE
Bug: Wrong side to play when creating study chapter

### ISSUE THREAD

**Issue by Marken-Foo** [WandererXII/lishogi#214]
When creating a study chapter, the chapter is created with the wrong side to play.

![image](https://user-images.githubusercontent.com/41288521/107185359-48a06880-6a1d-11eb-8cd8-1c24751855dc.png)

e.g. Picture shows "Sente to play" option, but when the chapter is created, the move belongs to the side with missing pieces (coordinates: rank 1-3, e.g. K52 as the first move.)

**Comment by WandererXII** [comment]
Thanks for reporting this. I fixed this on the site, you might need to force reload to see the changes.

**Comment by takodori** [comment]
I created a new chapter in one of my Studies today. I think this bug has been fixed. I guess only the issue originator has a preveledge to close it so I just reported there is no longer the same problem as long as I created a new chapter.

> WandererToday at 3:38 AM
> Applied a fix for the interactive studies, let me know if you notice anything still not working.
