### ISSUE TITLE
Bug: (notation) "金不成" in engine analysis lines

### ISSUE THREAD

**Issue by Marken-Foo** [WandererXII/lishogi#216]
Minor bug: "金不成" is displayed in engine analysis lines even though golds don't promote.

The same occurs in all the other notation systems (e.g. G-28=, G-2h=, even in Kitao-Kawasaki) so it's likely in the disambiguation/"translation" code for the engine output?

![image](https://user-images.githubusercontent.com/41288521/107500767-8645f280-6bd1-11eb-9f2a-86afc6da8b89.png)

**Comment by WandererXII** [comment]
Thanks, small bug in shogiops while parsing moves, fixed it now. Force refresh will probably be required to see the fix.
