### ISSUE TITLE
When viewing your profile, the suggestions list has several references to chess instead of shogi.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#22]
When viewing your profile, there is a big list of suggestions in a bulleted list. There are several references to "chess" where it should instead say "Shogi"!

"Learn **chess** rules"
"Improve with **chess** tactics puzzles - coming soon"

![image](https://user-images.githubusercontent.com/600562/99327737-710a3380-282f-11eb-9969-04c976860a16.png)

**Comment by WandererXII** [comment]
Fixed!
