### ISSUE TITLE
"CLEAR BOARD" button is disabled following to "Add a new chapter" in Study

### ISSUE THREAD

**Issue by takodori** [WandererXII/lishogi#222]
When I tried to add a new chapter in my Study by clicking the "Add a new chapter" button, an editor 
board appeared but I could not clear the board by clicking the "CLEAR BOARD" button.  

![image](https://user-images.githubusercontent.com/78942017/107895270-20ad8980-6f76-11eb-877e-ea98c69686ce.png)

![image](https://user-images.githubusercontent.com/78942017/107895148-a41aab00-6f75-11eb-957e-853eeaa17532.png)

**Comment by takodori** [comment]
The function used to work fine until a few days ago. But suddenly it has not worked for several days. I do not know why.

**Comment by WandererXII** [comment]
Hey, thanks a lot for reporting this. I found the cause, I will upload the fix together with the study database fix as soon as I have it ready.

**Comment by takodori** [comment]
Thanks. WandererXII. Good to know it will be fixed.

**Comment by takodori** [comment]
Thanks a lot. "CLEAR BOARD" button now works fine. Case closed.
