### ISSUE TITLE
Suggestion: Board editor pocket - be able to decrease count

### ISSUE THREAD

**Issue by CouchTomato87** [WandererXII/lishogi#225]
In the board editor, you can only increase the number of pieces in the pocket. There's no easy way of decreasing them outside of dragging them on to the board and deleting them. On Pychess, you can shift + click to decrease. Perhaps a similar functionality can be added?

**Comment by WandererXII** [comment]
Cleaning up - I will close this, shift+click was added as suggested, also right click deletes the pieces and you can also drag them anywhere, not just the board, to remove them. Thanks for suggesting this.
