### ISSUE TITLE
Suggestion: Tournament signup pages should have Shogi Proverbs instead of famous Chess Quotes.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#23]
When signing up for tournaments, a random Chess Quote is displayed under the rules. These quotes should either be replaced with Shogi Proverbs or quotes from famous Shogi Players. Some of the Chess quotes also apply to Shogi but many of them do not make sense.

Example: https://lishogi.org/tournament/t3PvcVlO

![image](https://user-images.githubusercontent.com/600562/99327954-ef66d580-282f-11eb-869f-bd2d8518cd86.png)

**Comment by ddugovic** [comment]
I'd be glad to patch this if I had a suitable list of proverbs to draw from.

**Comment by kleffa** [comment]
http://www.shogi.net/shogivocab/vocabhtml.html#10
This can help you? I had a spreadsheet with some others trying to translating to Spanish, maybe we can join force in the list

**Comment by kleffa** [comment]
I poposed a change, but not sure if is in god mode, since proverbs have no authors

**Comment by WandererXII** [comment]
Great! Thanks a lot for the pull request, already pushed to server.
