### ISSUE TITLE
Request: an option to show tooltips

### ISSUE THREAD

**Issue by Lokathor** [WandererXII/lishogi#234]
As a beginner, I would like to have the game show official pieces. However, I'm still trying to remember what pieces have what names while I go along. I think it would be very helpful if there was an option for the mouse to have a tooltip with the name of the piece (and possibly other info) when you hover over a piece on the board (both allied and enemy).

**Comment by WandererXII** [comment]
While a nice idea, this couldn't be default behavior and expecting beginners to find in preferences seems unreasonable. Some piecesets have helping _pointers_, that tells you how a piece moves:
![image](https://user-images.githubusercontent.com/43043181/185722435-0e1f1ded-367e-4c54-b67b-7228b1734f02.png)
That doesn't help with names tho, but I don't think there are that many piece types, that it would justify doing this.
