### ISSUE TITLE
Request: export study PGN

### ISSUE THREAD

**Issue by AmaiKinono** [WandererXII/lishogi#237]
In lichess, there's a share button, where you can share the URL or download chapter/study PGN.

It'll be great if lishogi can have this too, so people can save and browse the studies offline.

**Comment by justremember** [comment]
About this, and kif export/import @WandererXII sorry but I would rather not focus on this anymore... I feel this needs quite a bit of preparation & "background knowledge" of the system to code it well. The kif export functionality is already spaghetti code imo, even though I genuinely tried to keep it clean (but at the very least, most of the kifu-creating code is compartmentalized in one file)

**Comment by ddugovic** [comment]
I just touched the UI code, however I'm unfamiliar with how to actually export the chapter kifu.
