### ISSUE TITLE
Bug: forum post embed's piece design is always default one no matter the setting

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#238]
![Screen_Shot_2021-03-04_at_2 15 09_PM](https://user-images.githubusercontent.com/14817065/110194759-23184a80-7e75-11eb-9bc2-28e2c86f86a9.png)

https://discord.com/channels/778633701541806081/778633953992376350/817195864765759518

**Comment by TheYoBots** [comment]
https://github.com/WandererXII/lishogi/pull/393 Fixed this right?
