### ISSUE TITLE
Sugestion for shogi pieces

### ISSUE THREAD

**Issue by kleffa** [WandererXII/lishogi#24]
https://github.com/Little-Magician/ShogiGUI-piece-sets
There is a collection for pieces to shogiGui, I designed the Valdivia ones.
I will be glad if them can be set as option to play with them, there is a option for begginers but very appreciated
-Gabo

**Comment by CouchTomato87** [comment]
I'm the creator of one of those sets, although its modified a little from my model. You can also use the same ones used at www.pychess.org from here: https://github.com/gbtami/pychess-variants/tree/master/static/images/pieces/shogi

**Comment by WandererXII** [comment]
Those look great. Thanks guys. I will put them in as soon as I can.

**Comment by kleffa** [comment]
I can try make the sprites in format, maybe same for board, they have some specifications or I can try look into files to try it?

**Comment by WandererXII** [comment]
No real specifications, I think the viewbox should be square for pieces. The naming scheme should also be standard.
The only problem might be that the board on lishogi is also square, while most shogi boards elsewhere aren't.
If you want to look into files you can find the pieces here [https://github.com/WandererXII/lishogi/tree/master/public/piece](https://github.com/WandererXII/lishogi/tree/master/public/piece) and boards here [https://github.com/WandererXII/lishogi/tree/master/public/images/board](https://github.com/WandererXII/lishogi/tree/master/public/images/board). I think pngs or jpegs are better for boards, because when I tried svg, the lines didn't display correctly on some devices.

**Comment by CouchTomato87** [comment]
Does it have to do with the size of svgs? Using pngs and jpegs for something resizable seems really suboptimal.

**Comment by WandererXII** [comment]
It's probably because I can't really work with svgs. But the issue was that the vertical and horizontal lines separating individual squares were too thin on smaller displays, that they just weren't displayed at all.

**Comment by CouchTomato87** [comment]
Where are the pieces located? I can try to convert my pieces into png's to match them.

**Comment by WandererXII** [comment]
I was talking about boards with the jpegs and pngs. Pieces work fine as svgs and I didn't even try anything different, so I would say that pieces have to svgs, you can find current pieces here: [https://github.com/WandererXII/lishogi/tree/master/public/piece](https://github.com/WandererXII/lishogi/tree/master/public/piece)

**Comment by CouchTomato87** [comment]
Doh! Should've seen that earlier. I just realized this -- but is there any way you can separate the black king from the white king? They have unique symbols in all sets, and they help for identifying sides.

**Comment by WandererXII** [comment]
Just started differentiating them. OU for gote - second, GY for sente - first.

**Comment by CouchTomato87** [comment]
[Shogi Pieces.zip](https://github.com/WandererXII/lishogi/files/5571005/Shogi.Pieces.zip)

Alright, here's everything I got. The folder names should be self explanatory. The "Intl Colored/Monochrome 2D" are newly created sets I made to match a lot of the sets you already have (the stroke style)

**Comment by kleffa** [comment]
I made a pull request to include more pieces , I will add the couch ones to minimize work

**Comment by CouchTomato87** [comment]
Much appreciated!

I can start working on boards next. I'm not a fan of the square tiles, but I guess we're stuck with that for now.

**Comment by CouchTomato87** [comment]
[Boards.zip](https://github.com/WandererXII/lishogi/files/5576925/Boards.zip)

Ended up finishing the basic boards sooner than expected. I think these will all need thumbnails though. Is there something that automatically generates these thumbnails or do we have to do manually make them ourselves?

**Comment by kleffa** [comment]
I think, tomorrow I make the thumbnails then upload, this was surprisingly quick I just started when I see your port in discord XD

**Comment by WandererXII** [comment]
Thanks a lot, looks great! For thumbnails this can be used [https://github.com/WandererXII/lishogi/blob/master/bin/gen/board-thumbnail](https://github.com/WandererXII/lishogi/blob/master/bin/gen/board-thumbnail) on linux.

**Comment by CouchTomato87** [comment]
Oh cool! And yeah someone else will have to do that then haha. I don't have linux.

**Comment by CouchTomato87** [comment]
[Boards 2.zip](https://github.com/WandererXII/lishogi/files/5578317/Boards.2.zip)

I couldn't help myself and did a few more boards.

**Comment by kleffa** [comment]
ok, Im doing the thumbnails

**Comment by kleffa** [comment]
I upload the files! I see the thumbnail of dobutsu were in the same folder, so I set all thumbnails there

**Comment by WandererXII** [comment]
Nice, looking great! I will update server tomorrow with new boards and pieces.

**Comment by CouchTomato87** [comment]
[Intl 2D v2.zip](https://github.com/WandererXII/lishogi/files/5580599/Intl.2D.v2.zip)

Here are the updated 2D pieces.
And as per our discussion on Discord, the wooden 3D 1KE (down-facing knight) piece was missing features... and the intl shadowed pieces that were facing down were misaligned.

**Comment by CouchTomato87** [comment]
Oh, I should also add for the sake of server space... Those two sets have pieces that are identical. Those are: FU, KE, KY, NK, NY, and TO (obviously for both 0 and 1). I know that Pychess redirects the images to the base folder in the case of identical pieces, so you can probably do the same to save space.

**Comment by CouchTomato87** [comment]
Intl Wooden set: 1NK is also missing the eyes.

**Comment by CouchTomato87** [comment]
Thanks for the update! For some reason for the International 2D pieces, the downwards knight and promoted knight are both flipped horizontally. I thought I had messed this up in my files, but they're facing the right way there...

**Comment by WandererXII** [comment]
Thanks! Fixed, in your files 1KE was the same as 1NK, so I just flipped 0KE vertically, not realizing I also need to flip it horizontally.
![image](https://user-images.githubusercontent.com/43043181/100112718-d97c9480-2e6f-11eb-911f-285482935eb2.png)

**Comment by kleffa** [comment]
I get a little lost with all the movement,in this issue
I reedited the valdivias, (in two formats) still in square, but I think most of this should be in rectagles ifnew board get implemented
[valdivia pieces.zip](https://github.com/WandererXII/lishogi/files/5591380/valdivia.pieces.zip)

**Comment by kleffa** [comment]
also this for the orangain, this have the 0GY corrected
[orangain.zip](https://github.com/WandererXII/lishogi/files/5591729/orangain.zip)

**Comment by kleffa** [comment]
I will leave this for future, https://github.com/kleffa/ValdiviaShogiPieces is a repository with Valdivia Pieces for Pyshogi

**Comment by WandererXII** [comment]
> I get a little lost with all the movement,in this issue
> I reedited the valdivias, (in two formats) still in square, but I think most of this should be in rectagles ifnew board get implemented
> [valdivia pieces.zip](https://github.com/WandererXII/lishogi/files/5591380/valdivia.pieces.zip)

Yep, this issue is getting a bit confusing. I will add the pieces tomorrow. Looking nice, thanks a lot.

**Comment by WandererXII** [comment]
Thanks again guys for submitting pieces and board design. Closing this issue now.

**Comment by kleffa** [comment]
[LOGY_GAMES_by_Mitsuo_Yamamoto.zip](https://github.com/WandererXII/lishogi/files/5717602/LOGY_GAMES_by_Mitsuo_Yamamoto.zip)
Can I ask for include this ones in lishogi?
I Ask Mitsuo and he is very interested in share them

**Comment by WandererXII** [comment]
Sure, I am happy to include them!

**Comment by nexxogen** [comment]
Hello. I have tried pushing these through git but for some reason SoruceTree tells me I don't have permissions to do that, so here it is. I hope these will find a place on lishogi. 🙂 
[Ryoko_1Kanji.zip](https://github.com/WandererXII/lishogi/files/5744836/Ryoko_1Kanji.zip)

**Comment by nexxogen** [comment]
In the meantime, I managed to create a pull request so whatever is easier for you. :)
