### ISSUE TITLE
User hover popup hides in edge of screen sometimes

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#241]
https://cdn.discordapp.com/attachments/794423650681225246/817797600546783302/Screen_Shot_2021-03-06_at_9.31.55_AM.png

**Comment by ddugovic** [comment]
Which browser and browser version is this?

**Comment by justremember** [comment]
I was able to replicate it in windows 10 chrome latest version a month ago, but couldn't recently. Will try in firefox.

**Comment by justremember** [comment]
Can't replicate this anymore. Will be closing it for now.
