### ISSUE TITLE
Follow cursor with piece after left-clicking a piece in pocket

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#243]
I find that after clicking a piece on the tray and thinking for 1 minute I forget about having selected the piece and it can lead to accidental drops. The selected piece could follow the cursor like in 81dojo, to help w/ this problem. (for some reason the piece isn't centered in the screenshot but it is in the app)
![image](https://user-images.githubusercontent.com/14817065/110439236-2f5d0b80-80f2-11eb-9a65-1af4419c5c30.png)
The piece itself can also be partly transparent.

**Comment by justremember** [comment]
An alternative is, after left clicking a piece in the pocket, highlight all possible dropping squares. 
![image](https://user-images.githubusercontent.com/14817065/112713802-edb1ca80-8f11-11eb-9318-3c6693c20f92.png)

**Comment by WandererXII** [comment]
Added possible drop destination here: https://github.com/WandererXII/lishogi/commit/bb348076e52ac80f99c050d141f03c0900599a4c

**Comment by justremember** [comment]
Just noticed this addition, looks very cool, thanks 👍
