### ISSUE TITLE
Bug: multiple arrows & drop circles show after game has been analyzed

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#244]
https://lishogi.org/FQ4r3Iry
![image](https://user-images.githubusercontent.com/14817065/111059355-ed580f00-84cf-11eb-965c-180af83f664a.png)
there should be only one showing here, which is the engine's recommended move after this position (P*83). But it also shows the previous position's recommended move (P95). This bug only appears in some positions.

**Comment by WandererXII** [comment]
If I understand correctly, this is not a bug, but it's surely confusing. It's just showing opponents response to the current best move. I changed the colors to make it more readable.
![image](https://user-images.githubusercontent.com/43043181/186771509-973970c1-5231-4b87-ae66-32b7ef84850b.png)
