### ISSUE TITLE
Short delay after clicking promotion choice

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#246]
AFAIK this short lag happens consistently. Maybe unnoticeable in higher end devices but not the case with my laptop & phone.

**Comment by justremember** [comment]
Just wrote an issue in lila: https://github.com/ornicar/lila/issues/9007

**Comment by WandererXII** [comment]
Instead of autoqueen we could auto promote pawns, rooks and bishops. That would help a bit.

**Comment by justremember** [comment]
> My guess is that the perceived lag originates from the client waiting for the server to validate the move
@ddugovic  Nope. In my local server, for any non-promotion move the lag is almost non-existent. But the promotion lag still exists. My guess is that the delay was intentionally coded in the javascript many years ago to work around some other problem.

**Comment by ddugovic** [comment]
My guess is that the lila issue is somehow DNS-related, along with another issue frequently reported in lila (pieces not rendering) which I assume is DNS-related; it seems that using Lichess, many more DNS requests are made than using other websites (although I forget how I observed this).

**Comment by WandererXII** [comment]
The promotion frontend code was rewritten, so not sure if it still applies...
