### ISSUE TITLE
Two different ways of naming a coordinate and numbering on the board when someone makes a comment on a move

### ISSUE THREAD

**Issue by WateredBread** [WandererXII/lishogi#247]
![Bug _p](https://user-images.githubusercontent.com/74818508/111900100-7391c980-8a6b-11eb-9ed3-35138544ae56.jpg)

**Comment by WandererXII** [comment]
Fixed here https://github.com/WandererXII/lishogi/blob/master/ui/analyse/src/util.ts#L88, thanks for reporting this!
