### ISSUE TITLE
Gote promotion isn't upside down

### ISSUE THREAD

**Issue by Little-Mage** [WandererXII/lishogi#248]
Is this intended?
![image](https://user-images.githubusercontent.com/55811361/111914918-a15e1a80-8a39-11eb-8465-3f211fc32160.png)

**Comment by justremember** [comment]
I suggest making the piece design upside down as well. Probably best not to switch the button positions though.

**Comment by WandererXII** [comment]
Done here https://github.com/WandererXII/lishogi/commit/096d2fa2504d5283efb4cc3e0537ff9a9e36f667. Thanks!
