### ISSUE TITLE
Transparent board design, for users with background set to "transparent"

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#252]
From https://lishogi.org/forum/lishogi-feedback/want-the-clear-design-of-shogi-board#1
I also think it would be nice if we had transparent shogi boards. Maybe 2 different designs, with black lines & white lines.

**Comment by WandererXII** [comment]
579eddc37f706bfbe64bfc0e9ff8c955edbc915f b4ca5d36a205451ae15c1bb03b79518f8da5a3b7
