### ISSUE TITLE
Bug: Studies not incrementing move count in the move list.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#26]
When creating a new study, if you start from the initial position, the move count stays at 1 no matter how many moves you make. Attached screenshot shows an example. Every move is showing as the first move. It does the same thing for sub-variations.

Similarly, when the PGN export is made, it shows each move as being the first move.

In the future, you will probably want to follow the universal Shogi convention and change the move counts to count for each half-move/ply instead of each full move, but that is a minor implementation detail.

Example of bugged move count in moves list:
![image](https://user-images.githubusercontent.com/600562/99337869-ff82b300-2837-11eb-80ae-e7a57cfe5585.png)

**Comment by WandererXII** [comment]
The same thing happens in analysis, trying to find a reason for this

**Comment by WandererXII** [comment]
Found the problem, it's in lila-ws [https://github.com/WandererXII/lila-ws/commit/42ef7d91b60caff50cf2e7df97991bb8eaa0d718](https://github.com/WandererXII/lila-ws/commit/42ef7d91b60caff50cf2e7df97991bb8eaa0d718). I will update it on the server probably today.
