### ISSUE TITLE
Can't drop the opponent's piece after finishing a puzzle

### ISSUE THREAD

**Issue by AmaiKinono** [WandererXII/lishogi#263]
Sometimes, after finishing a puzzle, the board becomes free to play, and when it's the opponent's turn, the pieces can't be dropped.

This happens to [this puzzle](https://lishogi.org/training/vPQJj). I suspect it only happens in Tsume problems.

**Comment by KarolS** [comment]
![obraz](https://user-images.githubusercontent.com/1790750/113939236-023c6f80-97fc-11eb-93b5-a7b4be2b4e17.png)
I've managed to do a drop just fine.

**Comment by AmaiKinono** [comment]
@KarolS Thanks. You are right. I retried and it works. The dropping when I first tested it must be some illegal move.
