### ISSUE TITLE
Color - Refactor

### ISSUE THREAD

**Issue by WandererXII** [WandererXII/lishogi#267]
Doing what should've been done a long time ago.

White -> Sente(black)
Black -> Gote(white)

This will fix a lot of bugs - incorrect analysis board orientation when going from editor or inputting sfen, incorrect board orientation in 'from position' game creation menu, incorrect urls for sides, incorrect tags in some exports and mainly it will stop the confusion.

This issues is for tracking the commits.

- [x] Update the backend
- [x] Undo changes that swap colors in the frontend
- [x] Change all sfen values in the DB
- [x] Update shoginet
- [x] Update shogiops
- [x] Update lila-ws
- [x] Inform bots about this change
- [x] Update assets

**Comment by WandererXII** [comment]
https://github.com/WandererXII/lila-ws/commit/37a14a126aaa9fc809e2502d4066ea98943e227a

**Comment by WandererXII** [comment]
https://www.npmjs.com/package/shogiops/v/0.2.1

**Comment by ddugovic** [comment]
Eventually account for handicap games:

> White (handicap-receiver) is called uwate while black is called shitate (handicap-giver).
https://www.pychess.org/variant/shogi

**Comment by WandererXII** [comment]
Yep it was a real chaos, color should be good now, I will continue refactoring to get rid of unused variants, castle, enpassant and other chess stuff.

Something like that will probably be done in the front end. We would also need to add all those new translations line for uwate/shitate.
