### ISSUE TITLE
Studies tutorial has broken link to Studies documentation.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#27]
When first using the study, a series of informational popups show. One of them has links embedded in the tutorial popup. There is a broken link to a blog post that is supposed to give information about lishogi studies: https://lishogi.org/blog/V0KrLSkAAMo3hsi4/study-chess-the-lishogi-way

**Comment by timezombi** [comment]
The same broken link can be found in the "What are studies?" link in the navbar when viewing the overall list of studies.

**Comment by WandererXII** [comment]
aec82c1326d0b9e79931cdf9f2122ddc59e51a12
