### ISSUE TITLE
Replace all instances of "FEN" with "SFEN" throughout the website.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#28]
The shogi version of Forsyth–Edwards Notation (FEN) is actually called "SFEN". It has a consistent spec that you have mostly implemented, but I've found some errors (made another bug for that).

Wherever the website displays "FEN", you should instead consistently display SFEN instead.

If you want to test if your SFEN is working, you can try to use the sfenreader webapp:
https://sfenreader.appspot.com/en/create_board.html

**Comment by kleffa** [comment]
I make a pull request to change it in editor page, there is another site where FEN is mentioned?

**Comment by timezombi** [comment]
If this hasn't already been fixed in all places, then I'll set up the repo this Thanksgiving weekend and see if I can tackle this as a simple first commit.

**Comment by WandererXII** [comment]
Most places should be alright now, if you notice it being wrong somewhere and issue hasn't been made for it, please submit one. Thanks
