### ISSUE TITLE
Study enlarge New Chapter board

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#283]
There are 9 rows and 9 columns, plus the "box" of 2 rows and 2 columns above & below the board... it's easy to mouseslip.

![image](https://user-images.githubusercontent.com/1834123/116015412-bca2e380-a5fe-11eb-99a0-da3a5fe53ae7.png)

**Comment by WandererXII** [comment]
280px -> 320px, hopefully that's enough, I wanted to keep the bottom spare pieces and pocket at least mostly visible on 720p screens.

**Comment by justremember** [comment]
Fixed? @WandererXII

**Comment by WandererXII** [comment]
> Fixed? @WandererXII

I think this is enough, feel free to reopen this tho.
