### ISSUE TITLE
SFEN generated in Shogi TV is malformed.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#29]
When viewing a game in the TV mode, I noticed that the generated SFEN is producing characters that shouldn't exist in SFEN notation (e.g. "A" for a promoted piece).

For example, here is a game where Sente has a narigin (promoted silver) placed on 2c. However, the SFEN string does not have it in the generated string. Instead, it shows "A" where it should instead be "+S" in proper SFEN fashion.

There are probably other places where the SFEN notation is not generated properly. There are several good implementations for parsing SFEN that you can find on github if you are unfamiliar with the spec.

https://lishogi.org/@/ShogiExplained/tv#85 (move 43).

![image](https://user-images.githubusercontent.com/600562/99342052-e4b43c80-283f-11eb-9939-dbc2ace2973c.png)

**Comment by kleffa** [comment]
Not just that, look at move list, there is more "A"s instead is +S, I guess

**Comment by WandererXII** [comment]
That's backend leaking to the frontend, trying to avoid rewriting a lot of stuff, I had to represent (at least for now) all pieces with a single letter, it's 'A' for promoted silver. Will try to fix this week. Thanks for noticing, I also totally forgot that there's an inline view, will be fixed.

**Comment by kleffa** [comment]
this still happening
![image](https://user-images.githubusercontent.com/26838533/100487522-d25fbb80-30e7-11eb-8550-933444cbcb4e.png)
this SFEN have two problems
1 dragon in sfen notation is +r, as horse is +b (the plus for promotions)

**Comment by kleffa** [comment]
and for pieces in hand, yu can factoze them, like pppppp is 6p

**Comment by WandererXII** [comment]
This should be solved, if not feel free to reopen this. Thanks guys
