### ISSUE TITLE
Remove discrepancy between # of games in play shown in homepage vs actual # in lishogi.org/games

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#291]
Says `22 games in play` in homepage but when someone clicks it and goes to [/games](https://lishogi.org/games) they only see 1 game. This feels like misleading & false advertising, pretty much...

No clue how the code works here, but the possible solutions are:

1. showing ALL games in /games (see 2nd pic, the classical casual match in /tv wasn't in /games) with a hierarchy, from first to last:
  a. rated games
  b. casual user vs user
  c. user vs anon
  d. user vs AI
  e. anon vs anon
(maybe same hierarchy for tv as well?)
2. changing the logic for the homepage game counter
3. both.
 
![rtgrsdaf](https://user-images.githubusercontent.com/14817065/116840171-773a7380-ac07-11eb-9236-a4d98baadf05.png)

![aserggwed](https://user-images.githubusercontent.com/14817065/116840159-6e49a200-ac07-11eb-80ba-72ca5617d9fb.png)

**Comment by WandererXII** [comment]
Mostly done - https://github.com/WandererXII/lishogi/commit/e93d1e8a33817eb4d9aabe7667166e4a10282cf2
There will always be some discrepancy, because of correspondence games, that are not features in /games and the way the homepage counter logic works.
