### ISSUE TITLE
"同" in Japanese notation

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#293]
同 is used when the current move's destination square is the same as the previous move's, for example during a recapture. See [this](https://shogidb2.com/games/326b47ab026d49ec93c2b96813694d9fa628baa4#ln1gkg1nl%2F2s1r4%2F1pp2p1pp%2Fp2p1spb1%2F4p4%2FP1P2SP2%2F1PSPPP2P%2F1B1K3R1%2FLN1G1G1NL%20b%201p%2025) as an example. Also see https://en.wikipedia.org/wiki/Shogi_notation#Destination_coordinates_2
Note there may be a full-width space after the 同 for formatting purposes, like so:
４三歩
同　飛
５六金
However it maybe awkward to include that space when the moves are listed from left to right: 117.☖４三歩 118.☗同　飛 119.☖５六金
So dropping the space then will look better: 117.☖４三歩 118.☗同飛 119.☖５六金
Assuming it's not worth the extra effort of conditionally adding the space only when the moves are listed vertically, I would personally prefer having the space all the time.

**Comment by ddugovic** [comment]
Oh, is this not fixed?
https://github.com/WandererXII/lishogi/blob/43ca3e1edbd633a54aaf8c0b63c5c3dda2eb1d35/modules/shogi/src/main/scala/format/pgn/KifuUtils.scala#L86

**Comment by justremember** [comment]
That's for kifu generation. The code handling japanese notation would most likely be in /ui.

**Comment by WandererXII** [comment]
Done!
