### ISSUE TITLE
Streamer link on homepage redirect to twitch.tv or youtube

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#294]
In lichess.org, streamer links on homepage open a new tab & redirect to twitch.tv. This is a recent change. Nojoke explained why in the [perpetual chess podcast](https://open.spotify.com/episode/0bb8qTJmfL5TmPJtfLwlsd) that viewing from a twitch embed no longer counts for views. So I am sure it would help our lishogi streamers a lot if homepage links redirected to twitch, to give streamers a much more accurate view count.
![image](https://user-images.githubusercontent.com/14817065/117230765-544ed000-ae50-11eb-9d8c-32491b8daf19.png)

**Comment by justremember** [comment]
Relevant commit: https://github.com/ornicar/lila/commit/c022ad8cfd388607010fc0550a70b10f5b7b5a9e

**Comment by WandererXII** [comment]
Should work with https://github.com/WandererXII/lishogi/commit/b97f909347be078f329d29b194418f4caff6e057
