### ISSUE TITLE
Crowdin PR is safe to merge despite lint errors

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#296]
https://github.com/WandererXII/lishogi/pull/285
The Crowdin PR wasn't merged right after adding the source string "cheatDetected", so the PR itself contains translations of "Cheat Detected" yet no source string. Which means the PR is otherwise safe to merge right now.

**Comment by WandererXII** [comment]
I will remember to merge crowdin PR right after adding a new string next time.
