### ISSUE TITLE
Blurry pieces

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#297]
![image](https://user-images.githubusercontent.com/14817065/117405671-8d656e00-af3e-11eb-883e-9f95092fcfa8.png)
Fortunately most of the time, only a few pieces are affected. And sometimes no pieces are blurred.

This is most likely the single cause: https://github.com/ornicar/lila/issues/8114
Hoping they find a good fix for this eventually

**Comment by WandererXII** [comment]
Starting chrome 91 (current chrome beta), the rounding hack stops completely working.
![image](https://user-images.githubusercontent.com/43043181/118284057-51974f00-b4d0-11eb-9b4c-2b05ee21924d.png)

**Comment by WandererXII** [comment]
Applied the 'trick' you suggested (https://ctidd.com/2015/svg-background-scaling) and it seems to work very nicely with svgs.

One problem is that `will-change: transform` causes some pieces to have jagged edges like this: 
![image](https://user-images.githubusercontent.com/43043181/119159474-8ae33800-ba57-11eb-8604-c4f4e73cabb5.png)
Removing that solves it:
![image](https://user-images.githubusercontent.com/43043181/119159626-b82fe600-ba57-11eb-9b36-77e172ee6da7.png)
But without it png piecesets are now blurry when downscaled.
![image](https://user-images.githubusercontent.com/43043181/119159790-e44b6700-ba57-11eb-8399-94e46f3be385.png)

This is only a problem on chromium, works fine on firefox.

**Comment by justremember** [comment]
I think that particular piece set is naturally jagged. And I remember one of the possible fixes has a performance tradeoff, is that the case for `will-change: transform`?

**Comment by justremember** [comment]
At a certain size, portella images look jagged.
![image](https://user-images.githubusercontent.com/14817065/119295964-aaae7200-bc8a-11eb-93d7-1decce032524.png)

Looks fine in both smaller & larger sizes though.
![image](https://user-images.githubusercontent.com/14817065/119295919-90749400-bc8a-11eb-9359-6745d54cdb5a.png)
![image](https://user-images.githubusercontent.com/14817065/119296007-bb5ee800-bc8a-11eb-9618-3c3ce0a3792d.png)

**Comment by WandererXII** [comment]
> I think that particular piece set is naturally jagged. And I remember one of the possible fixes has a performance tradeoff, is that the case for `will-change: transform`?

Well the svg pieces are way too jagged with that, and from some measurements I did, I didn't see any meaningful differences.


> At a certain size, portella images look jagged.

I added `will-change: transform` on all png piece sets to fix the blur on chrome, so that's probably why they are jagged on your end, try unchecking that in dev tools, I can't replicate this neither on chrome or firefox tho.

**Comment by justremember** [comment]
Was trying to replicate this today, no success. Maybe it's fine now.

**Comment by justremember** [comment]
The lichess issue was closed after this commit https://github.com/ornicar/lila/pull/9197

**Comment by WandererXII** [comment]
I think we can close this too. Feel free to reopen, if you disagree.
