### ISSUE TITLE
Enable GitHub Discussions?

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#307]
I understand currently we have 56 open issues.  I would like some way of entering into GitHub fun feature ideas similar to how https://github.com/ornicar/lila has a "Discussions" section.

For example, it could be a fun feature to show Shogi Wars-style popup images without resorting to OBS plugins like https://github.com/RossLitzenberger/KappaGen , although such a feature seems unlikely to be developed anytime soon.

**Comment by WandererXII** [comment]
Discussions enabled.
