### ISSUE TITLE
Client-side Yaneuraou NNUE (WebAssembly)

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#309]
A few months back Hiroshi Ogawa (https://github.com/hi-ogawa/Stockfish) cracked the code on making Stockfish NNUE work fast in the browser with WASM. Lichess included Stockfish NNUE browser analysis. They even made a blog post for this. https://lichess.org/blog/YDOKRxQAACgAREB3/stockfish-13-nnue-on-lichess

So there is hope for a client-side Yaneuraou in lishogi. It would be a (selfish) request on behalf on lishogi, but hopefully we can convince the Yaneuraou developers to look into this. I am also hoping the WASM/emscripten code hiogawa wrote will be helpful to Yaneuraou. Or if anyone reading this is knowledgeable in this field, a helping hand would be appreciated.

Later I will try to write an issue in the Yaneuraou github repo.

**Comment by justremember** [comment]
Yaneuraou said they have plans, but only at year's end, maybe.

**Comment by killerducky** [comment]
I found this code and demo:

code: https://github.com/mizar/YaneuraOu.wasm
demo: https://lab.mzr.jp/yowasm/

**Comment by WandererXII** [comment]
Done!
