### ISSUE TITLE
Credits to shogi piece makers in COPYING.md

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#310]
Credits for shogi pieces are missing in https://github.com/WandererXII/lishogi/blob/master/COPYING.md. I do not know the licenses for each piece set, so @CouchTomato87 @Little-Mage @nexxogen and others who made lishogi pieces, please help us by stating the licenses of all your pieces, whether it's public domain or CC BY SA or any other.

Also if whoever reading this is in lishogi discord please copypaste the issue's link to #contribute-without-coding so others can see, thanks.

**Comment by nexxogen** [comment]
Honestly, I'm nor very knowledgeable about licenses, so I will just say that my pieces are free to use by anyone in any shape or form. You will know the name of the appropriate license, I'm sure.

**Comment by justremember** [comment]
So public domain, then. The only restriction would be that no one can slap their own copyright on the creative work.

**Comment by Little-Mage** [comment]
Mine are a remake of Couch and orangain so I'm not sure.

**Comment by justremember** [comment]
> Mine are a remake of Couch and orangain
Which pieces exactly?

**Comment by CouchTomato87** [comment]
https://github.com/CouchTomato87/InternationalizedPieces/blob/master/LICENCE.txt

**Comment by justremember** [comment]
@CouchTomato87 all the international pieces right? Which else?

**Comment by Little-Mage** [comment]
> > Mine are a remake of Couch and orangain
> 
> Which pieces exactly?

1Kanji_3D & Intl_Colored_3D are remakes of Couch.
2Kanji_3D is remake of orangain https://github.com/orangain/shogi-piece-images

**Comment by justremember** [comment]
Thanks little.

**Comment by CouchTomato87** [comment]
Yes, except Ka's (the last one that uses like 80% of my designs but changes things up). Also the tiger stripe pieces.
