### ISSUE TITLE
Suggestion: never show milliseconds for initial time when byoyomi is >=10

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#311]
Let's say it is move 51, sente's turn, the time control is 10|30 and there is 00:03.00 seconds left on the initial timer (not yet byoyomi). Seeing milliseconds count down, even in peripheral vision, might pressure someone to make a move, and I've observed this behavior in players, including myself. From an objective point of view however, there is absolutely no rush to move in those last 3 seconds, and they should just willingly enter byoyomi, and enjoy the extra 30 seconds of time in that move. On the other hand, if they make a move at move 51 with 2 seconds left on the initial timer, they will have 30(byo) + 2(init) = 32 seconds available on the next turn (move 53) as opposed to 30. Barely any time saved. So removing the milliseconds would hopefully lead them to making better choices under pressure.

**Comment by ddugovic** [comment]
That makes sense even if byoyomi > 0.  Likely this line would need to be edited:
https://github.com/WandererXII/lishogi/blob/43ca3e1edbd633a54aaf8c0b63c5c3dda2eb1d35/ui/round/src/clock/clockCtrl.ts#L100
