### ISSUE TITLE
pawn drop mate legal in positions with only one king

### ISSUE THREAD

**Issue by peanatsu** [WandererXII/lishogi#320]
This puzzle was found by discord user buschbeer69:
https://lishogi.org/training/HZTum

simpler versions from the analysis board:
https://lishogi.org/analysis/8k/9/7+R1/9/9/9/9/9/9_b_P_1 (1 king, pawn-drop mate legal)
https://lishogi.org/analysis/8k/9/7+R1/9/9/9/9/9/K8_b_P_1 (2 kings, pawn-drop mate illegal)

**Comment by WandererXII** [comment]
Fixed. Thanks for reporting this!
