### ISSUE TITLE
Players with two letter names can’t be made team leaders

### ISSUE THREAD

**Issue by TheYoBots** [WandererXII/lishogi#322]
> I've been able to make a team however, when adding more team leaders, my role as a team leader gets deleted and I am unable to do anything about it.

> If someone could explain why this is happening and if there is a solution to this I would be grateful.

I had even tested with a user in [this team](https://lishogi.org/team/shh-its-shogi) and it failed. 
- Once he creates a team he is the team leader. After that if he makes someone else a team leader, he gets removed from being a team leader and the other person becomes a team leader.
- When the other person becomes a team leader, he isn’t able to make the 2 digit user a team leader.

https://user-images.githubusercontent.com/73843275/119792397-48a47580-bef3-11eb-8887-714329bb78c3.mov

**Comment by WandererXII** [comment]
Thanks for making the issue
