### ISSUE TITLE
Idea for unique puzzle creation

### ISSUE THREAD

**Issue by peanatsu** [WandererXII/lishogi#324]
- go over game with Yaneurao-mate-solver to find positions where a mate exists and then 
- for each found position, step through the attacking moves in the solution with normal Yaneruao-NNUE with MultiPV set to 2. At each point checking that the 1st move of the attacker is mate, but not the 2nd. Bonus points if the 1st move is mate and the 2nd losing, even better if 2nd move is mate for defender (like in traditional tsume)

This more or less ensures that the solution the users click through is unique (more or less because normal Yaneruao-NNUE can definitely miss mates, so it's more like an educated guess), but there may be some ambiguities in lines that don't occur in the solution.

Also note that you can either discard the solution as soon as you find an ambiguity, or you can keep going and simply use the longest tail of the solution that's unique. The latter approach has the downside that the start-position from the puzzle wouldn't be from an actual game anymore.

Let me know what you think

**Comment by justremember** [comment]
Already discussed. I think it would cut off too many of the puzzles. A compromise is already made where the 2nd best move can mate in at least 10 moves more than the 1st. https://github.com/WandererXII/lishogi/issues/301#issuecomment-841314190

**Comment by WandererXII** [comment]
What you suggest is very similar to the system we already have in place for puzzles from games - https://github.com/WandererXII/lishogi-puzzler/blob/master/generator/generator.py
Differences are that only one engine is used, only positions with a swing in evaluation are considered puzzle candidates and solutions leading to advantage are also considered good puzzles, not just mates.

All puzzles should now be unambiguous (ofc engine might have missed something), so if you find ambiguous ones, you can either report them or just downvote them.


> A compromise is already made where the 2nd best move can mate in at least 10 moves more than the 1st. [#301 (comment)](https://github.com/WandererXII/lishogi/issues/301#issuecomment-841314190)

I deleted everything where the second mate was found, no matter how slow. I noticed sometimes it had issues finding mates 15+, so puzzles like that might still exist tho.
