### ISSUE TITLE
Decouple board highlights in preferences

### ISSUE THREAD

**Issue by peanatsu** [WandererXII/lishogi#328]
currently board highlights (check and last move) can only be enabled or disabled together. I suspect most shogi players want the last move highlight, but not the check-indicator (AFAIK announcing check is even considered rude in shogi), which is how it works on 81dojo, shogidojo24 and shogiwars.

I suggest splitting this option into seperate choices, one for the last move highlight, the other for the check-indicator.

**Comment by WandererXII** [comment]
Done after the last update. Thanks for suggesting it.
