### ISSUE TITLE
The search function within a user's profile contains Results that are not legal in Shogi.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#33]
When accessing the Advanced Search feature within a user's profile, invalid "Result" values are shown.

Accepted Values:
* Mate
* Resign
* Stalemate
* Draw
* Clock Flag
* Variant End <-- Not sure what this one is.

Stalemate is impossible in Shogi. If a stalemate occurs, the winner is the player not in stalemate. Maybe there should probably be an option for Impasse/Jishogi as a result since the result can be either a draw or a win. Having a result for sennichite also might make sense.

In the Shogi world, repetition/sennichite is actually a null result. In professional games, they replay the whole game with colors reversed if a repetition occurs. A draw only officially occurs in Impasse/jishogi conditions.

**Comment by justremember** [comment]
I think stalemate should still be called a stalemate, but have the clarification that it is a win for the stalemating player.
Sennichite could be implemented either as a draw (stronger player loses a few rating points), or aborted game (no change in ratings). I feel making it a draw would be simpler though.
