### ISSUE TITLE
Suggestion: Please create an official discord for lishogi!

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#34]
All of the lishogi discord links go to the official Lichess discord server. I think communication can be aided significantly from an official Lishogi discord server being created.

Right now a lot of the discussion for Lishogi are happening in unrelated discord servers. It would help to have it all centralized on a server being organized by the developers instead of the Shogi Harbour discord!

**Comment by WandererXII** [comment]
Ok, I created a server -[https://discord.gg/tU4EeKJ7]( https://discord.gg/tU4EeKJ7), I will also add the invite link to the site around next week probably. Do want to be an admin?

**Comment by timezombi** [comment]
> Ok, I created a server -https://discord.gg/tU4EeKJ7, I will also add the invite link to the site around next week probably. Do want to be an admin?

Sure! I would love to be an admin. Thank you for offering! Since you created the server, I'll have to call this ticket closed!

**Comment by abunickabhi** [comment]
Sorry for reopening this ticket, but the invite link of discord is not working.

**Comment by WandererXII** [comment]
Here's a permanent one [https://discord.gg/YFtpMGg3rR](https://discord.gg/YFtpMGg3rR)
