### ISSUE TITLE
Can Play Simuls With Yourself 

### ISSUE THREAD

**Issue by lidevelopers** [WandererXII/lishogi#344]
https://lishogi.org/simul/mV2XZu65
![image](https://user-images.githubusercontent.com/85686806/121797242-a8618700-cc3c-11eb-92dc-508731c18bcf.png)

**Comment by TheYoBots** [comment]
How do I reproduce this bug?

**Comment by lidevelopers** [comment]
Please Do Not Spam Lishogi with this bug

**Comment by TheYoBots** [comment]
If you don’t mention how to reproduce, no one will know how to fix it. Also what makes you think things might get messy?

**Comment by lidevelopers** [comment]
create a new simul on lishogi.org and keep one simul tab open with the joining account to the simul and then open a new tab and login to the creator of the simul account and in the previous window click join and it is done

**Comment by lidevelopers** [comment]
please fix this

**Comment by justremember** [comment]
Someone will look into the bug eventually, so just stop spamming.
