### ISSUE TITLE
Can Play Ultrabullet From Position with Lishogi AI

### ISSUE THREAD

**Issue by lidevelopers** [WandererXII/lishogi#345]
https://lishogi.org/PCcChJvV
![image](https://user-images.githubusercontent.com/85686806/121802008-ef10aa80-cc57-11eb-860f-7e57b4615ad4.png)

**Comment by TheYoBots** [comment]
Can be reproduced using the API (Similar to https://lichess.org/api#operation/challengeAi )

**Comment by lidevelopers** [comment]
please fix this

**Comment by WandererXII** [comment]
I assume the problem is that the ai doesn't move fast enough, therefore it times out after few moves? I guess I will set it to at least a minute, if no inc or byo is set.
