### ISSUE TITLE
Bug: Simultaneous Exhibition's Starting Position field is populated with Chess Openings

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#35]
When hosting a new Simul, the Starting Position is populated with chess positions! Of course, none of them make any sense for Shogi. Better would be to have standard handicaps selectable instead! This should be pretty easy to implement for starting positions.

Other ideas are to have starting positions for common Shogi joseki: Side Pawn Picker, Double Wing Attack, Bishop Exchange, Fourth File Rook, Central Rook, Snow Roof, etc.

Also fun would be an option to set a custom Starting Position based on a custom SFEN.

**Comment by WandererXII** [comment]
Removed the chess positions, but proper positions still need to be added f33fd084b5a3e738aad93c1c96192165f2f687d0

**Comment by justremember** [comment]
I can populate them with shogi openings, but my choices would be rather limited because I cannot input positions with pieces in hand like bishop exchange & double wing attack.

**Comment by WandererXII** [comment]
Replacing the dash with pieces doesn't work?
Something like this? I guess the "from position" games need some work, I will look into it tomorrow.
lnsgkgsn1/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL w - 1
lnsgkgs2/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL w nl 1

**Comment by justremember** [comment]
Oh, my bad. I thought this feature wasn't implemented yet because the editor doesn't let you add held pieces still.

**Comment by WandererXII** [comment]
Handicaps are there, more openings will prob be added later
