### ISSUE TITLE
Suggestion: How to use lishogi

### ISSUE THREAD

**Issue by ghost** [WandererXII/lishogi#353]
I hope you will forgive me for taking a Japanese perspective.

I have seen many streamers, but so many people do not know how to use lishogi.
Please make a page to introduce the basic functions.
For example, how to play games, how to set the time, arena tournaments, how to analyze, and the basics of the study function.

Thank you for your consideration.

**Comment by justremember** [comment]
We could have a page for this, like https://lishogi.org/resources. On another note, wdyt of implementing japanese translations for prismic documents? @WandererXII I'm asking here before making an issue. I might also be the one to code it.

**Comment by WandererXII** [comment]
> On another note, wdyt of implementing japanese translations for prismic documents? @WandererXII I'm asking here before making an issue. I might also be the one to code it.

I did that for storm and impasse explanations here https://github.com/WandererXII/lishogi/commit/01e78189b43242c1bf8c628db804d9cc07a2cdbc, _Shogi resources_, _Contribute_ and _Thank you_ should probably also have a Japanese version, but I'm not sure whether translating tos or privacy is worth it.

**Comment by justremember** [comment]
Cool, so there's japanese page translations already. I'll tell ch_suginami once it's deployed.

> I did that for storm and impasse explanations here [01e7818](https://github.com/WandererXII/lishogi/commit/01e78189b43242c1bf8c628db804d9cc07a2cdbc), _Shogi resources_, _Contribute_ and _Thank you_ should probably also have a Japanese version, but I'm not sure whether translating tos or privacy is worth it.

I think translating TOS and privacy to japanese are worth it in the long run, if lishogi were to have a larger reach, cause some people might be interested in those. If ch_suginami cannot translate it, we'll eventually find someone with legal expertise who can. Same for all other pages.

**Comment by WandererXII** [comment]
Discussion moved to https://github.com/WandererXII/lishogi/issues/703
