### ISSUE TITLE
Suggestion: Too many notifications. Need ability to tone down number of notifications.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#36]
When enabling notifications for lishogi, I receive a notification for every single move my opponent makes in a Realtime game, even if the window is in focus the entire time and we're playing a short game. I really only want notifications for stuff like game challenges, people following me, resignation, etc. I don't want to have a notification for every single move for realtime games if possible.

However, for correspondence games, I definitely want the ability to have a notification for every move!

**Comment by timezombi** [comment]
I've since been unable to reproduce the issue. It may have been caused from having too many browser windows open? If I can't repro it again, I'll close the ticket!

**Comment by WandererXII** [comment]
Ok, close it if doesn't seem to happen again. I haven't touched notifications - therefore it should be the same as it was on lichess a few months ago. If it happens again I will look into it more.

**Comment by timezombi** [comment]
Didn't have any problems all day. Closing for now until I manage to repro it consistently.
