### ISSUE TITLE
Export game notation

### ISSUE THREAD

**Issue by Little-Mage** [WandererXII/lishogi#37]
Pychess has this feature here's the link https://www.pychess.org/tRID6wWf?ply=41 the button is on the bottom Copy UCI/USI

**Comment by ianfab** [comment]
For reference, that is a USI position string (i.e., `position startpos moves ...`), which some shogi GUIs apparently seem to use for copy/pasting game records. If I remember correctly that was about ShogiGUI.

**Comment by justremember** [comment]
Working on this but for kif only as of now. Hopefully I can finish this week.
