### ISSUE TITLE
Game corrupted?

### ISSUE THREAD

**Issue by Kuukyo3** [WandererXII/lishogi#38]
The one blitz game that I played seems to be saved incorrectly.

![image](https://user-images.githubusercontent.com/49610899/99422831-3b814b00-2900-11eb-8d96-6184fc7cd390.png)

It doesn't show in my game list below and if I click on it I get an error page:

![image](https://user-images.githubusercontent.com/49610899/99422916-4cca5780-2900-11eb-974a-f9e52adeef55.png)

**Comment by WandererXII** [comment]
Thanks for reporting this I will look into it.

**Comment by WandererXII** [comment]
Fixed that it won't happen again, but fix for already incorrectly saved game will come tomorrow.
