### ISSUE TITLE
Lishogi Team Search not working

### ISSUE THREAD

**Issue by Notproffesionalcoder** [WandererXII/lishogi#389]
So when we search a team in lishogi here: https://lishogi.org/team/all
It shows No team found
is it same for me this feature was working for me earlier.Could this be fixed.
Thanks 
Regards **NotProfessionalcoder**

**Comment by WandererXII** [comment]
Server with elastic search is not set up (same reason as these: https://github.com/WandererXII/lishogi/issues/206, https://github.com/WandererXII/lishogi/issues/184). Currently working on this.

**Comment by WandererXII** [comment]
Done - https://github.com/WandererXII/lishogi-search and https://github.com/WandererXII/lishogi-search-import.
