### ISSUE TITLE
Bug: In Analysis Mode with engine enabled, preview ghost images are upside down.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#39]
When in analysis mode with the engine on, the "ghost images" to indicate piece drops appear upside down. This makes me think that the engine is choosing the piece set based on the wrong "color" (mixing up black and white).

Examples:
![image](https://user-images.githubusercontent.com/600562/99458391-509ab180-28e1-11eb-914f-95f8c741f6bc.png)

![image](https://user-images.githubusercontent.com/600562/99458545-8cce1200-28e1-11eb-92a7-01f2142b1b46.png)

**Comment by WandererXII** [comment]
Closing this one, keeping https://github.com/WandererXII/lishogi/issues/40 opened for now
