### ISSUE TITLE
Bug in Players leaderboard 

### ISSUE THREAD

**Issue by TheYoBots** [WandererXII/lishogi#396]
**Exact URL where the bug happened**

https://lishogi.org/players

**Steps to reproduce the bug**

Go to https://lishogi.org/players and you will see that some players on the leaderboard haven’t played a game for over a week.

**What did you expect to happen?**

https://lishogi.org/faq#leaderboards Says,
> 2. have played a rated game within the last week for this rating

so they must not be on the leaderboard and must not have a rank/trophy in their profile.

**What happened instead?**

Players who haven’t played that particular time control/variant in that particular week must not be on the leaderboard and shouldn’t have a rank/trophy.

**Operating system and browser version**

I believe it would occur in any browser/device.

**Additional Requests**

Since lishogi has very few players, rather than providing a trophy to all those in the top 100 it would be better to only give a trophy for those who are in the top 10 in that particular time control/variant. Also I don’t think any leaderboard has more than 100 non provisional, less that 75 RD players, so anyone who passes the requirements [here](https://lishogi.org/faq#leaderboards) would get a trophy, so it isn’t much valued.

**Comment by WandererXII** [comment]
Thanks for reporting this. Should be fixed now.
