### ISSUE TITLE
Display background image on study page

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#399]
Background: transparent with https://cdn.discordapp.com/attachments/734106207215943712/865952402553045012/Shogi_Harbour_logo_1920-1080_discord_invite_splash.png

![image](https://user-images.githubusercontent.com/1834123/127740875-5a62f94a-96f8-4151-adb8-90963cf163cb.png)

**Comment by WandererXII** [comment]
https://github.com/ornicar/lila/issues/6684
Best solution would prob be to proxy the requests and add the `Cross-Origin-Resource-Policy: cross-origin` header.

**Comment by WandererXII** [comment]
Once it's supported, I would like to use this [https://developer.chrome.com/blog/coep-credentialless-origin-trial/](https://developer.chrome.com/blog/coep-credentialless-origin-trial/), then we wouldn't need to proxy the requests.

**Comment by ddugovic** [comment]
Thanks; my own attempts (on my VPS, without a proper SSL certificate) to proxy requests were unsuccessful, and I agree I would like to use that too.

**Comment by WandererXII** [comment]
Just noticed vercel doesn't allow proxies, so I will have to set it up elsewhere.
