### ISSUE TITLE
Engine suggested drop/promotion shows wrong pieces/piece set

### ISSUE THREAD

**Issue by tttetsuo** [WandererXII/lishogi#40]
While analysing a game the suggested drops are shown using a different piece set. Also, promotion always appears as a tokin.
![droppiece](https://user-images.githubusercontent.com/39503566/99462998-9a9c8b00-2913-11eb-8b62-963b89adece5.png)
![promotion](https://user-images.githubusercontent.com/39503566/99463032-a5572000-2913-11eb-86db-d3149abd97cb.png)

**Comment by timezombi** [comment]
Good find! This seems related to issue #39 , where the pieces were displaying upside down.

**Comment by WandererXII** [comment]
Fixed the piece set being and direction being wrong here https://github.com/WandererXII/lishogi/commit/aef6c83482eeb1436f546fad904a29aea681b070
The tokin - I will fix later, problem there is that the engine returns only "+" at the end of the string for promotion, unlike in chess and it just defaults to tokin, passing the whole board every time to see what piece is going to be promoted is kinda ugly, but I'll prob do that for now.

**Comment by WandererXII** [comment]
Fixed here d73894fd206687c103f6cf088d236dd46fbf379b, thanks for submitting the issue.
