### ISSUE TITLE
Bug: Game record in analysis mode records an illegal promotion.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#41]
I'm not sure how to reproduce the issue, but at least on of my game record is showing illegal promotions. During the actual game I was never given an option to promote, however the game record shows the illegal promotion.

It happens on move 63 in this kifu:
https://lishogi.org/y1vodwUU#63

![illegal_promotion](https://user-images.githubusercontent.com/600562/99467333-0a4e4e00-28f3-11eb-8c3c-3967ebdb7579.png)

**Comment by WandererXII** [comment]
Thanks for reporting this, fixed that this will not be happening for new games, will try to fix already incorrectly saved promotions tomorrow.
