### ISSUE TITLE
Error in the ToS

### ISSUE THREAD

**Issue by TheYoBots** [WandererXII/lishogi#423]
In the [`Terms of Service` page](https://lishogi.org/terms-of-service), under the side heading `Fair Play and Community Guidelines`, the 4th point (`4. Trying to break …`) states:

> 4. Trying to break into accounts of other users, even if it’s as simple as just guessing a password, DDoS and volumetric attacks. This activity is illegal, so the relevant authorities would also be notified. You are welcome to support **Lichess** by [finding and reporting security issues to us](https://lishogi.org/contact#help-security).

The word **Lichess** which has been written in **bold** seems to be an error/mistake. It should be **Lishogi** instead. This can’t be edited through GitHub, hence I made an issue.

**Comment by WandererXII** [comment]
Fixed, thanks!
