### ISSUE TITLE
KIF files does not work ShogiGUI for correctly(mainly Japanese Users?)

### ISSUE THREAD

**Issue by ch-suginami** [WandererXII/lishogi#431]
Some KIF files downloaded from lishogi pages does not work correctly using ShogiGUI showing "Importing Error".
This error occurs when `.kif` extension files with UTF-8 encoding opens.
So if we open the same files with the combinations `.kifu` extension and UTF-8 encoding, or the combination `.kif` extension and Shift-JIS encoding, no problems happen.

This format is written in the [official page](http://kakinoki.o.oo7.jp/kif_format.html) of the second block.
> 文字コードは、拡張子が ".kif" の場合は Shift-JIS、".kifu" の場合は UTF-8 である。
(This explanation is Japanese but the meaning is the same I already mentioned above.)

I know that `.kifu` extension was used around first release of KIF formats at lishogi but it might have caused other problems.
KIF format is very complex and I hope we find the solutions for all users.
Thanks.

**Comment by WandererXII** [comment]
Yep, having one format use two different encodings is really annoying. I was considering a submenu, where the user could choose between `.kif` (Shift-JIS) and `.kifu` (UTF-8), but I didn't want to further confuse users who are not familiar with the differences.
We could also just go back to `.kifu`, like the page suggests, but I actually haven't seen `.kifu` that much in the _wild_, so I'm not sure whether, it's really that standardized. We went to `.kif`, since there were reports, that some software wasn't able to open `.kifu`...
Also in shogiGUI UTF-8 `.kif` files work for me when I select UTF-8 in the file selection menu.
![image](https://user-images.githubusercontent.com/43043181/133941925-84705767-57fe-408d-a046-72ae682d2c7b.png)

It's of course also possible something else went wrong in the export, so if that still doesn't work, can you please send me the file, or the link to the study/game?

**Comment by ch-suginami** [comment]
@karakoro first reported that exporting [this game](https://lishogi.org/jYLWr57k/gote) did not work with ShogiGUI after move 37 (so the trouble will raise at move 37).

If I changed the extension `.kif` to `.kifu`, no problems. Also if I edit the KIF file encoding UTF-8 to Shift-JIS, no problems.
I think this encoding trouble is mainly ShogiGUI program because I checked another GUI program which is [将棋所(Shogi-Dokoro)](http://shogidokoro.starfree.jp) did not show any errors the game.

So the exporting files would be correct but some other troubles occurred inside the ShogiGUI program.

I agree `.kifu` extension files is not used widely and some GUI programs can't recognize them.
To avoid this annoying troubles, `csa` format might be a better answer now I think.
I will continue checking and collecting reports about KIF troubles.

**Comment by WandererXII** [comment]
Okay then, I will add an option to export `.kif` with Shift-JIS encoding, and I will also start working on `csa` export and import.
Thanks for the report.

**Comment by akicho8** [comment]
> where the user could choose between .kif (Shift-JIS) and .kifu (UTF-8), but I didn't want to further confuse users who are not familiar with the differences.

Certainly many users are confused.

The KIF format is an unclear format where the specification is not clear, and the various applications are parsed with their own interpretation.
Currently, many people are burdensome that the character code is different. KIF exists.
And many people are not familiar with character codes.
The original specification is written that the extension is `.kif` and `.kifu`.
But this is too difficult and it is a very difficult specification.
Also, from the extension of `.kifu`, no one thinks that the U's character represents the meaning of UTF-8.
The most good thing is that each application automatically recognizes the character code.
Do not complicate the application's Export functionality.
Specifically, ShogiGUI should automatically recognize character codes.

**Comment by ch-suginami** [comment]
I just posted a suggestion to the ShogiGUI developer to recognize character codes automatically.
So only I can do is to wait the reply.
When the reply comes, I will report here.

**Comment by akicho8** [comment]
> I just posted a suggestion to the ShogiGUI developer to recognize character codes automatically.

Thanks.
When realized, many users and developers burden will be reduced and will be happy.
The impact of ShogiGUI is large.

**Comment by WandererXII** [comment]
I added CSA export and also an option to export KIF with Shift-JIS encoding (https://lishogi.org/blog/YWjrNhEAACQAjidY/csa-support). Hopefully it's not too confusing, if ShogiGUI starts automatically recognizing the encoding, I will probably remove it...
