### ISSUE TITLE
KIF import does not work when header line starting with asterisk

### ISSUE THREAD

**Issue by akicho8** [WandererXII/lishogi#433]
# Steps to reproduce

Copy
https://www.shogi-extend.com/w/persona42-itoshinTV-20210910_232622.kif
to
https://lishogi.org/paste

# Actual behavior

```
Cannot parse moves from kif: [4.1] failure: end of input expected

先手:persona42 五段
^
```

I explain reason of strange structure.
If there is a line with a URL as a value in the KIF header, ShogiGUI fails to read.
It is a problem with ShogiGUI.
But even if it is reported, it will not be corrected.
Because there is no choice, I commentouted a line containing the URL.
Now it is now possible to avoid defects in ShogiGUI.

# Expected behavior

If such a strange  structure:

```
*KEY1：VALUE1
手合割：平手
手数----指手---------消費時間--
   1 ７六歩(77)
* Something comments
   2 ３四歩(33)
   3 投了
```

Interpret as follows:

```
手合割：平手
手数----指手---------消費時間--
*KEY1：VALUE1
   1 ７六歩(77)
* Something comments
   2 ３四歩(33)
   3 投了
```

That's ideal.

**Comment by WandererXII** [comment]
Thanks for reporting this. This will be live once I also finish `.csa`, should be within few weeks.

**Comment by akicho8** [comment]
Thanks so much for the efforts.

**Comment by akicho8** [comment]
When is this fix apply in the production?
