### ISSUE TITLE
Engine suggested moves are written in the wrong notation

### ISSUE THREAD

**Issue by tttetsuo** [WandererXII/lishogi#435]
![image](https://user-images.githubusercontent.com/39503566/134420468-85e4bd42-8b49-4110-b3ba-72a3300670d3.png)
After requesting computer analysis on a study, the first move of a suggested line is always shown using western notation, regardless of the already in use.

**Comment by WandererXII** [comment]
It's only a comment with the wrong notation used, the actual move is below it. I know this isn't optimal, so I will pass the user's selected notation.
Or I could just get rid of that comment and use it only when exporting to kif...

**Comment by WandererXII** [comment]
Fixed in the last update. Thanks for reporting it.
