### ISSUE TITLE
Puzzle of the Day 9/27

### ISSUE THREAD

**Issue by RoriUSer** [WandererXII/lishogi#437]
I want my rating points back. There were two possible answers for the 9/27 puzzle but it only accepts one.

**Comment by TheYoBots** [comment]
Do you have the link to that puzzle? Would be helpful if provided, also mentioned what the other possible answers was for you didn’t get rating points.

**Comment by RoriUSer** [comment]
> Do you have the link to that puzzle? Would be helpful if provided, also mentioned what the other possible answers was for you didn’t get rating points.

https://lishogi.org/training/Lldke

Rook takes silver on 4a and i have the option of promoting and not promoting. Both lead to the same outcome however if you don't promote it's consider wrong.

**Comment by TheYoBots** [comment]
This is a know issue https://github.com/WandererXII/lishogi/issues/314

**Comment by WandererXII** [comment]
I plan to get to fix that soon, but unfortunately we can't refund you your puzzle rating.
