### ISSUE TITLE
[Suggestion if possible to do] Arena mode with "From Position" mode

### ISSUE THREAD

**Issue by ch-suginami** [WandererXII/lishogi#438]
I heard one lishogi user questioned about that is it possible to held arena with "From Position" mode.
This suggestion is not high priority but is interesting idea for me.
He suggested it because we can held "specific situation arena" that is similar but strictly different to the "Bougyoku Event".
In addition to this suggestion, some virtual shogi streamers had already hold special topic arena (with normal mode) such as "only ranging rook opening". So if this mode is implemented, they are very welcome and another special feature of lishogi, I think.

Of course, I know that "From Position" mode is only activated "Play with Friend" and there are other issues around KIF and so on.
So I just suggest this idea here but if the developers have some time to add this mode, I will appreciate very much.
Thank you for continuing operating and developing.

**Comment by WandererXII** [comment]
Thanks for suggesting this. Upstream has this feature, so I will look into merging it.
