### ISSUE TITLE
Bug: Mobile clients show chess notation in Studies.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#44]
Possibly related to bug #15 , which is supposed to be fixed, except it is happening with all variations not just sub-variations. 

Basically, Studies are showing chess notation instead of Shogi notation on mobile clients. Tested with Android versions of Chrome, Canary, and Microsoft Edge.

Example:
![Screenshot_20201117-233705](https://user-images.githubusercontent.com/600562/99500619-7a7ac500-292f-11eb-8c8e-0ead00755161.png)

**Comment by WandererXII** [comment]
This is probably related to the inline view thing. I fixed that one earlier and I can't seem to reproduce this now. I will close this if you can't reproduce it again. Thanks for reporting this.

**Comment by timezombi** [comment]
Confirmed fixed! Thank you!
