### ISSUE TITLE
character corruption?

### ISSUE THREAD

**Issue by ghost** [WandererXII/lishogi#449]
This is lishogi's kif, posted on a web site called note(https://note.com/).
I am Japanese, but I do not know this kanji.
I think it's probably character corruption.

![9d8e8d1aaac17981](https://user-images.githubusercontent.com/44540355/136370702-fa24b3ec-2f2e-4eea-938d-adc978ee8abe.JPG)

**Comment by WandererXII** [comment]
This is the relevant line `s"$speed$variant Shogi • ${playerText(g.sentePlayer)} vs ${playerText(g.gotePlayer)}"` (https://github.com/WandererXII/lishogi/blob/master/app/templating/GameHelper.scala#L36), so '•' is to blame...
It gets encoded as UTF-8 to `%E2%80%A2`, but I guess note.com tries to decode it as Shift-JIS...
![image](https://user-images.githubusercontent.com/43043181/136424727-e4f474fb-9c6d-41e8-9de2-103c58048b36.png)

So I guess I will replace the '•' with a '-', the bullet looks nicer tho.
But still if the names are kanji or kana (can happen in studies or imported games), it's still gonna be decoded wrong... Not much I can do about it tho, most sites expect UTF-8...
