### ISSUE TITLE
Wood pieces blend in with wood boards

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#456]
Wood pieces blend in with wood boards:
![image](https://user-images.githubusercontent.com/1834123/139358060-7c43c22d-0544-4b06-b0b4-cdf8537634ea.png)

Maybe copy some ideas from Lichess?  But maybe not.
https://github.com/ornicar/lila/search?q=dark+board
![image](https://user-images.githubusercontent.com/1834123/139357938-fc43676e-075e-4062-847e-61313b5c7bb5.png)

**Comment by WandererXII** [comment]
Maybe we could add an outline to the pieces in this set or make them 3d and add shadows, not sure how it would look.
But I don't think we can make all piece sets and boards compatible. I don't think lichess is doing anything special either.
![image](https://user-images.githubusercontent.com/43043181/140798857-eb8cd763-7e00-4d46-b73f-182b54c01e35.png)

**Comment by ddugovic** [comment]
Thanks, this makes sense.  I see there were other wood boards available... it's probably best to have artists contribute updated piece sets and/or boards in most cases.

Ah, that's right that Lichess doesn't do anything special either.
