### ISSUE TITLE
Add /page/documentation

### ISSUE THREAD

**Issue by TheYoBots** [WandererXII/lishogi#459]
> Like Lichess: https://lichess.org/page/documentation
>
> For example, if I want to read about the meaning of KIF headers, the only page that contains a link to https://lishogi.org/explanation/kif is this blog post: https://lishogi.org/blog/YTpk6RAAACUAI5dL/kif-imports-and-exports
>
> With https://lishogi.org/page/documentation , all links would be easily accessible for users (and the link to Documentation should be accessible from the menu).

~ https://lishogi.org/forum/lishogi-feedback/add-pagedocumentation

**Comment by WandererXII** [comment]
https://lishogi.org/page/documentation added. Now just to add all the relevant articles there and add the link to documentation somewhere.

**Comment by WandererXII** [comment]
https://github.com/WandererXII/lishogi/issues/703
