### ISSUE TITLE
Computer analysis Failing

### ISSUE THREAD

**Issue by TheYoBots** [WandererXII/lishogi#464]
**Exact URL where the bug happened**

https://lishogi.org/vRFGgIQC
(Not sure if any other game, post if you find)

**Steps to reproduce the bug**

[Open the link](https://lishogi.org/vRFGgIQC) and check the computer analysis tab. The computer analysis is loading (clearly not started) and has been going on for 5 days now with no results. The user is unable to request analysis of any other game because of this. "(Might be good to allow 2 games to be analysed at the same time by a user till further fixes?)

**What did you expect to happen?**

Expected computer to analyse the game and allow the user to request analysis for other games once done.

**What happened instead?**

Analysis never happened (never even started I believe).

**Operating system and browser version**

Any OS/Browser

**Other Information**

On discord: https://discord.com/channels/778633701541806081/778633953992376350/908386312472637471 onwards
Forum Post (might be related): https://lishogi.org/forum/general-shogi-discussion/computer-analysis

**Comment by WandererXII** [comment]
Thanks for bringing to my attention. I deleted few analysis requests that were slowing down the analysis and set up a server with another fishnet instance with separate client key. I will make some tweaks so this doesn't happen again.
