### ISSUE TITLE
[Suggestion] Kanji Piece Set with Dark and Light Bgs

### ISSUE THREAD

**Issue by visualdenniss** [WandererXII/lishogi#468]
I was suggested in Lishogi Discord to file the issue here. I've created a kanji piece set with dark and light background to make it easier for beginners to orientate themselves perceiving what is going on in the board in a certain stages of middle game positions faster or easier and so on. I think it could be helpful for players like me. We have now added this set on PyChess and i would like to ask if it would be possible to add it on Lishogi as well: 

<img width="645" alt="Screenshot 2021-11-21 at 12 12 06" src="https://user-images.githubusercontent.com/80699817/142759983-1bb8cae1-a62f-41a1-8eaa-c47006428a85.png"> 

You can also see it live on the website: https://www.pychess.org/editor/shogi (by selecting the last piece in the board editor)

Here is the Zip file containing all the pieces for use. 
[shogi-BnW.zip](https://github.com/WandererXII/lishogi/files/7576158/shogi-BnW.zip)

Thanks.

**Comment by WandererXII** [comment]
Thanks, I added the set.

One idea - currently white is always going to the bottom color, which is fine, but I thought it could be nice to have black pieces 'stick' with sente and white pieces with gote. The css would have to be larger, since we would need include both white and black pieces facing down and also up. Not sure if we want to do that.

**Comment by ochamaru39** [comment]
Nice to meet you.

I really like the black and white shogi piece set, which is very cool!
The current black-and-white piece set is the opposite of Sente and Gote notation of the game record, I use Japanese style notation, so it is more confusing.
I agree with WandererXII's idea. I hope that black pieces are with Sente and white pieces are with Gote.
I think it might be more useful for people in the chess sphere to be able to choose between black and white pieces for either Sente or Gote.
Personally, I would like to see the black pieces as Sente and the white pieces as Gote.

**Comment by visualdenniss** [comment]
Thanks for the feedback, 

sure, that was also my initial idea actually, to fix them to certain colors: Dark for Sente always and Light for Gote etc. I did postpone the work, just in case there is a fix via chessgroundx or via some CSS. 

Anyways, i'll create the upside version of the whole set then now, however since there is no such set, i'll have to come up with file names, for that i plan to use 0FU-1 and 1FU-1 for their upside version, i hope that naming convention is ok as well?

**Comment by ochamaru39** [comment]
I'm very happy to hear the good news. Thank you very much.
I'm sorry to just give my opinion, but I don't know anything about programming, so I'll leave the decision about naming conventions to the two of you.

**Comment by WandererXII** [comment]
> Anyways, i'll create the upside version of the whole set then now, however since there is no such set, i'll have to come up with file names, for that i plan to use 0FU-1 and 1FU-1 for their upside version, i hope that naming convention is ok as well?

Thanks! Appending `-1` for pieces facing up sounds good, anything that will distinguish them will do.

**Comment by visualdenniss** [comment]
[shogi-BnWx2.zip](https://github.com/WandererXII/lishogi/files/7755263/shogi-BnWx2.zip)

Here is the full set to fix dark pieces to sente and light ones to gote. I've named different color version of the same piece (either normal or upside version) with "...-1", but you can easily change that according to how their use requires it :) My pleasure! Hope the piece set will be useful!

**Comment by visualdenniss** [comment]
It would also be great to have some of the board theme that are already available for 1:1 also be available for 11:12. Such as these for example:

<img width="505" alt="Screenshot 2021-12-26 at 12 33 03" src="https://user-images.githubusercontent.com/80699817/147404280-9ccb0778-9896-43ac-9fdb-ccf33b7ea871.png">
<img width="503" alt="Screenshot 2021-12-26 at 12 33 29" src="https://user-images.githubusercontent.com/80699817/147404284-e070b94e-bce6-4103-a05e-36096f3f5937.png">

They complement the dark/light piece set quite harmoniously in my opinion :) Thanks.

**Comment by sukrosono** [comment]
This is great

**Comment by WandererXII** [comment]
> [shogi-BnWx2.zip](https://github.com/WandererXII/lishogi/files/7755263/shogi-BnWx2.zip)
> 
> Here is the full set to fix dark pieces to sente and light ones to gote. I've named different color version of the same piece (either normal or upside version) with "...-1", but you can easily change that according to how their use requires it :) My pleasure! Hope the piece set will be useful!

Thanks a lot! I will write generate the css and update it on the server as soon as I can.
