### ISSUE TITLE
]Issue] Inactive accounts automatic get closed!

### ISSUE THREAD

**Issue by FlyingndCoding** [WandererXII/lishogi#469]
I did not use lishogi for long
and my accounts got automatic close:
My accounts:
Birdlover-Human
Japanesechessisgr8ye-BOT
Shogilearning-Human
and 2morebots

**Comment by TheYoBots** [comment]
Accounts are closed if they are banned so you'll need to appeal if your account is banned https://lishogi.org/appeal

**Comment by FlyingndCoding** [comment]
Oh ;/ i did not break any rule tho
