### ISSUE TITLE
[Variant] Kyotoshogi

### ISSUE THREAD

**Issue by WandererXII** [WandererXII/lishogi#471]
- [ ] Notation - what's proper notation for kyotoshogi, both western and Japanese? Do we show promotion, if it's automatic? What about drop notation?
- [ ] USI - is there a standard? Is promotion noted?
- [ ] KIF - examples would be appreciated

**Comment by CouchTomato87** [comment]
Notation/USI - I don't think there's any. Kyoto Shogi is a relatively young game so AFAIK, notation hasn't really been defined.

KIF - You can find a whole bunch of example games here: https://www.pychess.org/tournament/s9Ri5QXg

**Comment by WandererXII** [comment]
Notation:
![image](https://user-images.githubusercontent.com/43043181/232621880-f13c13b7-c1c9-4250-b159-e7a14477d7c0.png)

For the gold (originally) move. Is this notation okay? Pychess would say this: '_+N-34-_',which is also an option, but I think 'G' as gold is more intuitive that '+N' as promoted knight, also in the initial position we have a gold and not knight...
For Japanese notation and kif, we might also use the combined name from the both sides of the peice in this case '金桂'.

**Comment by CouchTomato87** [comment]
Yes, I actually prefer this.

Maybe for Kanji, you can swap the order depending on the piece moved? For example, 金桂 means Gold that became Knight during movement while 桂金 means Knight that became Gold during movement. Very intuitive I think.

Theoretically you could also do the same with western. I.e. GN and NG.

**Comment by WandererXII** [comment]
That would be nice, but wiki says:

> The names of the pieces combine their promoted and unpromoted values, and are puns in Japanese for words with the same pronunciations but different kanji. For example, the lance/tokin is homonymous with the name of the city 京都 [Kyoto](https://en.wikipedia.org/wiki/Kyoto), and provides the name of the game.

And switching them around would break that. We can still do it with the western one tho.
But for drops we have to stick to one letter only, since I have 'L\*1c' for dropping lance top and 'T\*1c' fo dropping tokin top (rather than 'T\*1c+' or something for lance top) - similarly in Japanese notation.

**Comment by CouchTomato87** [comment]
Yep, very much aware of the puns. But if it's something that makes notation cleaner, then breaking the pun half the time doesn't hurt if it improves notation readability, I think. It's kinda more of a thing that inspired the game but not really something that needs to be stuck to rigidly.

Agree with drops.

**Comment by CouchTomato87** [comment]
My vote is 1 or 4. Definitely not 2

**Comment by CouchTomato87** [comment]
I don't know how possible this is... but what if instead of "+" for promotion, you have the endpoint of the piece?

Like instead of P-34 or PR-34, you have P-34R. And for kanji, same thing. I think this kind of fixes all your issues, keeps it close to original shogi notation, and simply replaces the "+" with a name. I don't really think of these pieces are promoting or demoting, but simply switching sides.

**Comment by WandererXII** [comment]
That could be done, it's similar to chess pawn promotions. It's a bit hard to read, maybe separating it - `P-34=R`, but that's kinda long... I think I still prefer simple +/成 tho, but if it doesn't _work_, I will change it.

**Comment by WandererXII** [comment]
I will close this, since it;s done. But feel free to open a new issue, if you think the notation should be changed.
