### ISSUE TITLE
[Update] Updated Intl Kings (AND Silvers and Dragons)

### ISSUE THREAD

**Issue by CouchTomato87** [WandererXII/lishogi#474]
[LishogiIntlKingUpdate.zip](https://github.com/WandererXII/lishogi/files/7736158/LishogiIntlKingUpdate.zip)

Here are updated pieces for the kings in the international sets. The kings are slightly more stylized, and in the monochrome sets, black and white are now distinguished by solid and hollow kings rather than a separate colored line.

**Comment by CouchTomato87** [comment]
Per feedback from Shogi Harbour, I've also updated the silvers (in monochrome sets only) and dragon kings (in all sets) for the internationalized sets. The Kings are not included are in the original post above. @WandererXII Would you be able expedite this update? Karolina will be using these in her streams soon so it would be nice to have these updated :)

Also, I will be working on an internationalized version of Portella's very nice pieces. I expect them to be done within a day from now, but I'm just sending the other pieces now because I think you guys do something to compress their file size too.
[Silver Dragon Update.zip](https://github.com/WandererXII/lishogi/files/8075462/Silver.Dragon.Update.zip)

**Comment by CouchTomato87** [comment]
Okay, and here is the final update: Portella-style Internationalized pieces:

[Portella Internationalized.zip](https://github.com/WandererXII/lishogi/files/8083102/Portella.Internationalized.zip)

**Comment by CouchTomato87** [comment]
The 0NG.png from the Portella in
![0NG](https://user-images.githubusercontent.com/52322435/157345566-441c9d12-e0ae-40b9-b1be-ce98c45a424f.png)
tl set had double shadow by accident. Here is the updated file

**Comment by WandererXII** [comment]
Will be live in few (hopefully 2) weeks.
