### ISSUE TITLE
[Variant] Annan shogi（安南将棋）

### ISSUE THREAD

**Issue by ghost** [WandererXII/lishogi#475]
Same board size and pieces as standard shogi
Popular in Japan and has a long history
Very deep gameplay
Annanshogi has not been implemented on other sites.

https://en.wikipedia.org/wiki/Annan_shogi

**Comment by WandererXII** [comment]
Wikipedia article mentions there are two variants:
> when a piece has a friendly piece on the square directly behind it, it has the movement of that piece instead of its own

and

> piece may move like any friendly piece that protects it

I suppose we want to go with the first main(?) one?

**Comment by WandererXII** [comment]
Here's a demo: https://lishogi1.org/assets/sandbox/annan/index.html

If anyone's familiar with annan shogi, please look it over.
