### ISSUE TITLE
Enhancement, give info black/gote on UI

### ISSUE THREAD

**Issue by sukrosono** [WandererXII/lishogi#480]
Till now I still confuse or sometimes wrong which one is sent or gothe.
Secondly I think we should have advance mode (non learning mode), which have feature like. No warning when king is checked. so if you forgot / not aware. bundler not taking defensive move you will lose the game.

**Comment by visualdenniss** [comment]
You can use the dark/light piece set. See here: https://github.com/WandererXII/lishogi/issues/468
Last week, i've provided the full set so that dark pieces can be fixed to Sente and light pieces to Gote. So probably, this version of full set will be available on Lishogi for use in very near future.

**Comment by sukrosono** [comment]
oh damn, really cool. Thanks for your work @visualdenniss
