### ISSUE TITLE
11:12 Board Geometry does not align with pieces on tablet

### ISSUE THREAD

**Issue by visualdenniss** [WandererXII/lishogi#483]
![IMG_2004](https://user-images.githubusercontent.com/80699817/147404539-c50a0750-0130-4039-80e4-1529561f517f.jpg)

Device: Ipad Pro, Orientation: Landscape, Browser: Safari. 

Pieces, no matter which piece set, do not align with the 11:12 Board for standard Shogi as well as Minishogi.

**Comment by WandererXII** [comment]
Should be fixed with https://github.com/WandererXII/lishogi/commit/71bc22df1dc3ed98812e680fd2c041cdfec87593, but it's not live yet, I will keep this open, until it is, so we can confirm the fix.

**Comment by WandererXII** [comment]
Should be good now.
