### ISSUE TITLE
Shogi/Minishogi Games from Pychess don't get imported

### ISSUE THREAD

**Issue by TheYoBots** [WandererXII/lishogi#487]
**Exact URL where the bug happened**

https://lishogi.org/paste

**Steps to reproduce the bug**

1. Play a game on [pychess.org](https://pychess.org) and copy the pgn (psn for shogi right?) **or** Directly copy the pgn/psn from a shogi game on pychess.org.
2. Paste the game on [Lishogi's import page](https://lishogi.org/import).
3. The following Error occurs
```
Invalid Notation

Kif parsing error: No moves, non-standard starting position or valid tags provided
```
- Pychess game I attempted to import: https://www.pychess.org/MJOKlimP

**What did you expect to happen?**

Game gets imported

**What happened instead?**

Game doesn't get imported. Though I think that by supporting the PSN(?) format for imports, games can be imported

**Operating system and browser version**

Any.

**Screenshot**

![lishogi-bug](https://user-images.githubusercontent.com/73843275/149085771-30a8dc7b-0d25-463e-8622-9d551098931c.png)

**Additional Information**

Also in studies importing a game just by pasting the game link from websites other than lishogi like 81dojo, pychess, shogiclub24, etc...(These are the only other famous sites I can think of now).

**Comment by KarolS** [comment]
That is not PSN, that is PGN; PGN uses terms White and Black, while PSN uses Sente and Gote, PGN labels squares a1 to i9, while PSN labels them 1a to 9i etc.

Anyway, neither PSN nor PGN are supported right now.

An example game in PSN format can be found here: https://web.archive.org/web/20170602142620/http://japanesechess.org/psn_white_sheet.php

**Comment by WandererXII** [comment]
Yep, but either way lishogi doesn't support either PGN os PSN. If enough people are interested I can write a parser for PSN, but I haven't seen it around too much, maybe KI2 is something that should be done before that.
I do not plan to add support for PGN, it's not really a shogi format.
