### ISSUE TITLE
colors? why no sente and gote

### ISSUE THREAD

**Issue by kleffa** [WandererXII/lishogi#49]
I think maybe just sente and gote or first players and second players is better than black and white since shogi has no colors, it become just more confusing

**Comment by WandererXII** [comment]
You are right, my intention was not to scare people with foreign words, but since the pieces are already scary enough this doesn't make much sense. I will change this as soon as I can, but since it involves many changes, don't expect it anytime soon tho.

**Comment by CouchTomato87** [comment]
Also one thing to keep in mind is that black and white do not always meet sente and gote, respectively. I'd imagine lishogi will have handicap support in the future, so you have to think of uwate and shitate.

**Comment by WandererXII** [comment]
Slowly started changing black to sente and white to gote, there will still be some places, where it has not been replaced yet and many languages where the translations weren't made. Please submit a new issue for the former case (wrong lines in english), thanks!
