### ISSUE TITLE
Minishogi Computer Analysis

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#495]
**Exact URL where the bug happened**
https://lishogi.org/9y8GgSkI/gote#20

**Steps to reproduce the bug**
1. Click "Start a Computer Analysis"

**What did you expect to happen?**
A server-side engine automatically annotates the game.

**What happened instead?**
Idle cursor spins forever

**Operating system and browser version**
Windows 10, Microsoft Edge

![image](https://user-images.githubusercontent.com/1834123/150652989-6d25af77-7cf3-4192-a721-8ee58bf036da.png)

**Comment by SriMethan** [comment]
It happens to me too. also if you see lishogi's Advanced search https://lishogi.org/games/search?perf=12&sort.field=d&sort.order=desc&analysed=1#results It shows that only 9 minishogi games are analyzed about 1 month ago.

**Comment by WandererXII** [comment]
Should be solved with the shoginet rewrite. Hopefully, not sure why it used to hang...
