### ISSUE TITLE
Blog posts don't display every time on the main page

### ISSUE THREAD

**Issue by WandererXII** [WandererXII/lishogi#5]
Sometime reload is needed to display the blog posts

**Comment by justremember** [comment]
How do you replicate this bug? I haven't been able to.

**Comment by WandererXII** [comment]
I can't replicate it consistently, but sometimes the blogposts just aren't sent from the server. You can't replicate it at all?

**Comment by justremember** [comment]
Still nope. Could've been a problem on Prismic's end.

**Comment by justremember** [comment]
Oh this issue didn't close automatically for some reason.
