### ISSUE TITLE
Problems and Related Suggestion about Board Editor system

### ISSUE THREAD

**Issue by ch-suginami** [WandererXII/lishogi#51]
When we use the Tools->Board Editor page, pieces can’t be placed to either hand’s area. The Editor system is the powerful tool so many players are confusing to make their original boards when they want to put pieces in either hand. Unlike chess games, normal shogi (meaning not for tsume-shogi puzzles or handicap/koma-ochi systems) has always 40 pieces on the board (including in both hands). I think optional checking system which checks the number of each kind of pieces and total number, is one way to improve the Board Editor system. Of course I know that some players are enjoying for making non-formal and original styles so this checking system should be optional. Anyway pieces which can’t be placed problem needs to be fixed I think.

**Comment by timezombi** [comment]
I agree. Not being able to place pieces on the piece stand / pocket is a huge problem. As a workaround, I've been using ShogiGUI to make the diagrams and then exporting the position to an SFEN. Importing positions by SFEN works great for everything I've tried so far.

**Comment by timezombi** [comment]
Since there are current plans to switch to chessgroundx for the UI, I think this might be on hold until chessgroundx is integrated.

**Comment by WandererXII** [comment]
Thanks for the suggestions.
Pieces in hand were added some time ago, 'Fill gote's hand' button was added and today I also added piece counter and fixed some bugs (https://github.com/WandererXII/lishogi/commit/f0beadfa4e6d1395dd6ad72f3ce913ead002af2e), everything should be good now.
