### ISSUE TITLE
Statistical Capture - Player settings

### ISSUE THREAD

**Issue by CouchTomato87** [WandererXII/lishogi#511]
Is it possible to keep track of what users have as their settings as preferred pieces and boards? Karolina is interested in knowing.

**Comment by WandererXII** [comment]
From db, includes only registered users that have changed preferences at least once.
It might be interesting to set up a page where this and other user preferences would be displayed, refreshed every hour for example. Not sure if that's what you meant.

Anyways, pieces:

| Pieces               | Count |
|----------------------|-------|
| Ryoko_1Kanji         | 4846  |
| kanji_light          | 1335  |
| doubutsu             | 1218  |
| western              | 993   |
| Intl_Colored_2D      | 935   |
| Intl_Wooden_3D       | 621   |
| Shogi_cz             | 581   |
| Vald_opt             | 572   |
| kanji_red_wood       | 559   |
| international        | 521   |
| Kanji_Guide_Shadowed | 495   |
| Portella             | 487   |
| Intl_Colored_3D      | 483   |
| orangain             | 456   |
| Portella_2Kanji      | 446   |
| Intl_Monochrome_2D   | 431   |
| kanji_brown          | 407   |

And here are square boards prefs:

| board      | Count |
|------------|-------|
| wood1      | 8528  |
| solid      | 1518  |
| oak        | 1258  |
| Kinkaku    | 811   |
| kaya1      | 728   |
| Painting1  | 527   |
| solid      | 523   |
| kaya2      | 386   |
| space2     | 366   |
| darkBoard  | 316   |
| blue       | 297   |
| solid      | 265   |
| dark       | 241   |
| space1     | 211   |
| doubutsu   | 177   |
| gray       | 150   |

**Comment by CouchTomato87** [comment]
Awesome, thanks!

**Comment by CouchTomato87** [comment]
Also at some point, these names should be cleaned up and standardized lol

**Comment by WandererXII** [comment]
Yep, was thinking the same:D. Not gonna do it right now, because I already have to migrate a lot of things with the next update, but it's definitely happening after that.
