### ISSUE TITLE
Board refactor - use SVG grid

### ISSUE THREAD

**Issue by WandererXII** [WandererXII/lishogi#513]
Currently most of the boards we use are just PNGs. Unfortunately there are two problems.

1. PNG doesn't scale that well - it's especially visible with the grid lines. As shown here, some lines are smaller and blurry, while other lines scaled relatively well: 
![image](https://user-images.githubusercontent.com/43043181/154855689-1f9ff422-0b47-44ad-b255-6709113a9882.png)
Zoomed in here: 
![image](https://user-images.githubusercontent.com/43043181/154855796-3ceb6d41-8e79-4cde-b5ac-8c5152b24eb8.png)

2. Right now we have to support 9x9 and 5x5 boards, both in square and tall version. We will need to support more dimensions, with more variants. This is not really managable...

**Possible solution:**

I added dynamically generated SVG grid to [shogiground](https://github.com/WandererXII/shogiground). The grid can be styled with css and should scale much better than png. For themes that do not need the grid we can simply `display: none`.
This will also make it possible to have custom board backgrounds and grid colors:
![Alt Text](https://thumbs.gfycat.com/BelovedMildAlligatorsnappingturtle-size_restricted.gif)

**Comment by WandererXII** [comment]
I need these themes without the grid:
- [ ] wood1
- [ ] kaya-light
- [ ] space2
- [ ] space1
- [ ] Painting2
- [ ] Painting1
- [ ] oak
- [ ] Kinkaku
- [ ] kaya2
- [ ] kaya1

**Comment by CouchTomato87** [comment]
Would it be possible to make the lines thinner? There's something unsightly about thick board lines. Also sent you the rest of the images by DM

**Comment by WandererXII** [comment]
Sure, all that's needed is to change the `stroke-width` attribute. I will try getting the line thickness closer to the current boards.

**Comment by WandererXII** [comment]
Here it is with smaller stroke-width:
![image](https://user-images.githubusercontent.com/43043181/155009925-a7318d9b-8d73-442d-b4b7-e578eb182f48.png)
At this stroke-width, at some board widths the lines are blurry once again (look at the most left vertical line on the board), but it's still much better than with pngs.
Right now I am using `vector-effect: non-scaling-stroke`, to assure the line is `stroke-width` wide, but sometimes it still falls between two pixels and then anti-aliasing blurs it. To prevent anti-aliasing, I played with `shape-rendering: crispedges`, it works on firefox, but not on chrome.
I'm also probably remove square boards, supporting both versions seems unnecessary.

**Comment by WandererXII** [comment]
Clear lines achieved, but at what cost... Each square is a separate element. This also solves square highlights not aligning with the board. And perhaps I can also make pieces just classes of the squares they are occupying, so maybe it's better this way.
![image](https://user-images.githubusercontent.com/43043181/155921887-0b1598a8-4a7e-485a-9efd-3478356aee5d.png)

**Comment by CouchTomato87** [comment]
Looks good, but I'm not an expert on element efficiency lol
