### ISSUE TITLE
Computer opponent not moving

### ISSUE THREAD

**Issue by killerducky** [WandererXII/lishogi#514]
I tried to play the computer with handicap yesterday: https://lishogi.org/BJUvyEv5
And today: https://lishogi.org/moSKD3cg

Computer isn't moving.

**Comment by SparkCA** [comment]
Hi. I tried playing a 6-piece Handicap game against a bot and the computer isn't making a move. https://lishogi.org/9Mbu6G0pYVbT

**Comment by ddugovic** [comment]
Where is the "play computer with handicap" (or from position) button?  I'm not seeing it.

**Comment by WandererXII** [comment]
Should be _solved_ with the new shoginet. If not please comment.
