### ISSUE TITLE
Tsyoku shogi

### ISSUE THREAD

**Issue by konrad7890** [WandererXII/lishogi#518]
Na lishogi.org moze byc tayoku shogi zasady sa proste jest tylko 208 typow roznych figur plansza jest 36×36 jesli nie znacie zasad wpiszcie tayoku shogi w Wikipedia

**Comment by WandererXII** [comment]
While definitely interesting, 36x36 and 208 pieces is just too much:)
I would have to fit it all on current implementation and it would affect performance all over. 12x12 for chuushogi is the limit.
Thanks for the suggestion.
