### ISSUE TITLE
Bigsby emoji

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#52]
Replace https://github.com/WandererXII/lishogi/blob/master/public/images/emoji/horsey.png

**Comment by CouchTomato87** [comment]
Where is this used?

**Comment by timezombi** [comment]
@CouchTomato87 It's used wherever you can react with emoji. For example, the forums. This one has a bunch of the emoji: https://lishogi.org/forum/lishogi-feedback/bugs

At time of writing, 8 people have reacted with the horsey emoji!

**Comment by CouchTomato87** [comment]
Ah, so maybe we can do a shogi piece with a face?

**Comment by CouchTomato87** [comment]
![bigsby](https://user-images.githubusercontent.com/52322435/99907161-34b05a80-2ca9-11eb-96db-3f54bc5bfaaa.png)

Would this suffice?

**Comment by timezombi** [comment]
Is it possible to rename horsey.png to something more relevant without breaking a lot of stuff? That seems like the only thing holding back the ticket from being closed. The cartoon Bigsby emoji couch made has already been deployed to the production website!

**Comment by ddugovic** [comment]
Yeah, anyone could safely find and replace references to "horsey" with "bigsby" (or something else).  Possibly tags on existing forum posts would need to be updated.

**Comment by WandererXII** [comment]
Done replaced horsey with bigsby in the db and updated modules/forum https://github.com/WandererXII/lishogi/commit/d60ae19542191166b713011d7f0e6f1136d97a53
