### ISSUE TITLE
Cannot select pieces from hand (one king position)

### ISSUE THREAD

**Issue by killerducky** [WandererXII/lishogi#523]
https://lishogi.org/analysis/9/7k1/7sp/9/9/9/9/9/9_b_RBG_1
Drop B*11 Kx11 and now I cannot select the Rook or Gold from hand.
When I added another King it started working again.

Shogi Harbour found this on her stream:
https://clips.twitch.tv/CallousOnerousSeahorseDancingBanana-MxrEfHNeyCzlNNzo

**Comment by WandererXII** [comment]
Seems to be fixed after the update. Thanks for reporting!
