### ISSUE TITLE
For rated games use traditional rules

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#525]
81Dojo beautifully implements traditional rules and allows players to nifu, move into check, play other illegal piece drops, etc.  Traditional rules are strict and fair, putting players in control of their own destiny.

**Comment by karakoro** [comment]
I disagree.
I don't think strict rule-setting and the environment of lishogi are incompatible.
Users will be stressed when trying to play a lot of games because it is an arena tournament, just as lichess is not.

**Comment by ponponponn** [comment]
Absolutely not.
There is no benefit whatsoever, just stress for the user.
It doesn't match with the system of lishogi, which is a system to play a lot of games easily.

81Dojo is a very special site and its direction is opposite to that of lishogi, so I don't think it should be used as a reference.

**Comment by ddugovic** [comment]
I don't think we can "absolutely" rule out a developer's suggestion...

Although Lishogi is based upon the Lichess codebase, players on that site have made the same feature request (albeit in a different context).

The Lichess community is large and some of its members, especially those playing quick time controls, take advantage of (angle shoot) rules/features while also complaining about them.  The closer we can get to official rules, the better we can support a large community without suffering constant rules arguments.

**Comment by ponponponn** [comment]
I do not speak English. This is google translate. I apologize if I didn't word it right.

I certainly understand that there are diverse opinions. There may be no absolutes.
Some may say that the rules should be stricter, but I am sure that none of the major chess or shogi sites that are popular in the real world apply strict foul rules.
Please be cautious in your decision making. I am not a developer and I think we should respect the developer's decision.
However, this implementation could kill the potential of the site.
Please, please, please, please be prudent in your decision.

**Comment by ddugovic** [comment]
Thanks for sharing your ideas.  WandererXII is the main developer; I sometimes develop changes too.

I think for rated, serious games that it makes sense to follow the example set by JSA.

[FIDE (chess) recently changed their rules](https://chess.com/news/view/new-fide-laws-of-chess-for-blitz-rapid-still-not-perfect): now, a player who makes two illegal moves loses the game.  USCF rules are far more lenient, which causes many fierce arguments between tournament directors, players, coaches, parents, children, and adults.  Thankfully in chess common illegal moves (promoting a pawn to a pawn, moving with two hands, moving a piece to the wrong square) are unintentional, although sometimes intentional (moving into check) illegal moves are made too.

Popular chess sites were developed based upon old technologies/protocols which do not have a way to communicate illegal moves.  This omission causes errors when recording or publishing a game where illegal moves happened!  But also a chess player competing online has no opportunity to play online with tournament-like rules, even in rated games; the only way chess players can learn FIDE or USCF rules is to read the rule book, or to lose tournament games (or observe others who lose games) and hear tournament directors explain the loss.

I think it is reasonable to give players in rated games a strict experience so competitive players do not need to learn two sets of rules.

**Comment by WandererXII** [comment]
I agree it would just stress the users. I would prefer to go the way of overall friendliness over elitism.
