### ISSUE TITLE
Conceal player ratings

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#53]
Show player ranks (kyu and Dan) instead.

**Comment by WandererXII** [comment]
You mean instead of titles(GM, IM, FM...) or map elo rating ranges on certain ranks?

**Comment by ddugovic** [comment]
Ah... I think both:
* If a player has a professional title, show that (already implemented, although title options may need to be re-coded)
* Else map player ratings to amateur ranks

**Comment by timezombi** [comment]
I just want to point out that the user Shogi_Harbour (https://lishogi.org/@/Shogi_Harbour) is literally a Ladies Shogi Professional (Joryuu Kishi 1-kyu). I think she is the only person on the site that is titled at the moment.

For professional title, you may want to make a distinction between Pro and Lady Pro, but don't know how much you would want to refine it down further than that. Maybe there could be special titles for the winners of the European Shogi Championships?

**Comment by kleffa** [comment]
I think for female professionals lichess also had the woman master titles like WM WIM and WGM, so this system can be adjust to profesional titles, but not sure of kyu/Dan ranks

**Comment by karakoro** [comment]
The population of shogi is smaller than that of chess, and if you display even kyu/dan, individuals can be identified.
This is especially true in the case of former Apprentice Professionals' Association members.

Some streamers are former Apprentice Professionals' Association members but have not disclosed their detailed kyu/dan.

**Comment by ddugovic** [comment]
Sorry for my confusion; other shogi sites display both a rating and a "title" based upon the rating.
