### ISSUE TITLE
Mobile. Study paste kif

### ISSUE THREAD

**Issue by Little-Mage** [WandererXII/lishogi#534]
If you're in mobile and create a study, select the editor tab in chapter then it gets stuck in editor. Doesn't go to the other tabs. Same result if you switch your browser to display as desktop. It gets stuck in editor even if you close the browser and try again.
![Screenshot_20220502-093643](https://user-images.githubusercontent.com/55811361/166263279-0a2f9e3d-4b7c-4289-b11b-8f7c090facb1.png)

**Comment by Little-Mage** [comment]
Deleting cookies solves the issue but clicking editor tab will make it to get stuck again.

**Comment by WandererXII** [comment]
Does it still happen after the new update?
I can't seem to replicate it in BrowserStack now, so if it still happens let me know, what browser/device it is happening on.
Thanks!

**Comment by Little-Mage** [comment]
No, it got fixed thank you.
