### ISSUE TITLE
Feature Request: HTTP backup

### ISSUE THREAD

**Issue by KY246** [WandererXII/lishogi#535]
Hello, one of the computers that I have is unable to connect to websockets making lishogi unusable with the exception of the puzzles.
While I understand that this is a problem that few people experience, I was hoping that a HTTP fallback connection ould be implemented for lishogi at a later date, similar to how lichess doesn't require support for websockets.

**Comment by WandererXII** [comment]
Hello, I thought lichess also required websockets...
If anyone knows any details please point me there.

**Comment by KY246** [comment]
Sorry, it looks like lichess requires websockets, and I was just having strange computer issues on my end.
