### ISSUE TITLE
Promotion dialog for forced promotions

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#536]
A knight from 53 capturing a gold on 61 does not require a promotion dialog.

**Comment by WandererXII** [comment]
Do we want a promotion dialog for forced promotions? There isn't really any option.

**Comment by ddugovic** [comment]
No we don't; sorry for my brevity, that was my point:
![image](https://user-images.githubusercontent.com/1834123/176978058-077089da-323d-4000-9ca7-bae385de5da0.png)

**Comment by WandererXII** [comment]
Oh, sorry for misunderstanding. This will be fixed with new shogiground.
