### ISSUE TITLE
SVG pieces, 1kanji, cz-like guide

### ISSUE THREAD

**Issue by ddeo604** [WandererXII/lishogi#537]
Hi,
I wanted to contribute to lishogi/shogi community in some way.
I attempted to create an svg piece set but not sure how to proceed from here.

Proposing the addition of this piece set.
I made a quick html file to show it here with 3 different setups to see if it reads well enough:

https://ddeo604.github.io/sp/Engraved/

its 11:12.
it has a movement guide inspired by cz.
it is 1 kanji.
it is all svg.
**it is offset towards the player who owns the piece.** for clarity who owns which piece.
it is beveled 3d piece shape.
it is an engraved writing effect.
it has red promoted sides.
the pieces, line up on their bottom end.
the characters, line up on their bottom end.
the movement guides, line up except for the knight
it is lit from the top right with bottom left cast shadow.
it is about < 380kb for the whole folder.

Thank you for reading and considering.

**Comment by WandererXII** [comment]
Looks great. I would be happy to add them. What should the name be? 'Engraved' perhaps?

**Comment by ddeo604** [comment]
Thanks! I didn't think of a name actually, is changing its name later simple? Engraved for now is fine.

How do I deliver the files?
Is there a naming convention you want me to use?
Any tweaks you would like in particular?

So far I might have to edit the pawns (kanji feels too small) and lance (guide feels short) based on feedback I received though.

**Comment by WandererXII** [comment]
I can change the names later, but it's better to have the name now.
To deliver the files, just attach a zip here with the pieces. When pointed out I agree with the feedback, everything else looks good to me, we can always make tweaks later.
Example of the naming convention: https://github.com/WandererXII/lishogi/tree/master/public/piece/1Kanji_3D.
'0' for the pieces facing up and '1' for the pieces facing down. The rest is a shorthand of the Japanese piece name. If you are not familiar with that, feel free to leave 'pawn', etc. and I will rename them.

**Comment by ddeo604** [comment]
[Engraved CZ.zip](https://github.com/WandererXII/lishogi/files/9057665/Engraved.CZ.zip)

I think its in the correct naming convention.

before renamed files:
https://github.com/ddeo604/sp/tree/gh-pages/Engraved
in case you need to grab one due to missing or what not.

**Comment by WandererXII** [comment]
Thanks a lot! It will be live hopefully in a week or two.

**Comment by WandererXII** [comment]
It's live!
