### ISSUE TITLE
Bug: Simul produces Error when special characters are used for the Simul name.

### ISSUE THREAD

**Issue by timezombi** [WandererXII/lishogi#54]
When creating a Simul (https://lishogi.org/simul/new), an Error is produced whenever a special character is inputted into the Simul Name field. The error doesn't show up until after clicking the "Host A New Simul" button. After several broken attempts, the page even refuses to successfully make a Simul for even valid names!

Using alphanumeric characters, Japanese, and spaces seems to be okay, but using any special characters produces the error without any additional error message.

Either there should be additional JavaScript validation in place to warn/prevent users from making an invalid name or special characters should be allowed in a Simul name (perhaps with some limitations such as not consisting _entirely_ of special characters).

Example Error using an apostrophe:
![image](https://user-images.githubusercontent.com/600562/99653592-0f53f000-2a0e-11eb-9c8f-84e4f81f87e0.png)

**Comment by WandererXII** [comment]
Will look into it

**Comment by WandererXII** [comment]
The server checks if the characters are valid but returns just random error, I will change it to be more specific. As for the reason why afterwards you couldn't create even a simul with a valid name is because after it returns the error it unchecks the variant checkbox. Will try to change that.
