### ISSUE TITLE
Learn shogi "Out of Check" 10th problem: Two Pawns is allowed and correct. 将棋を学ぶ「王手を防ぐ」の10問目で二歩も正着になる。

### ISSUE THREAD

**Issue by wass88** [WandererXII/lishogi#567]
![image](https://user-images.githubusercontent.com/26019458/184835760-6e03642e-c766-4338-bfb2-cb2adb8e678c.png)

**Comment by WandererXII** [comment]
Thanks for reporting this, will be fixed today.
