### ISSUE TITLE
Drop sound twice

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#568]
**Exact URL where the bug happened**
https://lishogi.org/forum/lishogi-feedback/drop-sound-2-times

**Steps to reproduce the bug**
Smartphone, chrome
A sound is made twice when the piece drop.
Please fix.

スマートフォン、クローム
駒を打つ際に音が二度鳴ります。
修正よろしくお願いします。

**What did you expect to happen?**

**What happened instead?**

**Operating system and browser version**

**Comment by WandererXII** [comment]
If anyone knows how to reproduce, let me know.

**Comment by WandererXII** [comment]
https://github.com/WandererXII/lishogi/commit/2d215556aa307c2862b1c2bb9b072f58c15b4e09
