### ISSUE TITLE
Animation sometimes slow and/or stops completely on studies.

### ISSUE THREAD

**Issue by killerducky** [WandererXII/lishogi#571]
![image](https://user-images.githubusercontent.com/64080/184906184-90a7ee4b-e720-45b8-8562-c4a8e309c323.png)

On studies, sometimes the animation pauses before it is completed for it to show the comment. In the screen shot, I dragged the Gold from pocket and dropped it off-center on the square. Before the animation completes to center the piece, the tooltip interrupts with the message ("The sacrifice draws..."). 

This is not 100% repeatable. Also when it happens the entire board seems pretty laggy and slow to respond. Also when it happens and I click on pocket pieces, the green dots for legal drops do not appear.

**Comment by killerducky** [comment]
Also sometimes I cannot even move pieces on the board. For https://lishogi.org/study/4XssSDlR chapter 8, I sometimes cannot even click on my Rook on the board. It only happens when I use "Drag a piece" mode or "Either" mode.

**Comment by WandererXII** [comment]
Any errors in the console?, when this happens

**Comment by WandererXII** [comment]
Also chrome or firefox?

**Comment by killerducky** [comment]
Chrome and Edge. I got one error in console but not at the moment it's happening:

lishogi.analyse.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at c (lishogi.analyse.min.js:1:339)
    at Ve (lishogi.analyse.min.js:1:21260)
    at Be (lishogi.analyse.min.js:1:19090)
    at lishogi.analyse.min.js:1:17824
    at Ie (lishogi.analyse.min.js:1:18638)
    at Te (lishogi.analyse.min.js:1:17752)
    at Je (lishogi.analyse.min.js:1:21388)
    at Xe (lishogi.analyse.min.js:1:21559)
    at lishogi.analyse.min.js:1:21734

**Comment by WandererXII** [comment]
Thanks. Helped me replicate and find the cause, fix will be live tonight.

**Comment by sgagyn** [comment]
> Also sometimes I cannot even move pieces on the board. For https://lishogi.org/study/4XssSDlR chapter 8, I sometimes cannot even click on my Rook on the board. It only happens when I use "Drag a piece" mode or "Either" mode.

Exactly the place I couldn't proceed from! Thanks for being way ahead of me in reporting it

**Comment by WandererXII** [comment]
Fix is live.
