### ISSUE TITLE
Japanese speech for king move

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#575]
**Exact URL where the bug happened**
https://lishogi.org/tv

**Steps to reproduce the bug**
1. Set sound = speech
2. Set notation = Japanese
3. Set language = Japanese

**What did you expect to happen?**
Speech for all moves is in Japanese

**What happened instead?**
Speech for most moves is in Japanese, but speech for king moves is in English

**Operating system and browser version**
Windows 10 Edge latest

**Comment by WandererXII** [comment]
Thanks for finding these!
