### ISSUE TITLE
Intl Wooden 3D: Opponent sente king incorrectly rendered

### ISSUE THREAD

**Issue by CouchTomato87** [WandererXII/lishogi#584]
(https://github.com/WandererXII/lishogi/blob/master/public/piece/Intl_Wooden_3D/1GY.svg)

Something happened to this piece where most of the piece is missing. Did something happen during the refactoring to make the piece like this, and do I need to send in a new piece?

**Comment by WandererXII** [comment]
I think svgo is to blame, the same happened with some other updated kings, but missed this one. Sry, will be fixed.

**Comment by WandererXII** [comment]
After optimization with svgo: https://github.com/WandererXII/lishogi/blob/98d9923482531e655812364052ccf6fe4904a3da/public/piece/Intl_Wooden_3D/1GY.svg
Not sure why this happened. Only the new kings are affected. I will just use the unoptimized versions.
