### ISSUE TITLE
Arrows are messed up in old studies

### ISSUE THREAD

**Issue by killerducky** [WandererXII/lishogi#586]
https://lishogi.org/study/4XssSDlR
![image](https://user-images.githubusercontent.com/64080/186816058-4a1307d2-56d1-420c-b4d2-4a713c093166.png)

For example Chapter 1, play Silver 52. The arrows just show the tips, body of arrow is missing.

I was able to fix another study by redrawing the arrows, but can you automatically fix them?

**Comment by WandererXII** [comment]
Fix is live, thanks for reporting this.
