### ISSUE TITLE
Improve promotion arrows

### ISSUE THREAD

**Issue by WandererXII** [WandererXII/lishogi#589]
Currently when engine suggests a move involving promotion, the shapes reflect that by drawing the promoted piece at the arrow destination.
![promNice](https://user-images.githubusercontent.com/43043181/187096392-e75c815b-9cfb-4662-8912-e6c29d5b823d.png)
That looks nice. But it becomes hard to read, if at the destination is a piece. One can hardly make out what's below the promoted piece.
![promNotNice](https://user-images.githubusercontent.com/43043181/187096415-7234b288-dcdd-4f70-8229-fe15913ffd04.png)

What can be done:
- Use different arrow color for promotions - not intuitive
- Draw some kind of a custom svg shape, somewhere on the destination square, this shouldn't conflict with glyphs.

**Comment by ddugovic** [comment]
I agree that the destination square looks a bit busy (whether or not it is originally occupied - I actually disagree about the arrow in the first diagram).

Perhaps an alternative would be to show an indicator on the path to the destination square, a la Watts' _The Usborne Guide to Advanced Chess_ which looked something like:
![image](https://user-images.githubusercontent.com/1834123/188330166-63e08eae-5a6c-4173-be8f-7e17bae49cdc.png)

Obviously, we're not interesting in numbers to indicate move ordering, but some indicator along the path might work.

**Comment by CouchTomato87** [comment]
A piece itself may get a bit congested too, for example a one step promotion (common) or a knight promoting by hopping over a piece.  What about a plus symbol along the arrow?

**Comment by TheYoBots** [comment]
https://lishogi.org/forum/lishogi-feedback/pieces-do-not-appear-on-the-board-when-right-clicking
> Previously, if you right-clicked on a piece on the piece stand and then right-clicked on any square on the board, a transparent piece and a green circle would appear on the square you clicked on. Currently, only the green circle is displayed when the same operation is performed, but the transparent piece is no longer displayed.
I don't know if the operating procedure has changed, but I reported it because a useful function is no longer available.
>
> それまでは、駒台の駒を右クリックしてから盤上の任意のマスを右クリックすると、クリックしたマスに透けた駒と緑色の丸が表示される機能がありました。現在同様の操作を行っても緑色の丸だけが表示されるのみで、透けた駒が表示されなくなりました。
操作方法が変わったのかはわかりませんが、便利な機能が使えなくなったので報告しました。

**Comment by WandererXII** [comment]
> https://lishogi.org/forum/lishogi-feedback/pieces-do-not-appear-on-the-board-when-right-clicking
> 
> > Previously, if you right-clicked on a piece on the piece stand and then right-clicked on any square on the board, a transparent piece and a green circle would appear on the square you clicked on. Currently, only the green circle is displayed when the same operation is performed, but the transparent piece is no longer displayed.
> > I don't know if the operating procedure has changed, but I reported it because a useful function is no longer available.
> > それまでは、駒台の駒を右クリックしてから盤上の任意のマスを右クリックすると、クリックしたマスに透けた駒と緑色の丸が表示される機能がありました。現在同様の操作を行っても緑色の丸だけが表示されるのみで、透けた駒が表示されなくなりました。
> > 操作方法が変わったのかはわかりませんが、便利な機能が使えなくなったので報告しました。

That functionality was replaced by arrows from hand to board. But it's still possible to do that, by middle clicking the piece in hand (small circle will appear next to the piece) and then you can just like previously draw it on the board by right clicking.

**Comment by WandererXII** [comment]
> I agree that the destination square looks a bit busy (whether or not it is originally occupied - I actually disagree about the arrow in the first diagram).
> 
> Perhaps an alternative would be to show an indicator on the path to the destination square, a la Watts' _The Usborne Guide to Advanced Chess_

> A piece itself may get a bit congested too, for example a one step promotion (common) or a knight promoting by hopping over a piece. What about a plus symbol along the arrow?

I will try something like that, since css pseudo elements don't work with inlined svgs, I will have to add that functionality directly to shogiground. I will try some options and post them here.

**Comment by WandererXII** [comment]
Posting some options I tried, even the ones that don't look that good, maybe you will think of something.

1. Flip the piece
![v11](https://user-images.githubusercontent.com/43043181/194729354-48e9eba3-9d4d-4a4b-8ced-c91d7e55ebc5.png)
![v12](https://user-images.githubusercontent.com/43043181/194729357-f7fed016-cdbe-43f1-a715-2c2fbbf3bcb0.png)
![v13](https://user-images.githubusercontent.com/43043181/194729358-35f2b164-f1f1-4e3f-9edb-163a17976b18.png)
Looks good on its own, but with an arrow or piece on the same square, it's doesn't look good.

2. Separate symbol (plus)
![v21](https://user-images.githubusercontent.com/43043181/194729377-3a1d010e-6b1d-4be8-b702-14bf6c6a6e15.png)
![v22](https://user-images.githubusercontent.com/43043181/194729382-74b17f79-d694-4f37-bcc7-77d49d925547.png)
Looks kinda dumb, not really enough space to have both the arrowhead and another symbol on the same square.

3. Arrowhead with a symbol (plus)
![v31](https://user-images.githubusercontent.com/43043181/194729456-bd5a3a76-5142-4d5a-97b7-c9a20475c222.png)
![v32](https://user-images.githubusercontent.com/43043181/194729459-3e4b24e7-86c5-4c1c-b31f-354073118560.png)
Kinda neat, but hard to see when a piece is behind it.

4. Symbol along the arrow line
![v41](https://user-images.githubusercontent.com/43043181/194729502-18adefe8-35c5-44ef-b4e6-d3411c11062c.png)
![v42](https://user-images.githubusercontent.com/43043181/194729504-2e361a0e-db78-4c19-9341-9be34b154fae.png)
![v43](https://user-images.githubusercontent.com/43043181/194729527-eb4a484f-a7a8-4576-a4f2-c8ad74b8c466.png)
Probably the best option, the circle and the sign can be any color, but I think the circle being the same color as the arrow looks the best. Not sure where to position the circle if the arrow is short (last two images, the first one is closer to the head).

**Comment by CouchTomato87** [comment]
> Posting some options I tried, even the ones that don't look that good, maybe you will think of something.
> 
> 1. Flip the piece
>    ![v11](https://user-images.githubusercontent.com/43043181/194729354-48e9eba3-9d4d-4a4b-8ced-c91d7e55ebc5.png)
>    ![v12](https://user-images.githubusercontent.com/43043181/194729357-f7fed016-cdbe-43f1-a715-2c2fbbf3bcb0.png)
>    ![v13](https://user-images.githubusercontent.com/43043181/194729358-35f2b164-f1f1-4e3f-9edb-163a17976b18.png)
>    Looks good on its own, but with an arrow or piece on the same square, it's doesn't look good.
> 2. Separate symbol (plus)
>    ![v21](https://user-images.githubusercontent.com/43043181/194729377-3a1d010e-6b1d-4be8-b702-14bf6c6a6e15.png)
>    ![v22](https://user-images.githubusercontent.com/43043181/194729382-74b17f79-d694-4f37-bcc7-77d49d925547.png)
>    Looks kinda dumb, not really enough space to have both the arrowhead and another symbol on the same square.
> 3. Arrowhead with a symbol (plus)
>    ![v31](https://user-images.githubusercontent.com/43043181/194729456-bd5a3a76-5142-4d5a-97b7-c9a20475c222.png)
>    ![v32](https://user-images.githubusercontent.com/43043181/194729459-3e4b24e7-86c5-4c1c-b31f-354073118560.png)
>    Kinda neat, but hard to see when a piece is behind it.
> 4. Symbol along the arrow line
>    ![v41](https://user-images.githubusercontent.com/43043181/194729502-18adefe8-35c5-44ef-b4e6-d3411c11062c.png)
>    ![v42](https://user-images.githubusercontent.com/43043181/194729504-2e361a0e-db78-4c19-9341-9be34b154fae.png)
>    ![v43](https://user-images.githubusercontent.com/43043181/194729527-eb4a484f-a7a8-4576-a4f2-c8ad74b8c466.png)
>    Probably the best option, the circle and the sign can be any color, but I think the circle being the same color as the arrow looks the best. Not sure where to position the circle if the arrow is short (last two images, the first one is closer to the head).

How is the last example for #1 even possible? lol

Anyways, I agree, I like the last one the best. Followed by #1.

**Comment by WandererXII** [comment]
Done!
