### ISSUE TITLE
Kings for sente and gote 

### ISSUE THREAD

**Issue by CouchTomato87** [WandererXII/lishogi#59]
Right now, the kings both show the same image. They should be differentiated (Pychess is able to do this), otherwise it makes it even harder to tell who's who. In other words, we need to use the 0GY piece with 1OU by default, or 1OU with 0GY for a board flip

This was also mentioned in the pieces discussion, but I think it's a separate issue.

**Comment by WandererXII** [comment]
Done, black now has GY white OU, might need to force refresh (ctrl f5) to see changes. If something's wrong open a new issue. Thanks
