### ISSUE TITLE
Premoves consume time

### ISSUE THREAD

**Issue by TheYoBots** [WandererXII/lishogi#596]
**Exact URL where the bug happened**
Any game where you can make a premove.

**Steps to reproduce the bug**
Start a game and then during the game make a premove. See movetime at the end of the game to notice time lost (or simply change clock to milliseconds).

**What did you expect to happen?**
Premove must be made without time wasted.

**What happened instead?**
Premove was made and a slight amount of time gets wasted (around 0.3 seconds).

**Operating system and browser version**
Possibly any. Noticed in PC.

**Related Forum Post**
https://lishogi.org/forum/lishogi-feedback/even-premove-consumes-time
> Thank you for the last major update.
I feel it has made it very easy to use.
There is one major problem: premove now consumes time on smartphones. It seems to consume about 0.3 seconds.
On a PC, this does not seem to be a problem.
I don't know if this is unavoidable or if it can be improved, but if it is possible, I would like you to improve it because one of the advantages of lishogi is that you can play shogi in a very short time, and if time is consumed even in premove, the advantage is lost.
>
> Please consider it.
(DeepL translation)
>
> 前回の大規模なアップデートありがとうございます。
大変利用しやすくなったと感じています。
一点、大きな問題がありまして、スマートフォン上でpremoveでも時間を消費するようになりました。大体0.3秒程度消費するようです。
PC上では問題ないように思われます。
これがやむを得ないことなのか、改善できることなのかわかりませんが、もし可能であれば改善して頂きたいです。lishogiは非常に短時間の将棋が指せることもメリットの一つであり、premoveでも時間が消費されてしまうとその良さが失われてしまいますので。
御一考のほどよろしくお願い致します。

**Comment by ddugovic** [comment]
Do you observe this with Windows (or Linux) + a Chromium-based browser (e.g. Edge, Chrome, Vivaldi)?

**Comment by TheYoBots** [comment]
> Do you observe this with Windows (or Linux) + a Chromium-based browser (e.g. Edge, Chrome, Vivaldi)?

Windows + chrome

**Comment by ddugovic** [comment]
Thanks, I too confirm this bug, even when playing with increment.

scalashogi tests look correct and are passing, therefore next I am looking at:
https://github.com/WandererXII/lishogi/blob/c896d3ac95d9110ef573e68488fe69c4a465be9f/modules/game/src/main/Game.scala#L798-L810

which differs from lila:
https://github.com/lichess-org/lila/blob/96755f3cbc03c08cada85543427e05a8cec08cc7/modules/game/src/main/Game.scala#L847-L848

The difference is a new member in `Clock.scala` which I will attempt to remove and see if I can reimplement some other way:
https://github.com/WandererXII/scalashogi/blob/9336875985a1f6fa393a9fd1566d671321ab9361/src/main/scala/Clock.scala#L177

**Comment by ddugovic** [comment]
After trial & error on my local server where my latency is near-zero so it's difficult to test... I wonder, maybe all this logic is correct however latency might be misreported or something.

**Comment by ddugovic** [comment]
I used `.pp` in `Clock.scala` to log lag compensation, then log move time (playing against myself):
```
diff --git a/src/main/scala/Clock.scala b/src/main/scala/Clock.scala
index 772f7e7..7f35188 100755
--- a/src/main/scala/Clock.scala
+++ b/src/main/scala/Clock.scala
@@ -96,7 +96,7 @@ case class Clock(
         val player              = players(color)
         val remaining           = player.remaining
         val (lagComp, lagTrack) = player.lag.onMove(lag)
-        val moveTime            = (elapsed - lagComp) nonNeg
+        val moveTime            = (elapsed - lagComp.pp).pp nonNeg

Sep 25 12:51:35 dugovic-host lila[114504]: Centis(0) <-- zero lagComp
Sep 25 12:51:35 dugovic-host lila[114504]: Centis(266)
Sep 25 12:51:35 dugovic-host lila[114504]: Centis(0) <-- zero lagComp
Sep 25 12:51:35 dugovic-host lila[114504]: Centis(2)
Sep 25 12:51:38 dugovic-host lila[114504]: Centis(0) <-- zero lagComp
Sep 25 12:51:38 dugovic-host lila[114504]: Centis(283)
Sep 25 12:51:38 dugovic-host lila[114504]: Centis(0) <-- zero lagComp
Sep 25 12:51:38 dugovic-host lila[114504]: Centis(3)
Sep 25 12:51:41 dugovic-host lila[114504]: Centis(0) <-- zero lagComp
Sep 25 12:51:41 dugovic-host lila[114504]: Centis(280)
```

**Comment by ddugovic** [comment]
6.5 hours into my coding livestream, I found the root cause and submit a PR.
