### ISSUE TITLE
In-browser engine analysis is broken in some positions

### ISSUE THREAD

**Issue by procion1302** [WandererXII/lishogi#606]
![image_2022-10-18_204827530](https://user-images.githubusercontent.com/59869948/196506446-8d63570c-73c5-4314-8902-031701a44165.png)
![Capture](https://user-images.githubusercontent.com/59869948/196503506-473688ec-632d-4eeb-b14f-cf2f6efbbfe9.PNG)

**Exact URL where the bug happened**
https://lishogi.org/analysis/standard/7nl/5s1%2BB1/p2ppp1pp/2p2lp2/7P1/1%2BR7/P2LPPP1P/kg2K1Sr1/N1G2G1NL_w_S2Pbgsn2p_74

also
https://lishogi.org/analysis/standard/7nl/5s3/p2pp2pp/2p2pp2/7P1/1%2BR7/P2LPPP1P/kg2K1Sr1/N4G1NL_b_GSL2P2bgsn2p_75

**Steps to reproduce the bug**
Enable infinite analysis in local browser

**What did you expect to happen?**
Analysis progressing with gradually increasing depth

**What happened instead?**
Analysis stops increasing depth almost immediately. Some interface options become irresponsive (can open analysis options but can't close it back). 
 In-browser console gives the repeating error "Uncaught TypeError: Cannot use 'in' operator to search for 'role' in undefined".

**Operating system and browser version**
Windows 10, Opera Version:91.0.4516.65. Also encountered the same error in the latest Chrome on Mac OS

**Comment by WandererXII** [comment]
Thanks for reporting this, I'll look into it.

**Comment by WandererXII** [comment]
The fix is live now, the issue was that YaneuraOu was sending "rep_draw" and we tried parsing it as a move.
