### ISSUE TITLE
A non-contiguous check sennichite was judged as an illegal move.

### ISSUE THREAD

**Issue by killerducky** [WandererXII/lishogi#610]
Just copying this issue I saw in the lishogi forum:

https://lishogi.org/forum/lishogi-feedback/a-non-contiguous-check-sennichite-was-judged-as-an-illegal-move

**Comment by WandererXII** [comment]
https://github.com/WandererXII/scalashogi/commit/2299ae77e1dc7528fe97caa6093e7d25048a980e but not deployed yet. Thanks for posting the issue here btw.

**Comment by WandererXII** [comment]
Done
