### ISSUE TITLE
Bug in which a draw is determined when stale mate is used.

### ISSUE THREAD

**Issue by Atelier-Mirai** [WandererXII/lishogi#612]
**Exact URL where the bug happened**
https://lishogi.org/OlvgRxj2LHy2
https://lishogi.org/FcI4w3cvqU1m

**Steps to reproduce the bug**
Steal mate by pawn, judged as a "draw" instead of a "win".

**What did you expect to happen?**
It should be a win, not a draw.

**What happened instead?**
It was ruled a draw, not a win.
The result of the game is a draw, please correct it to a win.

**Operating system and browser version**
macOS 13.0.1
Firefox 107.0.1

![ss 0004-12-10 午後8 51 59](https://user-images.githubusercontent.com/6257661/206854486-745c3073-eb44-40bd-95bf-ffb95406de2e.png)
![ss 0004-12-10 午後8 51 39](https://user-images.githubusercontent.com/6257661/206854496-64446472-d135-474d-86f0-3cd20254dfc8.png)

**Comment by Atelier-Mirai** [comment]
> Hello, thanks for reporting this. It says that you timed out, was that the case? The server apparently didn't receive the moves you indicated with the red arrows.

Why didn't the server receive my move? 

I have played about 1000 games and only these two games were declared draws.

The only possibilities are
if (steal mate && pawn not promoted) {
  Server does not receive incoming moves
  the game was declared a tie
} else {
  win decision
}

I was wondering if this was the case, so I contacted you.
Please continue your investigation.
Thank you in advance.

**Comment by WandererXII** [comment]
Closed in favor of #614, since the underlying issue is the same, but #614 is a clearer example.
