### ISSUE TITLE
YaneuraOu analysis engine load error

### ISSUE THREAD

**Issue by Anfid** [WandererXII/lishogi#615]
Hello, there seems to be an issue with YaneuraOu engine in Safari browser and on mobile Apple devices.

#585 is similar, but it seems that the underlying problem is different, hence separate issue.

**Exact URL where the bug happened**

https://lishogi.org/analysis with any uncached in the cloud move.
Alternatively, any post-game analysis.

**Steps to reproduce the bug**

Try to analyze any board position in local browser on one of the faulty device/browser combinations listed below.

**What did you expect to happen?**

Board position analysis is performed correctly in local browser, player advantage and recommended moves are displayed.

**What happened instead?**

"Loading engine..." message is shown indefinitely, regardless of engine settings (CPUs/Memory).
<img width="466" alt="image" src="https://user-images.githubusercontent.com/19424344/209178693-2a4ab01a-40c8-48ad-b1d1-326c093ac30c.png">

Following error is reported in the console on page refresh

Screenshot from MacBook M1 Pro, Safari
<img width="734" alt="image" src="https://user-images.githubusercontent.com/19424344/209179383-bfcfabc0-6de8-434e-af45-0ca7568c8a78.png">

Screenshot from iPad Air 5, Chrome
![IMG_09CB5F600095-1 2](https://user-images.githubusercontent.com/19424344/209186613-5fbf5530-d06c-4ef2-859f-18ee5479968c.jpeg)

**Operating system and browser version**

On the surface this issue seems to only affect Safari browser or mobile Apple device users, regardless of browser.

Following device/browser combinations were tested:

| Device \ Browser | Safari | Chrome | Firefox |
|-|-|-|-|
| Apple MacBook Pro 2021 (M1) | :x: | :white_check_mark: | :grey_question: |
| Apple MacBook Pro 2013 (intel) | :x: | :white_check_mark: | :grey_question: |
| Apple iPad Air 5 | :x: | :x: | :grey_question: |
| Apple iPhone 14 Pro | :x: | :x: | :grey_question: |
| Multiple Windows machines | N/A | :white_check_mark: | :white_check_mark: |
| Samsung S22 Ultra | N/A | :white_check_mark: | :white_check_mark: |

Let me know if there's any other info you need or if you want me to test same issue on debug build for more detailed logs. I might also be able to provide some help with WASM if necessary, given some instructions, but I'm not familiar with JS/TS.

**Comment by WandererXII** [comment]
Hello, thanks a lot for taking the time to investigate this and report it.
The repository for the engine we use is unfortunately archived - https://github.com/mizar/YaneuraOu.wasm. I'm not very familiar with WASM, but before the issues is resolved within the engine (if possible), it's probably best to disable NNUE on these devices/browsers.
Currently for NNUE we validate only these instructions: i32x4.dot_i16x8_s and i32x4.trunc_sat_f64x2_u_zero, which is probably wrong.
Does this - https://lab.mzr.jp/yowasm/selfplay.html - work for you? Or at least does it tell you it's not supported instead of crashing?

**Comment by Anfid** [comment]
The final link throws an alert with the following text:
```Your browser is not supported. {{ crossOriginIsolated: true }} {{ WebAssembly validation failed }} For more information, please take a look at https://github.com/yaneurao/YaneuraOu/.```

So at the very least it can detect that Safari doesn't support it. Just to confirm behavior aligns with the reported issue, I also checked Chrome on macOS and iOS, and it seems consistent with the table I posted above.

After digging a bit into the WASM SIMD support in browsers, it seems that Apple themselves may update browsers to support it in the future, but there's no timeline nor guarantee. Here's the link that displays current status, but it only seems to cover desktop browsers: https://webassembly.org/roadmap/ (Fixed-width SIMD row).

What puzzles me the most is lack of WASM SIMD support on M1 tablet in Chrome, because it's the browser that seems to support it across the board (macOS, Android), but only falls short on mobile Apple devices specifically.

So if I understand the issue correctly, I only see 2 solutions for it. Either waiting for browser developers to implement WASM SIMD support and improving error report or forking the engine and trying to implement fallback instructions in case SIMD is not supported. Latter doesn't seem like a productive time use, given that it may be deprecated the moment support is implemented in the browser.

**Comment by WandererXII** [comment]
> So at the very least it can detect that Safari doesn't support it. Just to confirm behavior aligns with the reported issue, I also checked Chrome on macOS and iOS, and it seems consistent with the table I posted above.

I added the same validation as the link I posted to lishogi, so lishogi should now detect the fact, that safari is not supported and use Fairy engine instead. Hopefully that's the case.

> What puzzles me the most is lack of WASM SIMD support on M1 tablet in Chrome, because it's the browser that seems to support it across the board (macOS, Android), but only falls short on mobile Apple devices specifically.

I'm not sure about M1 ipads, but chrome on iOS is just safari with a skin and google sync, so that's probably why - apple being apple.

> So if I understand the issue correctly, I only see 2 solutions for it. Either waiting for browser developers to implement WASM SIMD support and improving error report or forking the engine and trying to implement fallback instructions in case SIMD is not supported. Latter doesn't seem like a productive time use, given that it may be deprecated the moment support is implemented in the browser.

I agree, it's probably not worth it to spend a lot of time to develop a version that would work on safari, when they may add support for it later.

**Comment by Anfid** [comment]
> I'm not sure about M1 ipads, but chrome on iOS is just safari with a skin and google sync, so that's probably why - apple being apple.

Oh, that's interesting, never knew that.

Okay, thank you for your time. Let's hope Apple adds support for it sooner, rather than later. Feel free to close this issue whenever you see fit.

**Comment by Anfid** [comment]
For the record: Safari now supports WASM SIMD as of 16.4, I've tested YaneuraOu analysis on both MacBook Pro 2021 and iPad Air 5 and it works now. This fully concludes and resolves the original issue.
