### ISSUE TITLE
Analysis mode on mobile makes board render poorly and vary in size

### ISSUE THREAD

**Issue by awan1** [WandererXII/lishogi#617]
Cross-post from https://lishogi.org/forum/lishogi-feedback/analysis-mode-on-mobile-makes-board-render-poorly-and-vary-in-size

When I enable analysis mode on mobile (Android, Chrome), the board is no longer constrained to the mobile viewport and becomes too large to use. It also flickers in size.

I'm not sure how this works, but if a mobile screen ratio is detected, maybe the UI elements (board, eval bar, nav tree) could be fixed in size to the viewport width to prevent this.

My best guess is that the green eval progress bar is not assigned a viewport-related width.

**Comment by WandererXII** [comment]
Thanks for reporting this!

**Comment by awan1** [comment]
Oh my goodness thank you so much for fixing this!! Made my day :)
