### ISSUE TITLE
Piece highlight not working for specific pieces on checkered board

### ISSUE THREAD

**Issue by CouchTomato87** [WandererXII/lishogi#619]
https://lishogi.org/dQS8K1iCFYUs (Move 9)

![image](https://user-images.githubusercontent.com/52322435/209869505-aaa674bc-7dae-4eaf-a055-77f4bc8efc4e.png)

In this game of Chu Shogi (not sure if this happens in normal shogi), for some reason only the PHOENIX when moving diagonally and only on the CHECKERED boards (either of them) does not highlight the squares. When I change to a noncheckered board, there's no issue.

This is using Chrome on WIndows.

**Comment by CouchTomato87** [comment]
https://lishogi.org/FZ3e0xR3OnD6 Reproduced with the silver here on move 11. Only the dark square is not highlighted. It's possible that this only involves dark squares since the silver moved from a light square.

**Comment by WandererXII** [comment]
Thanks for reporting it, the css that creates the checkered boards is a bit messy, I will have to rewrite that.

**Comment by CouchTomato87** [comment]
Sounds good. I've come to realize that checkered boards are vastly superior to the original shogi board when it comes to chu shogi lol

**Comment by CouchTomato87** [comment]
I didn't want to open up a whole new topic for this, but I just realized that the 1_PROMOTEDSILVER piece for the internationalized set is incorrect. I'm surprised it was only one piece out of 80 of these! The corrected one is below:

![1_PROMOTEDSILVER](https://user-images.githubusercontent.com/52322435/210123711-77fd3621-c07e-47a4-a9d9-a6293824ac9d.svg)
