### ISSUE TITLE
Lion-move premove

### ISSUE THREAD

**Issue by CouchTomato87** [WandererXII/lishogi#620]
This is via Tepin:

"defending a piece attacked by a lion with a premove, makes the lion attack only once, and cannot retreat"

He shares a video here where it looks like it's an eagle rather than lion doing the premove.
[bandicam_2022-12-29_14-13-21-951.zip](https://github.com/WandererXII/lishogi/files/10319825/bandicam_2022-12-29_14-13-21-951.zip)

**Comment by WandererXII** [comment]
It's a visual bug that occurs only on 1a square. Refreshing the game reveals the lion/eagle/falcon did retreat. I will push the fix later today. Thanks for reporting it here!
