### ISSUE TITLE
Chu Shogi Internationalized Black and White set

### ISSUE THREAD

**Issue by CouchTomato87** [WandererXII/lishogi#622]
[Chuu_Intl_BnW.zip](https://github.com/WandererXII/lishogi/files/10327782/Chuu_Intl_BnW.zip)

Finally finished this set. I followed the convention for the other black and white set... but in this case, the "-1" makes the pieces WHITE instead of black, as I believe sente should still be black.

Regarding the kings, I kept the KING and TAMA designations used in the monochrome sets, as I wasn't sure how you'd want that. 

I also mentioned this in another thread, but will also put it here since it's more related... the 1_proomotedsilver piece in the internationalized set was unfortunately incorrectly colored, and I fixed it below:

![1_PROMOTEDSILVER](https://user-images.githubusercontent.com/52322435/210151942-2d4785a0-951b-4d6d-b87d-fc67d32d6f0e.svg)

**Comment by WandererXII** [comment]
Really nice, will be up within few days when I update the server. Thanks!

**Comment by WandererXII** [comment]
It's live, looks great on the board.
But prince was missing, so I used king instead for now.

**Comment by CouchTomato87** [comment]
Ahhh! How careless of me! Here's the prince:

[PRINCE.zip](https://github.com/WandererXII/lishogi/files/10329317/PRINCE.zip)

**Comment by WandererXII** [comment]
Thanks, fixed version is live. Might take a while to propagate tho.

**Comment by CouchTomato87** [comment]
Hmm doesn't seem to have propagated?

**Comment by WandererXII** [comment]
Once cdn picks it up, it takes a while, but I purged it now, so force refresh should do the work. I could've just changed asset version, but whatever...
