### ISSUE TITLE
New piece set

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [WandererXII/lishogi#638]
<img width="130" alt="ShogiGoteKing" src="https://user-images.githubusercontent.com/101206332/221014773-ad5097ba-dd78-4540-b0f0-5498e5e4b20f.png">
<img width="130" alt="ShogiSenteKing" src="https://user-images.githubusercontent.com/101206332/221014803-2874e48b-c60a-4b83-a0f3-d616aa149730.png">
<img width="130" alt="ShogiGoteGold" src="https://user-images.githubusercontent.com/101206332/221014832-10329cd7-9341-4397-9320-31aa8ccf7145.png">
<img width="130" alt="ShogiSenteGold" src="https://user-images.githubusercontent.com/101206332/221014875-47d914d9-0c84-4b51-9706-14c0d09923ea.png">
<img width="130" alt="ShogiGoteSilver" src="https://user-images.githubusercontent.com/101206332/221014923-cd20424a-204d-43f5-86db-218755e34ab1.png">
<img width="130" alt="ShogiSenteSilver" src="https://user-images.githubusercontent.com/101206332/221014967-7a074304-1b46-43a9-bfa6-a8c2c35e48dc.png">
<img width="130" alt="ShogiGoteProSilver" src="https://user-images.githubusercontent.com/101206332/221015007-26b70657-e71e-4320-a355-45d6064e8ccd.png">
<img width="130" alt="ShogiSenteProSilver" src="https://user-images.githubusercontent.com/101206332/221015105-cba7c01c-96dc-4083-b635-d1cfde703479.png">
<img width="130" alt="ShogiGoteRook" src="https://user-images.githubusercontent.com/101206332/221015140-9016eed4-fe58-4f03-88dc-a6dbf32e7907.png">
<img width="130" alt="ShogiSenteRook" src="https://user-images.githubusercontent.com/101206332/221015169-6eca83f2-6887-4003-b7e4-3ddac4c42765.png">
<img width="130" alt="ShogiGoteHyperrook" src="https://user-images.githubusercontent.com/101206332/221015462-e1f8eada-e330-4556-9adc-5206d778a5a9.png">
<img width="130"  alt="ShogiSenteHyperrook" src="https://user-images.githubusercontent.com/101206332/221015215-86a45f23-709f-4ad6-a9e5-0d9252b81897.png">
<img width="130" alt="ShogiGoteBishop" src="https://user-images.githubusercontent.com/101206332/221015283-5d4ec3e9-e174-4781-8bf4-0daa2f6d794f.png">
<img width="130" alt="ShogiSenteBishop" src="https://user-images.githubusercontent.com/101206332/221015302-8e3f60bf-f055-4f62-8055-edcab47f7e76.png">
<img width="130" alt="ShogiGoteUltrabishop" src="https://user-images.githubusercontent.com/101206332/221015330-c7ff5a66-c9aa-496d-86b4-a4c0583fd9bf.png">
<img width="130" alt="ShogiSenteUltrabishop" src="https://user-images.githubusercontent.com/101206332/221015363-5f4a05a6-f905-435c-a05f-dc91bf64329a.png">
<img width="130" alt="ShogiGoteLance" src="https://user-images.githubusercontent.com/101206332/221015599-cf767b48-8b5c-42f4-a978-d470c54640a8.png">
<img width="130" alt="ShogiSenteLance" src="https://user-images.githubusercontent.com/101206332/221015640-ecded34f-09b3-476d-852f-1d0026f48abc.png">
<img width="130" alt="ShogiGoteProLance" src="https://user-images.githubusercontent.com/101206332/221015673-6a5e8162-b32f-49df-bb72-234ff9424670.png">
<img width="130" alt="ShogiSenteProLance" src="https://user-images.githubusercontent.com/101206332/221015700-fee983f2-ca8a-4bae-bcd5-8c095effc10e.png">
<img width="130" alt="ShogiGoteHorse" src="https://user-images.githubusercontent.com/101206332/221015728-10a01892-4df4-4eb9-b989-e65557d38610.png">
<img width="130" alt="ShogiSenteHorse" src="https://user-images.githubusercontent.com/101206332/221015766-0da763f0-ef35-43b4-8aa4-ede485acd0a0.png">
<img width="130" alt="ShogiGoteProHorse" src="https://user-images.githubusercontent.com/101206332/221015789-4f84ad6a-bfac-4382-aac7-3b8cbf9cc08b.png">
<img width="130" alt="ShogiSenteProHorse" src="https://user-images.githubusercontent.com/101206332/221015804-0805f58c-187f-4218-9dd3-009e43a275a3.png">
<img width="130" alt="ShogiGotePawn" src="https://user-images.githubusercontent.com/101206332/221015824-bbeeb77d-1ae0-4400-b7dc-1201ff15f06d.png">
<img width="130" alt="ShogiSentePawn" src="https://user-images.githubusercontent.com/101206332/221015833-394c15f1-ba76-4466-b081-e2a637d59aa3.png">
Joyful. Pawns are turning into yellow (original) Gold image.

**Comment by WandererXII** [comment]
These look really fun! Thanks a lot!
Could you please write what each piece is, just to be sure (something like 1. king, 2. gold, 3.silver).
Also PNG is gonna work fine, but SVG scales better... Not sure if you have that format?
How do you wish to be credited and what license should apply?

I will add them together with the next update, hopefully within a month.

Thanks!

**Comment by TheYoBots** [comment]
Since it was the topic of adding a new piece set, Hachu source has a simple kanji (I think it should be called that?) set too.

https://salsa.debian.org/debian/hachu/-/tree/master/svg

**Comment by Rechefiltr-is-Fire** [comment]
Thank you, 1. king, 2. gold 3. silver 4. pro silver 5. rook 6. hyperrook 7. bishop 8. ultrabishop 9. lance 10. pro lance 11. horse 12. pro horse 13. pawn (pro pawn is 2. gold)

**Comment by WandererXII** [comment]
The pieces are live, thanks a lot for submitting them!
