### ISSUE TITLE
Impasse

### ISSUE THREAD

**Issue by Little-Mage** [WandererXII/lishogi#639]
How does impasse work I clicked impasse in this game and nothing happened. Do u need to click on it twice?
https://lishogi.org/nmyjnLLg

**Comment by WandererXII** [comment]
Impasse triggers automatically. Did you meet all the requirements for impasse?

- Your king is not in check
- Your king has entered opponent's territory
- You have 10 other pieces in the opponent's territory
- You have 28 points in total if you are sente (black), or 27 points if you are gote (white)

From looking at the last position I think you have only 9 piece (not counting king) in opponent's territory. Did the counter when you click impasse showed something else?

**Comment by Little-Mage** [comment]
i didnt know 10 entered were needed.
