### ISSUE TITLE
Lion move not implemented correctly (tsukegui not allowed).

### ISSUE THREAD

**Issue by SetTheorist** [WandererXII/lishogi#640]
The specific lion capture move doesn't seem to be implemented correctly.

It is not allowing a lion capturing another piece and then the opposing lion in a single move (which is allowed, even if that lion can be immediately recaptured.

For example, in this game https://lishogi.org/k1q7EHqC/sente the move 107 Lx56x47 should be allowed.

![image](https://user-images.githubusercontent.com/6331937/221453511-8a5b7c66-7a8d-4fb3-9e1f-300877733e8f.png)

(Compare wikipedia "A lion cannot capture a non-adjacent other lion (i.e. on a "☆" square) when it could then be recaptured on the next move, unless it captures something substantial (i.e. other than pawn or go-between) together with the lion in a double capture. (Such a double capture is called 付け喰い tsukegui or 喰添 kuisoe "additional eating", and recapturing that lion is called 獅子を撃つ shishi o utsu 'shooting the lion'.)"

**Comment by WandererXII** [comment]
Do you mean this move?
![image](https://user-images.githubusercontent.com/43043181/221456394-1cd29940-b7cc-4acc-97ba-4695019ef3c8.png)

That move isn't possible because you only capture a pawn before capturing the opponent's lion. I believe this is covered in the text you attached (highlight mine):

> "A lion cannot capture a non-adjacent other lion (i.e. on a "☆" square) when it could then be recaptured on the next move, unless it captures something substantial **(i.e. other than pawn or go-between)** together with the lion in a double capture. (Such a double capture is called 付け喰い tsukegui or 喰添 kuisoe "additional eating", and recapturing that lion is called 獅子を撃つ shishi o utsu 'shooting the lion'.

Is this what you meant or did I misunderstand?

**Comment by SetTheorist** [comment]
That is what I meant, but you are correct.  I was wrong, I forgot about that detail and missed it when skimming that rule section.  Not a bug.
