### ISSUE TITLE
Suggestion: have the "change language" option be immediately visible in the main page

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#65]
A sizeable portion of players will be japanese. I think it will be helpful for many of them. Also, this is the default for many other shogi apps.

**Comment by WandererXII** [comment]
It is also possible to detect the user's browser language and load the page in that language. Don't know what's better...

**Comment by justremember** [comment]
Oh i was wondering too. Does lichess already have this feature? Maybe there's some privacy issues around it.

**Comment by WandererXII** [comment]
Lichess does have this, so this wouldn't be a problem to do at all.

**Comment by WandererXII** [comment]
Lishogi should now use browser language as default.

**Comment by WandererXII** [comment]
Thanks, the changes are live now.
