### ISSUE TITLE
Checkmate Byoyomi Bug

### ISSUE THREAD

**Issue by TheYoBots** [WandererXII/lishogi#652]
> I have previously used the forum to report a glitch we have encountered on two occasions: if you give checkmate as you enter byoyomi for the first time your opponent is awarded a win on time.
>
> https://lishogi.org/forum/lishogi-feedback/byoyomi-glitch-with-checkmate
>
> Apparently the bug was also discovered at the Mind Sports Olympiad shogi event last weekend.
I believe the playstrategy site uses the same code as lishogi.
>
> James Heppell (jheps) was organising the MSO tournament and he found the bug in the code:

> > **Mind-Sports-Ol**: On investigation of [playstrategy.org/FW0ylWYr/p2](http://playstrategy.org/FW0ylWYr/p2) we can see a bug
with the PlayStrategy system regarding checkmate+byoyomi+timeouts
> > **Mind-Sports-Ol**: If a player enters their Byoyomi period and then delivers checkmate, they
are incorrectly marked as the loser on a timeout
>
> I wanted to bring this to your attention as the only response I have had so far on the forum suggests the problem might lie with my internet connection.

**Comment by WandererXII** [comment]
https://github.com/WandererXII/scalashogi/commit/a9beccfd8ab71ce29cd250b58ca4e097c919497a

**Comment by WandererXII** [comment]
Fixed, thanks for bringing it to my attention!
