### ISSUE TITLE
KIF export does not preserve arrow colours or drawn piece orientations

### ISSUE THREAD

**Issue by KarolS** [WandererXII/lishogi#663]
**Exact URL where the bug happened**

https://lishogi.org/study/eUWBkUPs

but any other study is fine

**Steps to reproduce the bug**

1. Create a study with at least one chapter.
2. Draw some arrows and/or circles.
3. Draw some pieces (MMB on komadai + RMB on board).
4. Export KIF of the chapter.
5. Import the KIF as a new chapter.

I tried reproducing it using CSA, but CSA import didn't work, I'll investigate it later.

**What did you expect to happen?**

1. Arrows and circles in the new chapter has the same colour as in the original chapter.
2. Drawn pieces on the board in the new chapter point in the same direction as in the original chapter.

Here is the original chapter:
![obraz](https://user-images.githubusercontent.com/1790750/229583289-0c492f4e-50a7-47c2-9cdd-153234c7d365.png)

**What happened instead?**

1. All arrows and circles in the new chapter are blue.
2. All drawn pieces point up.
3. Upon closer inspection: 
    * the KIF file does not contain correct arrow colours according to the extended PGN standard: instead of G,R,B,Y it uses P and A
    * the %cpl tags do not contain information about piece orientation (and neither do %cal tags, if the arrow points to pieces in hand).

```
棋戦：vytah's Study - Rozdział 3
場所：https://lishogi.org/study/eUWBkUPs/Dcjafbhw
手合割：平手
先手：
後手：
手数----指手---------消費時間--
* [%csl P4e,P3e,P2e,A4f,A3f,A2f][%cal P9g9d,A8g8d,A7g7d,A6g6d][%cpl P4eL,P3eL,P2eL,A4fL,A3fL,A2fL]
```

![obraz](https://user-images.githubusercontent.com/1790750/229584122-c68dcdfa-afcc-48bb-aee5-2ebbef52a203.png)

**Operating system and browser version**

Windows 10, Firefox 111

**Comment by WandererXII** [comment]
Thanks for the detailed report! Fixed here: https://github.com/WandererXII/lishogi/blame/e2136263079053364d8f46b12f8109b7384223e3/modules/study/src/main/NotationDump.scala#L104

Will be live with the next update.
