### ISSUE TITLE
Game analysis page capture sound missing

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#667]
**Exact URL where the bug happened**
https://lishogi.org/BMF1tBqP

**Steps to reproduce the bug**
Play through the game (including captures)

**What did you expect to happen?**
Capture sound is played when captures occur

**What happened instead?**
Move sound is played when captures occur

**Operating system and browser version**
Windows 10, Vivaldi (Chrome-based) latest

![image](https://user-images.githubusercontent.com/1834123/233641285-c03897a7-d9b6-4d21-821e-d9640a23a959.png)

**Comment by WandererXII** [comment]
Thanks for reporting it!

https://github.com/WandererXII/lishogi/commit/2e2a2a51f9643f2a6d442520d17db7aca15fab9c
