### ISSUE TITLE
IP Address banned, but i'm not banned. Appeal isn't being responded to.

### ISSUE THREAD

**Issue by CVirus11** [WandererXII/lishogi#669]
Hi! I'm ALucasM on Lishogi.org and Lichess.org! My Internet was banned, and you forgot to unban it. and alos, moderators aren't reading my appeals! pls help!

**Comment by WandererXII** [comment]
Hello. Please don't create multiple issues of the same thing. I don't know the details, but I trust the decision that was made by the moderator.

In any case this is not the right place for this.
