### ISSUE TITLE
Fix CI errors

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#67]
If you were to enable the CI pipeline https://github.com/WandererXII/lishogi/actions you would see many errors, for example those seen at https://github.com/ddugovic/lishogi/actions

One purpose of CI is to detect errors early, before production errors become impossible to debug.  For further background I would recommend watching Bryan Cantrill presentations such as [GOTO 2017 • Debugging Under Fire: Keep your Head when Systems have Lost their Mind](https://www.youtube.com/watch?v=30jNsCVLpAE).

**Comment by justremember** [comment]
Shouldn't this be closed already? Or is there anything wrong with the current CI?

**Comment by ddugovic** [comment]
https://github.com/WandererXII/lishogi/actions looks good to me.
