### ISSUE TITLE
[BUG] .kif export data corruption for study chapters containing many variations

### ISSUE THREAD

**Issue by yellowtrafficlight** [WandererXII/lishogi#670]
**Exact URL where the bug happened**

https://lishogi.org/study/X5xjl2cp

**Steps to reproduce the bug**

1. Clone the study
2. Export any 1 of 6 chapters as .kif (Share -> CHAPTER KIF)
3. Add a new chapter -> Choose File -> upload .kif -> Create Chapter

**What did you expect to happen?**

I expected the new chapter to be identical to the original chapter.

**What happened instead?**

The new chapter is an incomplete version of the original chapter, missing moves within variations. There appears be a positive correlation between the size and complexity of the original chapter vs. the number of missing moves in the exported .kif file. The longer the chapter, the greater the number of moves lost.

From my observations, the .kif export is not bugged for text commentary. Move comments are successfully exported, unless the underlying move itself did not successfully write to the .kif file. In that case, both the move and the move comment are lost.

**Operating system and browser version**

macOS Ventura 13.1
Chrome Version 112.0.5615.137

Thank you for your time and attention to this issue.

**Comment by WandererXII** [comment]
Thanks for reporting it, the fix will be live with the next update, which might still take me some time
