### ISSUE TITLE
Joyful upset

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [WandererXII/lishogi#672]
It looks like an previous version. Why?!!!

Browser: Safari, iPhone SE, iOS 14.8.1

**Comment by WandererXII** [comment]
You probably have the old version still cached on your phone. You should be able to see it in anonymous window.

**Comment by Rechefiltr-is-Fire** [comment]
I opened it on my Windows portative comp, both as Rechefiltr and anonymous, but result is still same XD

**Comment by WandererXII** [comment]
I see this, which is the new version I believe.
![image](https://user-images.githubusercontent.com/43043181/236695513-7ff9c759-d615-4eb2-8e23-cc235263228f.png)

'CTRL+SHIFT+R' for force reload. Or give it some time.
