### ISSUE TITLE
Chu shogi bot

### ISSUE THREAD

**Issue by VighneshJadha** [WandererXII/lishogi#673]
Lishogi has an issue:
There is no bot for Chu shogi. Try to make one such bot.

**Comment by WandererXII** [comment]
Engine integration is planned, but some rules lishogi uses are not implemented in HaChu - https://github.com/WandererXII/lishogi/issues/627. Until that is resolved we are stuck. If anyone knows of other engines with decent playing strength we could consider using those.

**Comment by VighneshJadha** [comment]
> Engine integration is planned, but some rules lishogi uses are not implemented in HaChu - #627. Until that is resolved we are stuck. If anyone knows of other engines with decent playing strength we could consider using those.

Which rule differences HaChu has which are not in Lishogi?

**Comment by WandererXII** [comment]
Rules such as lion bridge capture, lance backrank promotions and repetitions might differ

**Comment by VighneshJadha** [comment]
> Rules such as lion bridge capture, lance backrank promotions and repetitions might differ

What does 'Lion Bridge Capture' mean?

**Comment by VighneshJadha** [comment]
> Rules such as lion bridge capture, lance backrank promotions and repetitions might differ

I am not familiar with the term 'Lion Bridge Capture'. Explain what that means.

**Comment by WandererXII** [comment]
> > Rules such as lion bridge capture, lance backrank promotions and repetitions might differ
> 
> I am not familiar with the term 'Lion Bridge Capture'. Explain what that means.

https://lishogi1.org/assets/sandbox/chushogi/index.html#21


> > Rules such as lion bridge capture, lance backrank promotions and repetitions might differ
> 
> Start working to create your bot. After you add the Chu shogi bot, you must add Dai shogi and its bot into Lishogi.

Dai shogi is not planned.

**Comment by VighneshJadha** [comment]
> > > Rules such as lion bridge capture, lance backrank promotions and repetitions might differ
> > 
> > 
> > I am not familiar with the term 'Lion Bridge Capture'. Explain what that means.
> 
> https://lishogi1.org/assets/sandbox/chushogi/index.html#21
> 
> > > Rules such as lion bridge capture, lance backrank promotions and repetitions might differ
> > 
> > 
> > Start working to create your bot. After you add the Chu shogi bot, you must add Dai shogi and its bot into Lishogi.
> 
> Dai shogi is not planned.

Why didn't you plan Dai shogi?

**Comment by VighneshJadha** [comment]
@WandererXII Start working on your Chu shogi bot.

**Comment by WandererXII** [comment]
> Why didn't you plan Dai shogi?

I believe the work that's need outweighs the potential of dai shogi. It's hardly played nowadays, with really long games and steep learning curve. I believe there are features that require attention much more atm. Of course that might change in the future, but I would not count on it.

> @WandererXII Start working on your Chu shogi bot.

You made your request clear, don't repeat yourself.

I will be closing this, since it's being tracked in another issue already.
