### ISSUE TITLE
Minishogi repetition

### ISSUE THREAD

**Issue by Olekaze** [WandererXII/lishogi#674]
currently repetition results in a draw. I think it should be loss for sente. https://lishogi.org/forum/lishogi-feedback/regarding-the-rules-of-minishogi-repetition?page=1

**Comment by WandererXII** [comment]
Thanks for reporting this. Will be fixed.

**Comment by WandererXII** [comment]
Fixed here: https://github.com/WandererXII/scalashogi/commit/81a1f063dc8ed3e76c8e11fd1cf49df3e4ae6a76
Will be live with the next update. Thanks again!
