### ISSUE TITLE
Suggestion : Adding byo-yomi option

### ISSUE THREAD

**Issue by sokah2412** [WandererXII/lishogi#68]
Hello everyone, Currently, we can only choose increment in clock options, which is not used really often in Shogi (at least in my own experience). That'd be very nice to have the possibility to choose a Byo-yomi timer instead !

**Comment by sokah2412** [comment]
Sorry, for the double issue... I have just seen the #14 issue. Please, feel free to delete this one.

**Comment by WandererXII** [comment]
No problem, byo-yomi is definitely something we are going implement.
