### ISSUE TITLE
Board layout

### ISSUE THREAD

**Issue by WandererXII** [WandererXII/lishogi#682]
Layout overflows the screen on vertical screens:
![image](https://github.com/WandererXII/lishogi/assets/43043181/4b092704-c90f-444b-93c8-37b76d0e43b8)
Users can solve it by making the board smaller, but that's obv not optimal.

We want to rewrite once and for all uniboard.scss. We probably need to drop the old _side_ layout, cause trying to maintain one is enough...

Related issues from lichess:
https://github.com/lichess-org/lila/issues/9522
https://github.com/lichess-org/lila/pull/12837

**Comment by WandererXII** [comment]
If we got rid of the side layout, we could have shogiground take care of hands and have it inside `.sg-wrap` possibly making it easier to properly scale and position, instead of this mess:
![image](https://github.com/WandererXII/lishogi/assets/43043181/093549c1-9c99-4978-977a-3083f749591b)

**Comment by WandererXII** [comment]
Currently the side layout is used by 4464 users, which makes me a bit hesitant to remove it... I could set everyone to the compact layout in the next update and see how many people switch back and then decide.

**Comment by WandererXII** [comment]
Also I would slightly rework the compact layout to bring back big clocks and make visible coordinates. Something like this (made in gimp), not sure about the clock cutout, but you get the idea.
![new_compact](https://github.com/WandererXII/lishogi/assets/43043181/4d7e09db-a1cc-45eb-914f-cadd669eeac2)
 I would keep the current compact layout (with the clock and player names attached to board) as an option to streamers who want to have all the important information on a smaller screen capture.

**Comment by WandererXII** [comment]
https://github.com/WandererXII/lishogi/commit/5a72056bd3181ff5a14f8e3e3ebbaa4a8accd61a

**Comment by Olekaze** [comment]
I prefer the side layout for chu shogi

**Comment by WandererXII** [comment]
The clocks are the same size, it's just that chu shogi has that (kinda ugly) gap there where hand pieces would go with other variants...
![image](https://github.com/WandererXII/lishogi/assets/43043181/1f87329b-7357-4f2d-8d21-f3992bbffa84)
![image](https://github.com/WandererXII/lishogi/assets/43043181/b688c8ec-3ac4-47cb-8052-a4d01f10b603)

**Comment by WandererXII** [comment]
Thinking about it, the gaps in chushogi are not ideal. Maybe we could use them for https://github.com/WandererXII/lishogi/issues/625. Or I could make an exception for chushogi and not have the layout same as other variants (related - https://github.com/WandererXII/lishogi/issues/694)...

**Comment by Rechefiltr-is-Fire** [comment]
I prefer to save old layout 😌

**Comment by WandererXII** [comment]
> I prefer to save old layout relieved

Why do you prefer it?

**Comment by Rechefiltr-is-Fire** [comment]
At least now pieces in old layout aren’t small on computer or laptop (mobile devices tweak it) in Mini and Kyoto…

So it would be great for me to make highlighted custom hands in new layout as in old, and:
- or make Mini and Kyoto pieces in hands a bit bigger,
- or save old layout for these variants…

**Comment by WandererXII** [comment]
> At least now pieces in old layout aren’t small on computer or laptop (mobile devices tweak it) in Mini and Kyoto…
> 
> So it would be great for me to make highlighted custom hands in new layout as in old (_Edit:_ probably the main reason why I prefer the old one) , and:
> 
> * or make Mini and Kyoto pieces in hands a bit bigger,
> * or save old layout for these variants…

I agree, I'm trying to think of a solution - https://github.com/WandererXII/lishogi/issues/694

> > I would keep the current compact layout (with the clock and player names attached to board) as an option to streamers who want to have all the important information on a smaller screen capture.
> 
> It’s not forbidden to me to become Lishogi streamer.

Not sure what you mean. But yes you can become a streamer, if you stream, but the compact layout is available to everyone.

**Comment by CouchTomato87** [comment]
I'm a little confused -- what is the issue regarding chu shogi?

**Comment by WandererXII** [comment]
The gaps on each side of the board, that are reserved for hands, I don't think it looks that bad, but still... gif, switching between default and side layout:
![Peek 2023-07-04 01-33](https://github.com/WandererXII/lishogi/assets/43043181/3379d200-f230-45f8-9be3-dad5010a83f6)

I can't just remove them because I want to preserve the same layout across all variants, board and everything at the same place, no layout shifting.

**Comment by Olekaze** [comment]
aside from the gaps, my main problem with the new layout is the longer move list. I want the clocks to be as big and close to the center as possible so I can keep track of time without taking my eyes off the board (this is also the reason I don't like the gaps). I think the longer move list looks nicer but I don't see the point

**Comment by milkymia93** [comment]
dont know how github works, but i use the side view for streaming layout and it works wonders with obs because it has the board background in it as well. i much prefer the side layout to any other layout, and especially for streaming shogi.

**Comment by WandererXII** [comment]
Unfortunately side layout was already removed here and soon the change will be live.
But the now default layout might have an advantage for streaming, because smaller area of the window needs to be captured, since the hands and the board are together, but obv this depends on your setup too:
![image](https://github.com/WandererXII/lishogi/assets/43043181/f93aa74c-b27f-4a37-bcd9-538087e1053d)
There is also a setting, that adds background to the pieces in hand:
![image](https://github.com/WandererXII/lishogi/assets/43043181/527f4778-909d-417d-99d5-b9f6bb73416e)
I could write some dirty css stylesheet for stylus, but that's not a long term solution...

**Comment by milkymia93** [comment]
i see you updated it, thats unfortunate, i like that you can have background to the pieces in hand but its awkward because it's vertical rather than horizontal. oh well :)
