### ISSUE TITLE
Team Battle with many teams

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#683]
> I've checked lichess can held team battle up to 200 teams.
> In this way, I thought lishogi also can held team battle up to 200 teams, but actually up to 10 teams.
> Is it possible to enlarge the teams (no need to 200 teams but up to 50 or more) in 2 weeks?
> I will apologize for demanding this task but I want to explain the reasons.
> 
> At 25 June(Sun.), a very big team battle has been planned by a streamer between 20:30 and 22:00(JST).
> This is the tweet which the details are explained.
> [twitter.com/Vpomeshogi/status/1660246249868775425?s=20](https://twitter.com/Vpomeshogi/status/1660246249868775425?s=20)
> The event is team battle where every team has 3 members.
> At this time, about 45 teams (i.e. participants arround 150 users) will join it so the event capacity is not enough now.
> 
> Again, I apologize about this strong and hurry suggestion.
> If it will be accepted, I am very happy and no concern about the event and more active lishogi.
> If not, I will need to notify the host the result.
> 
> I'm very glad to all lishogi developers.

https://lishogi.org/forum/lishogi-feedback/suggestion-more-than-10-teams-for-team-battle-asap

**Comment by WandererXII** [comment]
Thanks for bringing it to my attention.

**Comment by WandererXII** [comment]
8abd50a7456b9e4a7b60cc3f55fe1c6515bd9a35
