### ISSUE TITLE
New trophies

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [WandererXII/lishogi#685]
If you want to create new update, it will be cute to add new trophies like Lichess and Pychess ones (not like old Lichess and Lidraughts trophies).
![silverTrophy](https://github.com/WandererXII/lishogi/assets/101206332/03a55e07-36a7-4db6-b65e-78e0b57cb14a)

**Comment by WandererXII** [comment]
Looks great, maybe a missed opportunity to not have 金 on the gold trophy, 銀 on the silver one and perhaps 銅 on the bronze one, not sure about that one.

Also how is it with copyright?

**Comment by Rechefiltr-is-Fire** [comment]
Look at Lichess and Pychess and you will understand.
Pentagon figure is taken from SVG posted in you repo, and Silver kanji is from your Shogi Basics.
