### ISSUE TITLE
The large 15×15 game Dai Shogi along with 16×16 Tenjiku Shogi and other shogi variants

### ISSUE THREAD

**Issue by VighneshJadha** [WandererXII/lishogi#689]
Add Dai shogi to Lishogi. Dai shogi adds knights to the Chu shogi experience and also introduces new pieces like Angry Boar, Cat Sword, Evil Wolf, Violent Ox, Flying Dragon, Iron and Stone Generals.
Also add Tenjiku shogi which features the Fire Demon which can burn any adjacent enemy pieces along with range-jumping generals, which can move as range movers but also jump any number of pieces including zero to capture.
Also add Dai Dai and Maka Dai Dai shogi which feature hook moving pieces which can range but at one point in their paths, they may turn 90° then continue moving. Hook moving pieces cannot continue after capturing straight.
Also add Tai shogi which blends Dai Dai and Maka Dai Dai shogi but also introduces Turtle-Snake, Vermillion Sparrow, Peacock, Soldier, Ram's Head Soldier, Fierce Eagle, Side Dragon, Golden Deer, Silver Hare.
Also add the largest shogi variant - Taikyoku shogi.

**Comment by WandererXII** [comment]
Sorry, but not planned
