### ISSUE TITLE
Suggestion: Analysis with the opponent

### ISSUE THREAD

**Issue by sokah2412** [WandererXII/lishogi#69]
It would be great if we could analysis the game we just made (or another one) with the person with whom we played it. 81dojo is great on this point, with its host mode, branching support, the possibility to show with arrows threats and tactics, and all. And the best thing in my opinion, would be to be able to also use the computer evaluation on this mode.

**Comment by justremember** [comment]
This feature is the only reason why I think 81dojo is the best shogi platform right now. Talking to your opponent about the game, knowing his thought process, looking at possible variations with the opponent. Almost replicating an over-the-board experience. After encountering this feature in 81dojo I'd say a shared post-game analysis feature is almost necessary for a serious ~~boardgame~~ shogi platform.

**Comment by sokah2412** [comment]
Totally agree, and when lishogi will have it I think it will be faaaar greater than 81dojo, but now, I really miss this feature.

**Comment by kleffa** [comment]
I think you can still use the chat after play, didn't trued here, but in lichess I remember chat with friends after play

**Comment by WandererXII** [comment]
After we get all the necessary stuff done - byo-yomi, impasse, bugs, etc. I will try to implement this. Study's got something similar, where it tries to sync what everyone sees, with some tweaks it could work like like an after game analysis with your opponent.

**Comment by WandererXII** [comment]
Moved here https://github.com/WandererXII/lishogi/issues/363
