### ISSUE TITLE
Unique sets for Kyoto Shogi?

### ISSUE THREAD

**Issue by CouchTomato87** [WandererXII/lishogi#695]
Any thoughts on having Kyoto Shogi have access to unique sets like chu shogi? At Pychess we already have all the images ready, so you'd basically just need to copy them. Two reasons why this may be worth considering:

1) Visually - Using the standard shogi image sets, pieces changing from front to back will change size, which is weird. For example, the small pawn changes to the big rook.

2) Mnemonics - All the specialized Kyoto Shogi sets on Pychess also have mnemonic devices, which makes it much easier to play.

![image](https://github.com/WandererXII/lishogi/assets/52322435/06852593-46af-4a08-9ef5-b1670ab0c697)

![image](https://github.com/WandererXII/lishogi/assets/52322435/c17265aa-ab41-4de0-9ac9-09ec21c9ceca)

**Comment by WandererXII** [comment]
Definitely agree with your points. I might have to rework how piece sets are handled tho, because the list of pieces already can't fit my screen:
![image](https://github.com/WandererXII/lishogi/assets/43043181/0d577e63-3dcb-4d77-855f-d9014153926b)
Probably to something similar to how Pychess does it - showing only the piece sets for the current variant.

**Comment by WandererXII** [comment]
https://github.com/WandererXII/lishogi/commit/7fca3ef893013510d251e1459f607d29b8cbb7fd
https://github.com/WandererXII/lishogi/commit/8029d2dd47d2cfcd399b3902f32150fb56af6855
https://github.com/WandererXII/lishogi/commit/e3142ed0560f65553b930a6e383cd3821371f385
https://github.com/WandererXII/lishogi/commit/112fdbf8f844cc465176402183728719a0b6b81b

![image](https://github.com/WandererXII/lishogi/assets/43043181/bfc1d0fd-84dc-4234-9c55-f5beda0fecd9)

**Comment by Rechefiltr-is-Fire** [comment]
https://github.com/WandererXII/lishogi/issues/701
