### ISSUE TITLE
Dai shogi

### ISSUE THREAD

**Issue by VighneshJadha** [WandererXII/lishogi#697]
After Annan and Kyoto shogi, I hope that they add Dai shogi next so I can use knights in Chu shogi.
**Dai shogi initial setup**
![image](https://github.com/WandererXII/lishogi/assets/110092019/227c71d7-e617-481f-8dca-fe75f807dd62)
![image](https://github.com/WandererXII/lishogi/assets/110092019/188265e1-aa23-4ffa-bf35-616f7e41e0f8)
![image](https://github.com/WandererXII/lishogi/assets/110092019/f50eca41-1d37-40a4-87c3-27732a523cd2)
![image](https://github.com/WandererXII/lishogi/assets/110092019/c22129fc-ecbf-42f0-b521-36c946fa561b)

**Comment by WandererXII** [comment]
Dude, you know u posted the same issue like 3 times and each time I said it's not gonna happen...

**Comment by VighneshJadha** [comment]
@WandererXII What will Dai shogi fans say?

**Comment by Rechefiltr-is-Fire** [comment]
@VighneshJadha what will server answer?

**Comment by VighneshJadha** [comment]
Rechefiltr is fire! I kindly say that @WandererXII **must** add Dai shogi otherwise Dai shogi fans who prefer Lishogi will keep on repeating to post about Dai shogi.
