### ISSUE TITLE
Board editor select a piece and drag/click on squares to add it to the board

### ISSUE THREAD

**Issue by Olekaze** [WandererXII/lishogi#707]
The lichess board editor lets you select a piece and place it on the board by clicking on squares or dragging the courser over the board. Not sure if it's a bug but this doesn't work on lishogi, forcing you to drag pieces one by one from the piece menu.

**Comment by WandererXII** [comment]
Clicking squares after selecting a spare piece works for me, but you are right, that dropping the new pieces by dragging the cursor over the board doesn't work, not sure if we want that, but I will look into it.

![editor_pieces](https://github.com/WandererXII/lishogi/assets/43043181/32566247-20b0-4e59-b7c5-e3a99f8ff322)

**Comment by Olekaze** [comment]
I think I found the issue. Checking "drag a piece" in the preferences breaks it. not a problem on lichess

**Comment by WandererXII** [comment]
Oh, nice find. `selectSquare` won't select a square, if `selectable` is disabled - https://github.com/WandererXII/shogiground/blob/c6e1591c02b4de8d000866ebdd1c2e0e2d207847/src/board.ts#L227.
It kinda makes sense tho, with 'drag a piece' you can only drag, but it's annoying in editor. I guess I will have to tweak shogiground, to make an exception...
