### ISSUE TITLE
Studies down

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#713]
> It looks that is possible to access to the studies already created but not to add any new chapters or create a new one.

https://lishogi.org/forum/lishogi-feedback/studies-down

**Exact URL where the bug happened**

**Steps to reproduce the bug**

**What did you expect to happen?**

**What happened instead?**

**Operating system and browser version**

**Comment by WandererXII** [comment]
Thanks for reporting this, restarted lila - for now it seems to work. Will try to fix asap...

**Comment by WandererXII** [comment]
Creating studies from games with no moves created invalid `position` field in db, which then threw an exception, when we tried to read it back.
I guess that could put the thread in a weird state, I observed similar behavior once, but idk, couldn't replicate it locally.

https://github.com/WandererXII/lishogi/commit/18914e527e92dfdc631e86040d12448aaa93fdea
https://github.com/WandererXII/lishogi/commit/962a4a67bfe0cbbb764dbcc91c2af4cc676ebc64

Please let me know if you notice anyone having this issue.

**Comment by WandererXII** [comment]
Closing this, create a new issue please if it happens again
