### ISSUE TITLE
Byoyomi periods and Rated games

### ISSUE THREAD

**Issue by TheYoBots** [WandererXII/lishogi#715]
> Currently it is not possible to create rated games using byoyomi periods. In Chu shogi, a game can last over 4 hours, and small breaks are necessary. Can this be changed?

~ https://lishogi.org/forum/lishogi-feedback/byoyomi-periods-and-rated-games

**Comment by WandererXII** [comment]
Moved to https://github.com/WandererXII/lishogi/issues/718
