### ISSUE TITLE
conditional premoves don't work in correspondence games from position

### ISSUE THREAD

**Issue by Olekaze** [WandererXII/lishogi#716]
in this game https://lishogi.org/pWjBr2gN both of us weren't able to make conditional premoves. After playing out the moves, I wasn't able to save them. In all my other games not from position I had no problems. I was able to reproduce it with games vs an anon in all variants I tried

**Comment by WandererXII** [comment]
Thanks for reporting this, I will look into it.
So pressing 'add current variation' did nothing?
![image](https://github.com/WandererXII/lishogi/assets/43043181/a0f0c86e-781d-44e0-b066-8f5949fd929c)

**Comment by Olekaze** [comment]
in the same game I noticed that the downarrow key doesn't work. It should move you to the last move but instead moves you to the first like the upkey. Only a problem in this game
