### ISSUE TITLE
Custom Piece Set Submission

### ISSUE THREAD

**Issue by HansAldiChristian** [WandererXII/lishogi#728]
I see that lishogi doesn't have a piece set that has a pixely/8-bit theme so I tried to create my own. (Creator: Justice007)
png file:
![Justice007's Pixelated Piece Set](https://github.com/WandererXII/lishogi/assets/146007537/3d9f15c8-c00d-450a-87dc-58866ca06612)
svg file:
![Justice007's Pixelated Piece Set](https://github.com/WandererXII/lishogi/assets/146007537/2cc08268-71f7-4bd1-871b-2cf7aaf2eecd)
I hope this piece set could be put into consideration.

**Comment by HansAldiChristian** [comment]
I also provide the individual svg files for each piece:
![0FU](https://github.com/WandererXII/lishogi/assets
![0HI](https://github.com/WandererXII/lishogi/assets/14
![1TO](https://github.com/WandererXII/lishogi/assets/146007537/eb18e725-6f06-49a6-985d-4dabe0d365d5)
![0TO](https://github.com/WandererXII/lishogi/assets/146007537/72c3a2de-5871-405a-bbfc-4d1e1d72acf7)
6007537/22eddd3e-56f3-4058-b7e9-8dd4ebaf6f1a)
![1HI](https://github.com/WandererXII/lishogi/assets/1460
![1OU](https://github.com/WandererXII/lishogi/assets/146007537/2ccdae28-c698-473
![1UM](https://github.com/WandererXII/lishogi/assets/146007537/a837557d-4381-48cd-803c-27dbb2ea3480)
![0UM](https://github.com/WandererXII/lishogi/assets/146007537/7f979aae-68a1-4f41-8d7f-69e59b8c28ba)
a-bd95-e30bac40bfc9)
![0OU](https://github.com/WandererXII/lishogi/assets/146007537/a369f092-dd0b-4014-836e-6af9b6296644)

![1NY](https://github.com/WandererXII/lishogi/assets/146007537
![1RY](https://github.com/WandererXII/lishogi/assets/146007537/779a7c3f-3380-4a30-9fa3-665a34bd1198)
![0RY](https://github.com/WandererXII/lishogi/assets/146007537/8bab0876-a350-4a48-a1ac-7aa9eddcea69)
/9bbf5b53-8cda-4b82-8fbb-b60a01a35389)
![0NY](https://github.com/WandererXII/lishogi/assets/146007537/1c4a63d0-c2c0-4c
![1NG](https://github.com/WandererXII/lishogi/assets/146007537/806b4a90-fe56-4d25-b393-c9b15ab90d22)
![0NG](https://github.com/WandererXII/lishogi/assets/146007537/f6a2b160-e151-471f-8603-122d7425f956)
70-a76a-801431f81fe8)
07537/4845f
![1KA](https://github.com/Wande
![1KE](https://github.com/WandererXII/lishogi/assets/146007537/e21c5233-4882-4eed-91c1-8a1cb21c0f74)
![0KE](https://github.com/WandererXII/lishogi/assets/146007537/3c093b19-74a9-44b5-8f40-b62986ab45cd)
rerXII/lishogi/assets/146007537/b370b
![1KY](https://github.com/WandererXII/lishogi/assets/146007537/ce505697-7fd5-4c43-af40-4e1709cc0e82)
![0KY](https://github.com/WandererXII/lishogi/assets/146007537/
![1NK](https://github.com/WandererXII/lishogi/assets/146007537/f08e2bd4-ee0d-4de9-a4c8-39db81beedb2)
![0NK](https://github.com/WandererXII/lishogi/assets/146007537/b1cab7f6-8af3-4429-8eef-e94f9a858613)
b3e35d98-fce5-4ae2-a9d5-fa63cdc2c0e5)
671-0c45-4900-9ff3-cea6be4150e1)
![0KA](https://github.com/WandererXII/lishogi/assets/146007537/5721cb02-028d-42e6-8cab-9a5b34b7a1cc)
82c-6af2-4049-afd9-a8bd75ea3695)
![1KI](https://github.com/WandererXII/lishogi/assets/146007537/86921365-5c91-40d0-b2ea-b5100b184f74)
![0KI](https://github.com/WandererXII/lishogi/assets/146007537/268df201-20b3-4305-b917-66593b07471a)


![0GY](https://github.com/WandererXII/lishogi/assets/146007537/e469304f-6dfa-4837-b99a-7a6b54ee8536)
![1GY](https://github.com/WandererXII/lishogi/assets/146007537/68c8f6fb-05ad-4909-ae2e-2f66db78d691)
/146007537/
![1GI](https://github.com/WandererXII/lishogi/assets/146007537/00147222-2ab8-4095-b828-5088c66f50ca)
![0GI](https://github.com/WandererXII/lishogi/assets/146007537/c0e7bf1c-9df5-4f2a-b4e8-9b3fa706526f)
2d48120b-efe7-40dd-a5d2-d204d5a387e1)
![1FU](https://github.com/WandererXII/lishogi/assets/146007537/ad58a56d-3b30-4f25-8161-13a6c32810fc)

**Comment by HansAldiChristian** [comment]
I also provide the svg files for each piece if it helps:
![1FU](https://github.com/WandererXII/lishogi/assets/146007537/ff5c452b-4385-4933-88cd-80b2d1c35626)
![0FU](https://github.com/WandererXII/lishogi/assets/146007537/32b2cc6c-515c-428f-8b02-ce4597857b5a)
![1GI](https://github.com/WandererXII/lishogi/assets/146007537/74e6a20c-d29a-4ae4-b32a-2275ce1dcbe0)
![0GI](https://github.com/WandererXII/lishogi/assets/146007537/a98ca275-7da3-42ce-9b80-0e086fe89fb3)
![1GY](https://github.com/WandererXII/lishogi/assets/146007537/5d6a37d2-56ee-457f-928e-d8fe22f2a826)
![0GY](https://github.com/WandererXII/lishogi/assets/146007537/5ed41ded-8d79-489a-b633-458bfd84ae9e)
![1HI](https://github.com/WandererXII/lishogi/assets/146007537/52ed81a4-b6f1-4ecf-a3ee-7310355e4950)
![0HI](https://github.com/WandererXII/lishogi/assets/146007537/cb5e4d49-11b7-479a-95bb-f3e95f125f8d)
![1KA](https://github.com/WandererXII/lishogi/assets/146007537/5a4cf791-ecea-49d1-b88b-8822460b05b4)
![0KA](https://github.com/WandererXII/lishogi/assets/146007537/080cb3dc-ecec-4ba4-8be7-4a97f87d06b5)
![1KE](https://github.com/WandererXII/lishogi/assets/146007537/be3af006-76fb-4776-a840-38aae47b0daa)
![0KE](https://github.com/WandererXII/lishogi/assets/146007537/21857a9e-9402-4398-b3a6-f79b03f4355b)
![1KI](https://github.com/WandererXII/lishogi/assets/146007537/5ae9d314-b58c-41d0-abbb-fa93b5306943)
![0KI](https://github.com/WandererXII/lishogi/assets/146007537/36312941-4c9e-4589-b52c-c6ed6cd735c2)
![1KY](https://github.com/WandererXII/lishogi/assets/146007537/afd49548-7b8c-48b2-8ac7-7d8a61af5b89)
![0KY](https://github.com/WandererXII/lishogi/assets/146007537/77129749-60bd-4aec-bdd8-2e566fc5ba9e)
![1NK](https://github.com/WandererXII/lishogi/assets/146007537/8f927df1-4719-4ca7-b412-63fecf836305)
![0NK](https://github.com/WandererXII/lishogi/assets/146007537/b8d1c46f-11bf-4f61-90e6-a05ef9063bfd)
![1NY](https://github.com/WandererXII/lishogi/assets/146007537/54bf79c4-1938-4420-927b-764083b57901)
![0NY](https://github.com/WandererXII/lishogi/assets/146007537/33f1db55-a765-47ab-a0d5-ee78b5b89d91)
![1NG](https://github.com/WandererXII/lishogi/assets/146007537/cdd3ff9a-2e94-4b92-9d7d-864de5f38f70)
![0NG](https://github.com/WandererXII/lishogi/assets/146007537/4f2a9856-7da3-4748-95dc-a1636dc2d2c1)
![1OU](https://github.com/WandererXII/lishogi/assets/146007537/7762f60f-5ed5-4b4b-b784-4b2d3ae679be)
![0OU](https://github.com/WandererXII/lishogi/assets/146007537/da9a5af1-1a11-4a72-9b78-5922e063465a)
![1RY](https://github.com/WandererXII/lishogi/assets/146007537/63f3dfc6-7796-41ad-beb6-88c05ba311af)
![0RY](https://github.com/WandererXII/lishogi/assets/146007537/8f09d961-9988-4d51-b1d6-b59bce284ccf)
![1TO](https://github.com/WandererXII/lishogi/assets/146007537/97c8e30c-3582-4942-a88f-e9d2703b9a87)
![0TO](https://github.com/WandererXII/lishogi/assets/146007537/1112b2ee-3847-4994-8b85-d4c482f781a8)
![1UM](https://github.com/WandererXII/lishogi/assets/146007537/b1f1e633-981c-4e44-9416-8284c9dd3753)
![0UM](https://github.com/WandererXII/lishogi/assets/146007537/fd33b7dd-63dd-4e51-81b8-1d983a68decf)

**Comment by M-DinhHoangViet** [comment]
nice

**Comment by WandererXII** [comment]
Really nice, I will be sure to add them with the next update. Thanks!
