### ISSUE TITLE
I offer this board theme

### ISSUE THREAD

**Issue by Olekaze** [WandererXII/lishogi#729]
![271750743-83c26359-7c5f-4a52-bf06-dea7c5bead87 (1)](https://github.com/WandererXII/lishogi/assets/89757188/bc56bd68-f53b-4f17-a078-ea75ec6b340a)
![olekaze wood](https://github.com/WandererXII/lishogi/assets/89757188/83c26359-7c5f-4a52-bf06-dea7c5bead87)

![Screenshot 2023-09-29 23 33 03](https://github.com/WandererXII/lishogi/assets/89757188/b129034f-0432-4354-a8c5-75c6801f85cd)

By the way, would it be possible to add a grid thickness somewhere between slim and thick?

**Comment by WandererXII** [comment]
Thanks, I will be sure to add this.

> By the way, would it be possible to add a grid thickness somewhere between slim and thick?
Slim is 1 pixel wide and thick is 2 pixel wide. Subpixels do not really work well - some lines would be 1 pixel wide and other 2 pixel wide.
I could try make the second pixel color less sharp, which could make it look less thick, but not sure if worth the added complexity, but I will try it.

**Comment by Olekaze** [comment]
was the grid thickness 2 pixels before the custom board update?

**Comment by WandererXII** [comment]
I think the custom board update was together with the board rework. So before that the board and grid lines were just a png. The issue with that was that the image had to be scaled by the browser and the grid lines weren't all scaled to the same thickness, so I reworked it - https://github.com/WandererXII/lishogi/issues/513.
