### ISSUE TITLE
Small Bugs:Coordination is unchanged at Lishogi TV pages.

### ISSUE THREAD

**Issue by ch-suginami** [WandererXII/lishogi#73]
This is related the closed issue about #17 of coordination style.
I checked the coordination is fixed to two numbers except Lishogi TV pages like this below picture.
![image](https://user-images.githubusercontent.com/67103794/99843513-08b3ad00-2bb5-11eb-879a-37fac7476a91.png)
I think coordination of watching other players' games (not only above one but maybe all games) continue old style now.

**Comment by WandererXII** [comment]
Hey, thanks for reporting this! Will fix tomorrow.

**Comment by WandererXII** [comment]
Fixed
