### ISSUE TITLE
Suggestion for piece set selection names

### ISSUE THREAD

**Issue by CouchTomato87** [WandererXII/lishogi#734]
![image](https://github.com/WandererXII/lishogi/assets/52322435/6def888f-e795-467d-b716-b7ae70763483)

Just a couple things I've noticed.

1 - The names are a little crowded. Also, why is "chushogi" one word and Kyoto Shogi two?
2 - Why need the name "shogi"? Every variant is shogi. So my suggestion is simply "Chu" and "Kyoto." in fact, with the space saved, you could call it "中 Chu" and "京都 Kyoto."
3 - "Default" is a strange choice of word. Default is the word I'd use for the default set. In this case, I think the better word is "Standard," both for Standard Shogi and also standard shogi set (i.e. what you use for variants that also use a standard set)

**Comment by WandererXII** [comment]
The names come from translations, so I fixed Chu being one word and kyoto two. But I don't really want to add shorter versions of variants to translations just for this... And using translations feels better than hardcoded strings.
I replaced 'Default' with 'Standard' (https://github.com/WandererXII/lishogi/commit/840ef2c74805335e588b1e30376e31921f77437c)
Thanks for the suggestions.

**Comment by Eventlesstew** [comment]
Better way to do this is to use piece folders. Default can remain as is, but then Chu and Kyoto are merged into one "Variants" tab where the sets for Chu and Kyoto Shogi are split into folders.

(Sorry for posting in a closed issue, just thought I'd bring that up.)
