### ISSUE TITLE
Many search bars stopped working

### ISSUE THREAD

**Issue by Olekaze** [WandererXII/lishogi#735]
https://lishogi.org/team/all
https://lishogi.org/games/search
https://lishogi.org/forum
https://lishogi.org/study

If you try to search something it won't load

**Comment by WandererXII** [comment]
Fixed, thanks for reporting it. I couldn't figure out what actually caused it tho, so if you notice it again please let me know.

**Comment by Olekaze** [comment]
number of turns filter in the advanced search stopped working. for example in https://lishogi.org/games/search?turnsMin=1&turnsMax=100&clock.initMin=0&clock.initMax=30&sort.field=d&sort.order=desc#results the time control filter works but number of turns is deleted and ignored when you click search (it's still in the url though). tested it on firefox and chrome

**Comment by WandererXII** [comment]
Thanks for letting me know, I think I know why this is. I renamed it to 'pliesMin' and 'pliesMax', but I missed it somewhere. Will be fixed with the next update.

**Comment by PatMyron** [comment]
@WandererXII these search bars seem broken again:

> https://lishogi.org/team/all
> https://lishogi.org/games/search
> https://lishogi.org/forum
> https://lishogi.org/study

**Comment by WandererXII** [comment]
Thanks, fixed now. I will investigate the cause later.
