### ISSUE TITLE
Game manners

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#739]
See 81Dojo: players can great each other before and after games, and report upon whether opponents' game manner is appropriate.  Game manners (and user preferences for "interest in post-game discussion") may also encourage post-game analysis.

**Comment by AlexGTrick** [comment]
Greetings already exist on Lishogi. There are buttons like "GL" and "HF" pressing which you automatically send into chat "Good Luck", "Have Fun", etc. After the game, you can use "GG" and "WP" which will come into "Good Game" and "Well Played".
