### ISSUE TITLE
Annan mate?

### ISSUE THREAD

**Issue by Little-Mage** [WandererXII/lishogi#747]
**https://lishogi.org/jsKRy4H5/gote#28**

**Steps to reproduce the bug**
Made a game via Create a Game button
Played the game till mate
**What did you expect to happen?**
game to end.
**What happened instead?**
platform didnt see the mate
**Operating system and browser version**
Microsoft Edge
Version 119.0.2151.72 (Official build) (64-bit)

<img width="960" alt="image" src="https://github.com/WandererXII/lishogi/assets/55811361/4051b154-495f-4ae0-88cf-90af73839cd5">

**Comment by Olekaze** [comment]
It's not mate. The pawn can capture the gold

**Comment by Little-Mage** [comment]
oh thats wack lol
