### ISSUE TITLE
Variant 1-check

### ISSUE THREAD

**Issue by Little-Mage** [WandererXII/lishogi#753]
1st check wins with drops (the normal shogi rules)
Tried this variant with a friend and its fun.
Games:
https://system.81dojo.com/en/kifus/9697926
https://system.81dojo.com/en/kifus/9697938
https://system.81dojo.com/en/kifus/9697963
https://system.81dojo.com/en/kifus/9697954

**Comment by Little-Mage** [comment]
or 3-check

**Comment by M-DinhHoangViet** [comment]
Wait until Lishogi restarts. Because @WandererXII added the CheckShogi variant a month ago

**Comment by WandererXII** [comment]
Closing in favor of https://github.com/WandererXII/lishogi/issues/712
