### ISSUE TITLE
Board not being displayed completely in tablet on portrait(vertical) mode

### ISSUE THREAD

**Issue by ghost** [WandererXII/lishogi#754]
![Screenshot_20231228-120448_Mull](https://github.com/WandererXII/lishogi/assets/155057060/13bfab2e-a4b7-4c24-81f7-c3cd58c3ffb4)

**What did you expect to happen?**

**What happened instead?** website display has changed and the board is inaccessible
**Operating system and browser version**
Android 12 : Samsung tab A7
Even reported by ipad user on Lishogi discord channel
All the browsers( chromium based and gecko based) except cromite(fork of bromite browser) 
![Screenshot_20231228-142249_Discord](https://github.com/WandererXII/lishogi/assets/155057060/14b519bf-85ad-42f2-895d-2add756a3851)

![Screenshot_20231228-143050_Mull](https://github.com/WandererXII/lishogi/assets/155057060/60f42f86-4a26-4e22-823b-4a2df1302b9d)
![Screenshot_20231228-142652_Mull](https://github.com/WandererXII/lishogi/assets/155057060/ec4c6829-537e-438f-a209-4e62fd28ea14)
![Screenshot_20231228-142042_Mull](https://github.com/WandererXII/lishogi/assets/155057060/b1584369-2932-42e4-92f4-9ecc7908c878)
![Screenshot_20231228-120448_Mull](https://github.com/WandererXII/lishogi/assets/155057060/f389f6bb-6ccf-4882-87ff-9b4a4fa59b6d)
![Screenshot_20231228-115055_Mull](https://github.com/WandererXII/lishogi/assets/155057060/24907295-568c-4083-812c-acce586171b4)

*** Earlier before Oct 2023 it used to be like
![Screenshot_20231228-142532](https://github.com/WandererXII/lishogi/assets/155057060/d4692ec5-142f-4a7a-ba47-3bf4473093b0)
![Screenshot_20231228-141955](https://github.com/WandererXII/lishogi/assets/155057060/059ff375-d0c6-4d3d-904c-b3c971fc37db)
![Screenshot_20231228-120309](https://github.com/WandererXII/lishogi/assets/155057060/fcc6353e-6f30-4794-a88e-58aeee18f3ca)

**Comment by Rainfall1917** [comment]
I'm observing the same thing with all the Lichess forks 
Lichess, Lishogi and Lidraughts

**Comment by Rainfall1917** [comment]
It happens on cromite too but not always

**Comment by WandererXII** [comment]
Thanks for reporting it.
Possibly related to this https://github.com/WandererXII/lishogi/issues/682?
I rewrote the whole layout structure, so I could fix it, but still haven't got around to actually fixing it.
It's weird that it worked in October, because no css was changed since then, maybe some browser behaviour changed.

**Comment by Rainfall1917** [comment]
I dont think that its much related to #682, in this case there is no way that I can resize the board. The main issue are the last two files on the board which dont even appear.

**Comment by WandererXII** [comment]
Should be fixed - https://lishogi.org/blog/post/ZcQjlRAAACMAgvrF, if this still happens comment here, I will reopen it, or create a new issue - thanks!

**Comment by kachick** [comment]
I had same problem in my iPad Pro 12.9-inch 2017 ver, that has been fixed now! 🙏
