### ISSUE TITLE
[Feature request] Add api endpoint for leaderboard

### ISSUE THREAD

**Issue by roman-vygon** [WandererXII/lishogi#756]
Currently API is missing an endpoint for leaderboards, instead in documentation there's only a link to the html variant like https://lishogi.org/player/top/200/bullet, it would be useful to also have https://lishogi.org/api/player/top/200/bullet which returns json like on lichess.

**Comment by TheYoBots** [comment]
Check this out: https://lishogi.org/api#tag/Users/operation/playerTopNbPerfType
