### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Cola-lishogi** [WandererXII/lishogi#757]
On the Lishogi forums you can put a reaction to your message, and if, for example, your forum tab crashed or for some other reason, Lishogi writes that the forum has already been viewed 2 times! 
I am writing through a translator, so there may be mistakes. I can write in Russian without errors!

**Comment by M-DinhHoangViet** [comment]
https://crowdin.com/project/lishogi/ru

**Comment by WandererXII** [comment]
Thanks for reporting this. Seems that they removed it on lichess for this exact reason (https://github.com/lichess-org/lila/commit/e3c0ea2b0980320e75e0b4d1a69bf19aee094f72). So I will do just that.

**Comment by WandererXII** [comment]
https://github.com/WandererXII/lishogi/commit/0066de2326e26bd10f173ba0ad8ae40dddbc39d3
