### ISSUE TITLE
custom backgrounds, boards, and piece userstyles don't work in puzzles/analysis/studies on firefox

### ISSUE THREAD

**Issue by Olekaze** [WandererXII/lishogi#759]
**Exact URL where the bug happened**
only studies, puzzles and analysis

**Steps to reproduce the bug**
use a custom background(not default) or board image and it won't show

**Operating system and browser version**
Firefox (chromium seems ok). I'm using the latest version. galago also has the same issue

**Comment by WandererXII** [comment]
Same as this: https://github.com/WandererXII/lishogi/issues/675
But firefox now supports `credentialless`, so once I deploy it's gonna be fixed.
