### ISSUE TITLE
Study - Import Kifu with resignation

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#783]
**Exact URL where the bug happened**
https://lishogi.org/study/ENWm5YvR/qWa8Z5k9

**Steps to reproduce the bug**
1. Copy kifu from https://system.81dojo.com/en/kifus/9827848
2. Open an existing study (or create a new one)
3. Add a new chapter (KIF/CSA)
4. Paste kifu and Create Chapter

**What did you expect to happen?**
Resignation and result should be visible (like how ShogiGUI and ShogiDokoro include the resignation and result)

**What happened instead?**
Game is imported except for the resignation and result

**Operating system and browser version**
Windows 10, Vivaldi (latest)

![image](https://github.com/WandererXII/lishogi/assets/1834123/e266822f-b97d-4128-8e01-0513d1e92c32)
![image](https://github.com/WandererXII/lishogi/assets/1834123/eaf19c75-150a-433f-9d3d-a37f53a6e631)

**Comment by WandererXII** [comment]
Thanks for the detailed issue.
