### ISSUE TITLE
Shogi hands on Minishogi games

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [WandererXII/lishogi#788]
Where you’re watching Minishogi via tournament, you see that there are ghosts reserved for Knights and Lances, and therefore there’re 7, and two of them (Pawn & Lance) overlap on the board’s squares. Please fix;)
![974FD468-2198-41B4-A853-F27C8776EEBC](https://github.com/WandererXII/lishogi/assets/101206332/33556ce9-16de-48d9-8f14-54c0e4d8eb13)

**Comment by Rechefiltr-is-Fire** [comment]
> But hardly playable from mobile device. Board simply gets reduced in size.

#799

**Comment by WandererXII** [comment]
Thanks for the screenshot, closing this now.
