### ISSUE TITLE
Bug: In Analysis Mode with engine enabled, preview ghost images aren't from current piece set

### ISSUE THREAD

**Issue by aclaudiadavid** [WandererXII/lishogi#79]
When in analysis mode with the engine on, the "ghost images" to indicate piece drops appear with the default piece set.
![image](https://user-images.githubusercontent.com/48031230/99915065-3efa4500-2cf9-11eb-9f7a-fdb35ab49cf8.png)

**Comment by WandererXII** [comment]
Thanks! I hope I can get a fix the upcoming week.

**Comment by WandererXII** [comment]
Fixed aef6c83482eeb1436f546fad904a29aea681b070, might need some testing on various deevices.
