### ISSUE TITLE
Czech Chu Shogi Set!

### ISSUE THREAD

**Issue by Eventlesstew** [WandererXII/lishogi#791]
I made a Czech Set for Chu Shogi! A lot of people needed this to be added, myself included lol.
[Chu FCZ.zip](https://github.com/WandererXII/lishogi/files/14465596/Chu.FCZ.zip)

Oh ye I also have a set for regular Shogi too.
[Shogi FCZ.zip](https://github.com/WandererXII/lishogi/files/14465616/Shogi.FCZ.zip)

**Comment by WandererXII** [comment]
These look great, thanks! Will be live in a week hopefully!

**Comment by Eventlesstew** [comment]
Yoooo thanks! I’m glad to have helped. :D
