### ISSUE TITLE
Preset for AI should be longer time controls

### ISSUE THREAD

**Issue by killerducky** [WandererXII/lishogi#798]
Before presets anonymous accounts that played vs bots just set time control to max. I don't think they want the pressure of a clock at all.

Maybe 30|0 or just go all the way to 180|0 because why not?

**Comment by WandererXII** [comment]
What about 15|0, 30|0, 45|0 or would it be better to have the same time control on all the ai levels. I kinda like the idea of less time for lower level and more time for higher level, but maybe having the same time for all would be cleaner.

**Comment by killerducky** [comment]
I think the logic for faster time on level 1 is "this level is so easy let's give some time pressure". But the target audience for level 1 is complete beginners that are spending lots of time just remembering how the pieces move. 

I think 30|0 for all is more reasonable, and I still wonder if just making it 180|0 to remove any clock pressure is better (but games eventually end to avoid server clogging).

Also for the other game settings, traditionally after 10|30 the next longer time control would be 15|60. Personally I find that too long but the majority will probably advocate for it. Maybe a compromise could be e.g. 15|40.

**Comment by gyermolenko** [comment]
thank you both for this tweak. Just after big update I still had to create a custom game just because preset time control was not long enough. So now I can just click a tile, that is convenient!
