### ISSUE TITLE
Board becomes sufficiently smaller in ongoing games on mobile devices

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [WandererXII/lishogi#799]
Puzzles, finished games and studies aren’t affected.
**Operating system and browser version**
iPhone SE, Safari
![5CE15288-73BA-4344-89B7-1C06475001AE](https://github.com/WandererXII/lishogi/assets/101206332/e4a7d262-fdc8-4148-9ade-3eaa6760b815)

**Comment by WandererXII** [comment]
That was on purpose. The idea is to have enough space for board, hands and moves. But I guess it's too small then, I will not reserve space for the moves then.

**Comment by Rechefiltr-is-Fire** [comment]
Bruh, on mobile device it anyway places hands along players, not sides. So why we resize the board & preserve side spaces which won’t be used?

**Comment by WandererXII** [comment]
Having space on the sides is essentially a side effect of making space on top/bottom:

Example on ipad mini - current with space on the side:
![image](https://github.com/WandererXII/lishogi/assets/43043181/6d362b66-44fb-44c8-a0ba-13d61709934a)
But if I don't limit space (allow it to use 100% width) - the board won't fit the screen, the clock and hands also won't fit:
![image](https://github.com/WandererXII/lishogi/assets/43043181/9c31c5cd-73f7-4140-90d2-cdb55df8e80f)
