### ISSUE TITLE
Pawn drop checkmate

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#81]
> Drop Pawn Mate (Japanese: 打ち歩詰め uchifudzume): A pawn may not be dropped to give an immediate checkmate. (This rule only applies specifically to pawns, drops and checkmates – to clarify, a player may deliver an immediate checkmate by dropping a non-pawn piece, a player may checkmate a king with a pawn that is already on the board, and a pawn may be dropped to give an immediate check as long as it does not also result in checkmate.)

https://en.wikipedia.org/wiki/Shogi#Drops

**Comment by Ivory-Pawn** [comment]
![uchifu](https://user-images.githubusercontent.com/58965808/99937670-9ce66580-2da9-11eb-9451-2cf8a4629a17.PNG)

**Comment by WandererXII** [comment]
Fixed, I plan to add status for this
