### ISSUE TITLE
Declining Adjournment is bugged!

### ISSUE THREAD

**Issue by Eventlesstew** [WandererXII/lishogi#815]
When my opponent offers Adjournment in Chu Shogi and I refuse, all sounds are disabled and I still get the "Sealed Move" prompt, meaning I can't offer/accept/refuse Draws, Adjournmnets, or even resign.

And when I offer Adjournment and my opponent refuses, the "Adjournment Offer Sent" pop-up is still there and I can't offer another Adjournment.

Any chance that this can be fixed?

![image](https://github.com/WandererXII/lishogi/assets/161836208/c7249ee9-7251-4931-9a57-ddfbd4924bf2)
![image](https://github.com/WandererXII/lishogi/assets/161836208/c5361d05-db29-4c5b-85d1-00cec67c8c2e)

**Comment by WandererXII** [comment]
Thanks a lot for reporting this! Will push live soon.
