### ISSUE TITLE
Opposing Prince Fix in Chu Shogi

### ISSUE THREAD

**Issue by Eventlesstew** [WandererXII/lishogi#819]
Saw that the Prince in my FCZ set was a bit bugged, so I fixed it.
![1_PRINCE](https://github.com/WandererXII/lishogi/assets/161836208/e6d42517-fcf0-4f93-8c44-2bc38484e3db)

**Comment by amdewitt** [comment]
The current piece is stored in

lishogi/public/piece/Chu_FCZ/1_Prince.svg

so the developers will need to update the code there.
