### ISSUE TITLE
Unable to drop (mobile browser)

### ISSUE THREAD

**Issue by mopmop325** [WandererXII/lishogi#82]
I played a game on mobile (Firefox, iOS) and found I couldn’t drop any pieces. My AI opponent could still drop.

**Comment by WandererXII** [comment]
Probably related to https://github.com/WandererXII/lishogi/issues/83, the only way to drop a piece right now is by dragging it. I plan to change this behaviour, because especially on mobile, this can be a bit slow and clumsy.

**Comment by WandererXII** [comment]
I will close this issue for now. If it was a game from position, I made some fixes, if it was the dragging, I'm planning on fixing/implementing that. If it was neither of those, feel free to reopen this issue. Thanks!
