### ISSUE TITLE
User tournaments not shown on calendar

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#821]
**Exact URL where the bug happened**
https://lishogi.org/tournament

**Steps to reproduce the bug**
1. Create a tournament
2. Tell other players to try to find it

**What did you expect to happen?**
User tournaments appear on tournament calendar (unlike Lichess which intentionally suppresses them because there are hundreds of tournaments)

**What happened instead?**
Tournament calendar does not include the new tournament

**Operating system and browser version**
N/A

**Comment by WandererXII** [comment]
Included user tours in various places here: https://github.com/WandererXII/lishogi/commit/3fa373e392b10dee2f7341b5dffdfb20bbcfcfb9
Good suggestion.
