### ISSUE TITLE
Default notation style from selected language

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#826]
Users who use Japanese language prefer to use Japanese notation:
![image](https://github.com/WandererXII/lishogi/assets/1834123/567c3492-2cad-4244-b5e0-169781158540)
https://twitter.com/__Honey_Mint/status/1789830419845943386

**Comment by WandererXII** [comment]
https://github.com/WandererXII/lishogi/commit/5e90403697849bc8ce7390e69a215da9a8ff43a5
