### ISSUE TITLE
Allow piece drops by clicking

### ISSUE THREAD

**Issue by Marken-Foo** [WandererXII/lishogi#83]
Currently, the only way to drop a piece on the board is by dragging it from the pocket. This is inconvenient for fast time controls.
It would be good to allow dropping by first clicking the piece in the pocket, then clicking a square on the board.

For reference, one implementation is on pychess: https://github.com/gbtami/pychess-variants/issues/5

This is also a request by Japanese players, see: https://lishogi.org/forum/lishogi-feedback/AgKZWS09

**Comment by WandererXII** [comment]
c6adb6a361620d96d13a816c44b08a956e3983a3, 3e96c114e9e2138df5d86f2090e9118bb5cec65d. I know there are some issues, like predrops, when piece is selected can't move pieces on board and select cancels after opponents round, if someone knows of another issue, please submit a new issue. Thanks!
