### ISSUE TITLE
Chat should be disabled while playing against anon user

### ISSUE THREAD

**Issue by rainfall-1917** [WandererXII/lishogi#831]
Theoretically it is possible that a named user can potentially send offensive message in the chat to an anon user( though why would someone do that is a separate issue)and in return the anon opponent can neither report nor retaliate  in such a hypothetical situation.So the most viable option would be to disable chat while such a game is played to potentially avoid cases of misconduct.

**Comment by WandererXII** [comment]
I think that chat can still be very useful here to completely disable it. And anon players can still hide the chat. Allowing reports from not registered users would probably cause more issues than it would solve...
