### ISSUE TITLE
API - autocomplete user name

### ISSUE THREAD

**Issue by ddugovic** [WandererXII/lishogi#847]
Suggestion: add feature https://lichess.org/api#tag/Users/operation/apiPlayerAutocomplete so Discord client (and someday a Lishogi mobile app) can autocomplete usernames.

**Comment by WandererXII** [comment]
This works https://lishogi.org/player/autocomplete?term=wander, I guess it's just not documented in the API doc.

**Comment by ddugovic** [comment]
Thank you; I will PR a documentation update.

**Comment by ddugovic** [comment]
I successfully tested the changes on my PC.
