### ISSUE TITLE
rook move not working in accessibility mode.

### ISSUE THREAD

**Issue by Majin-Buu611** [WandererXII/lishogi#853]
**Exact URL where the bug happened**
https://lishogi.org/D09iOLss/sente
**Steps to reproduce the bug**
Turn on accessibility mode(blind mode). After the king moves to 31, try to move the sente rook up to 11 to checkmate. I have tried the following: "r11+", "R11+", "r-11+", "R-11+", "r1511+"
**What did you expect to happen?**
I expected the rook to move up to 11 and checkmate.
**What happened instead?**
I was told that my move was invalid.
**Operating system and browser version**
Windows, Chrome

**Comment by WandererXII** [comment]
Thank you for reporting this!
