### ISSUE TITLE
Misleading drop move shown in analysis

### ISSUE THREAD

**Issue by Ogochi** [WandererXII/lishogi#858]
**Exact URL where the bug happened**

https://lishogi.org/analysis/standard/lns1k1snl/1rg6/pppp+Ppppp/9/4p4/9/PPPP1PPPP/1B5R1/LNSGKGSNL_b_BG_1

**Steps to reproduce the bug**

1. Tunr on computer analysis with multiple lines enabled
2. Create any position in Analysis where the best moves are a drop to the same place, but with a different pieces
3. Analysis will show the worst move from computer multiple lines on the board.

**What did you expect to happen?**

To display the best engine move on the board reflecting displayed evaluation in the right bar.

**What happened instead?**

Analysis has shown weaker move, which isn't a mate, while the eval bar presented "#1" meaning mate in 1.

**Operating system and browser version**

MacOS 14.6.1, Google Chrome Version 128.0.6613.85
<img width="1792" alt="Screenshot 2024-09-04 at 17 49 11" src="https://github.com/user-attachments/assets/ee73626c-4fa3-4e2b-99f1-f2df6cfc05af">

**Comment by WandererXII** [comment]
Thanks for reporting this. I could either fix it to show the best drop role - gold in this case. Or switch to arrows from hand pieces to board like this:
![image](https://github.com/user-attachments/assets/c26344a5-713a-4542-a7b6-719d7f5a124c)

This way all options are visible not just one piece which is nice, but it might be a bit more cluttered.
