### ISSUE TITLE
Sennichite with check is giving victory

### ISSUE THREAD

**Issue by kleffa** [WandererXII/lishogi#88]
https://lishogi.org/Hw02ww5fOeQQ
I played that so, I tryed force a sennichite with check, I should lose the game since repeating same position with checks is a ilegal manuver, I have no idea if this works in normal sennichite where it should be a draw

so basically repetition with continous checks is lose the game (now is winning)

**Comment by kleffa** [comment]
![image](https://user-images.githubusercontent.com/26838533/100144258-49414e00-2e75-11eb-81e6-b68faccdc711.png)
black (Sente) wins????

**Comment by WandererXII** [comment]
Thanks, that's really weird, I will fix this tomorrow.

**Comment by WandererXII** [comment]
Fixed yesterday, I hope I didn't screw it up this time. Thanks for making me aware of this! I still need to upload the perpetual check state to the frontend.
