### ISSUE TITLE
Suggestion: remove entry requirements for all open tournaments

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#93]
I think it makes sense to remove the <=x played games requirements for open tournaments, at least for now when fulfilling the requirements would take time due to few players, to encourage more people playing in them.

**Comment by WandererXII** [comment]
Good idea, I will remove or at least lower the requirements. I also need to solve some issues with tournament pairings before that.

**Comment by WandererXII** [comment]
Removed or lowered the conditions here https://github.com/WandererXII/lishogi/commit/ff6fd8a006684a50ec74fd1526496b9e68362e9f
But the tournament that had already been scheduled will not be affected by this. I will probably change it manually in the db.
