### ISSUE TITLE
Bug: analysis board breaks when trying to make branches in certain games

### ISSUE THREAD

**Issue by justremember** [WandererXII/lishogi#94]
For example in this game https://lishogi.org/TKxLTgiw/white#54, I cannot drop a piece that blocks the horse, the move is not reflected on the board and the dropped piece disappears from the "komadai". It seems to work properly in other games though, for example this: https://lishogi.org/bSaKru7G/white#35 and this: https://lishogi.org/bSaKru7G/white#35. It could be a unique bug in "From Position" games.

**Comment by WandererXII** [comment]
Thanks, fixed! You were right, it was because of 'from position' games. Needed to update ws server.
