### ISSUE TITLE
Feature Request: Add analysis circles/arrows for pieces in hand

### ISSUE THREAD

**Issue by rebeccaloran** [WandererXII/lishogi#97]
I feel that the ability to draw arrows and circles from the pieces in hand would be extremely helpful in analysis, especially when creating a Study position where you would be able to indicate a specific drop without having to write it in the comments.

As an aside, I would like to try to understand the dropping implementations of the code in order to work on additional issues involving them.

I would like to implement this feature and will look at the code ASAP to start working on it myself.

**Comment by WandererXII** [comment]
Good idea! Arrows from pieces in hand to board might be a bit harder to implement, currently shogiground is only able to calculate positions inside the board for pieces, arrows, circles and such - here for instance https://github.com/WandererXII/lishogi/blob/master/ui/shogiground/src/svg.ts#L157 and relations between pockets and the board also change depending on the size of the screen, thinking about it though, that should be solvable.
But what might also be good for indicating drops in study and even in normal games is the same mechanism engine in analysis indicates drop best moves which is by indirectly calling this function https://github.com/WandererXII/lishogi/blob/master/ui/shogiground/src/svg.ts#L179. That just displays the piece it wants to drop, but slightly transparent. We would need to think of some intuitive binding, maybe right-click on the piece in the hand before right-clicking on the board. This might be a bit easier to implement than the arrows from pockets to the board.

Dropping implementations are usually in a folder called "crazy" (from crazyhouse in chess). For instance here https://github.com/WandererXII/lishogi/blob/master/ui/analyse/src/crazy/crazyCtrl.ts

**Comment by WandererXII** [comment]
Added to analysis, will be added to games soon, if it works. e883dc638b0b22c74ab345aa55d95a092c88cf2c, bfeb68405eeb525cc8caa32cfe2476b55eefce78
