### ISSUE TITLE
Bug: Games lost versus SF do not display in "Losses" tab on profile

### ISSUE THREAD

**Issue by Marken-Foo** [WandererXII/lishogi#99]
Games lost against the SF engine ("Play with the computer" from the lobby) appear in the "Games" tab in the player's profile, but not in the "Losses" tab. Victories against SF do appear in the "Wins" tab.

For instance, "Games" tab:

![games](https://user-images.githubusercontent.com/41288521/100877771-374e5380-34e4-11eb-998f-22732cafc81e.png)

"Losses" tab:

![losses](https://user-images.githubusercontent.com/41288521/100877779-3a494400-34e4-11eb-9575-f4aa231a8f71.png)

**Comment by WandererXII** [comment]
Interesting, definitely an inconsistent behavior, but I just checked and the same thing happens on lichess. Thanks for submitting this I will fix after we get different notation systems and byo-yomi.

**Comment by WandererXII** [comment]
Fixed here https://github.com/WandererXII/lishogi/commit/5e382634b1cb3a88618cfd31b3c592056ee227f6, not live yet, but soon.
